/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import Homogenization.Sobolev.Foundations.H10Graph
public import Mathlib.MeasureTheory.Measure.SeparableMeasure

/-!
# Zero-trace Sobolev space

This file defines the Hilbert completion of the value-gradient graph of
`H10Function U`, together with its basic component maps and realization theorem.
-/

@[expose] public section

namespace SuperdiffusionCLT.Section8.DivergenceForm

open Homogenization
open scoped RealInnerProductSpace

section ZeroTraceSobolev

variable {d : ℕ} {U : Set (Vec d)}

private instance instFactTwoENNRealNeTop :
    Fact ((2 : ENNReal) ≠ ⊤) := ⟨by norm_num⟩

private noncomputable instance instCountablyGeneratedVec :
    MeasurableSpace.CountablyGenerated (Vec d) := inferInstance

private noncomputable instance instSFiniteVolumeMeasureOn :
    MeasureTheory.SFinite (volumeMeasureOn U) := inferInstance

private noncomputable instance instIsSeparableVolumeMeasureOn :
    MeasureTheory.IsSeparable (volumeMeasureOn U) := inferInstance

private noncomputable instance instSecondCountableScalarL2 :
    SecondCountableTopology (ScalarL2 U) := by
  exact MeasureTheory.Lp.SecondCountableTopology

private noncomputable instance instSecondCountableHilbertVectorL2 :
    SecondCountableTopology (HilbertVectorL2 U) := by
  exact MeasureTheory.Lp.SecondCountableTopology

noncomputable abbrev zeroTraceAmbient :=
  WithLp 2 (ScalarL2 U × HilbertVectorL2 U)

private noncomputable instance instSecondCountableZeroTraceAmbient :
    SecondCountableTopology (zeroTraceAmbient (U := U)) := inferInstance

noncomputable abbrev zeroTraceAmbientEquiv :
    zeroTraceAmbient (U := U) ≃L[ℝ] ScalarL2 U × HilbertVectorL2 U :=
  WithLp.prodContinuousLinearEquiv 2 ℝ (ScalarL2 U) (HilbertVectorL2 U)

noncomputable abbrev zeroTraceClosedSubmodule :
    ClosedSubmodule ℝ (zeroTraceAmbient (U := U)) :=
  (h10GraphClosedSubmodule U).comap
    (zeroTraceAmbientEquiv (U := U)).toContinuousLinearMap

/-- The Hilbert completion of the value–gradient graph generated by
`H10Function U`. On open bounded convex domains, every element has an honest
`H10Function` representative by `ZeroTraceSobolev.exists_h10Function`. -/
noncomputable def ZeroTraceSobolev (U : Set (Vec d)) : Type :=
  ↑(zeroTraceClosedSubmodule (U := U)).toSubmodule

namespace ZeroTraceSobolev

noncomputable instance : NormedAddCommGroup (ZeroTraceSobolev U) := by
  exact inferInstanceAs
    (NormedAddCommGroup (zeroTraceClosedSubmodule (U := U)).toSubmodule)

noncomputable instance : NormedSpace ℝ (ZeroTraceSobolev U) := by
  exact inferInstanceAs
    (NormedSpace ℝ (zeroTraceClosedSubmodule (U := U)).toSubmodule)

noncomputable instance : InnerProductSpace ℝ (ZeroTraceSobolev U) := by
  exact inferInstanceAs
    (InnerProductSpace ℝ (zeroTraceClosedSubmodule (U := U)).toSubmodule)

noncomputable instance : CompleteSpace (ZeroTraceSobolev U) := by
  change CompleteSpace (zeroTraceClosedSubmodule (U := U)).toSubmodule
  exact (zeroTraceClosedSubmodule (U := U)).isClosed.completeSpace_coe

noncomputable instance instSecondCountableTopology :
    SecondCountableTopology (ZeroTraceSobolev U) := by
  change SecondCountableTopology (zeroTraceClosedSubmodule (U := U)).toSubmodule
  infer_instance

/-- The scalar `L²` component of a zero-trace Sobolev element. -/
noncomputable def toL2 : ZeroTraceSobolev U →L[ℝ] ScalarL2 U :=
  (WithLp.fstL (p := 2) (𝕜 := ℝ) (α := ScalarL2 U) (β := HilbertVectorL2 U)).comp
    (zeroTraceClosedSubmodule (U := U)).toSubmodule.subtypeL

/-- The Hilbert-vector `L²` gradient of a zero-trace Sobolev element. -/
noncomputable def gradient : ZeroTraceSobolev U →L[ℝ] HilbertVectorL2 U :=
  (WithLp.sndL (p := 2) (𝕜 := ℝ) (α := ScalarL2 U) (β := HilbertVectorL2 U)).comp
    (zeroTraceClosedSubmodule (U := U)).toSubmodule.subtypeL

/-- Embed an honest zero-trace Sobolev function in its value–gradient graph
completion. -/
noncomputable def ofH10Function (u : H10Function U) : ZeroTraceSobolev U := by
  refine ⟨(zeroTraceAmbientEquiv (U := U)).symm
    (u.toH1Function.toScalarL2, u.toH1Function.gradToHilbertVectorL2), ?_⟩
  change
    (zeroTraceAmbientEquiv (U := U))
        ((zeroTraceAmbientEquiv (U := U)).symm
          (u.toH1Function.toScalarL2, u.toH1Function.gradToHilbertVectorL2)) ∈
      (h10GraphClosedSubmodule U).toSubmodule
  rw [(zeroTraceAmbientEquiv (U := U)).apply_symm_apply]
  exact (Submodule.le_topologicalClosure _) (h10_pair_mem_h10GraphSubmodule u)

@[simp] theorem toL2_ofH10Function (u : H10Function U) :
    toL2 (ofH10Function u) = u.toH1Function.toScalarL2 := by
  rfl

@[simp] theorem gradient_ofH10Function (u : H10Function U) :
    gradient (ofH10Function u) = u.toH1Function.gradToHilbertVectorL2 := by
  rfl

@[ext] theorem ext {u v : ZeroTraceSobolev U}
    (hvalue : toL2 u = toL2 v) (hgradient : gradient u = gradient v) :
    u = v := by
  apply Subtype.ext
  apply WithLp.ofLp_injective (p := 2)
  exact Prod.ext hvalue hgradient

theorem norm_sq_eq (u : ZeroTraceSobolev U) :
    ‖u‖ ^ 2 = ‖toL2 u‖ ^ 2 + ‖gradient u‖ ^ 2 := by
  exact WithLp.prod_norm_sq_eq_of_L2 u.1

/-- The scalar component has norm at most the full value--gradient norm. -/
theorem norm_toL2_le (u : ZeroTraceSobolev U) : ‖toL2 u‖ ≤ ‖u‖ := by
  rw [← sq_le_sq₀ (norm_nonneg _) (norm_nonneg _), norm_sq_eq]
  exact le_add_of_nonneg_right (sq_nonneg _)

/-- Recover an honest zero-trace Sobolev representative on the domains where
the pinned CoarseGraining graph-realization theorem applies. -/
theorem exists_h10Function [NeZero d] (hU : IsOpenBoundedConvexDomain U)
    (z : ZeroTraceSobolev U) :
    ∃ u : H10Function U,
      u.toH1Function.toScalarL2 = toL2 z ∧
      u.toH1Function.gradToHilbertVectorL2 = gradient z := by
  have hz :
      (zeroTraceAmbientEquiv (U := U)) z.1 ∈
        (h10GraphClosedSubmodule U).toSubmodule :=
    (ClosedSubmodule.mem_comap).1 z.2
  exact exists_h10Function_of_mem_h10GraphClosedSubmodule (U := U) hU hz

end ZeroTraceSobolev

end ZeroTraceSobolev

end SuperdiffusionCLT.Section8.DivergenceForm
