/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.Projective
public import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousMap

/-!
# Law uniqueness from finite-dimensional marginals

If the measurable space of a carrier is generated by a family of real-valued evaluation maps,
two probability measures with the same finite-dimensional marginals are equal.  The statement
is generic over the family and is later specialised to the shell carrier and to scalar
continuous fields.
-/

@[expose] public section

namespace SuperdiffusionCLT.Assumptions.ShellLaw.Model

open MeasureTheory MeasurableSpace

variable {Ω ι : Type*}

/-- The evaluation vector of a family of real-valued maps. -/
def nv_evalVec (ev : ι → Ω → ℝ) (ω : Ω) : ι → ℝ := fun i => ev i ω

theorem nv_eq_comap_evalVec [m : MeasurableSpace Ω] (ev : ι → Ω → ℝ)
    (hgen : m = ⨆ i, MeasurableSpace.comap (ev i) inferInstance) :
    m = MeasurableSpace.comap (nv_evalVec ev) inferInstance := by
  rw [hgen, MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  simp only [MeasurableSpace.comap_comp]
  rfl

theorem nv_measurable_evalVec [m : MeasurableSpace Ω] (ev : ι → Ω → ℝ)
    (hgen : m = ⨆ i, MeasurableSpace.comap (ev i) inferInstance) :
    Measurable (nv_evalVec ev) := by
  rw [nv_eq_comap_evalVec ev hgen]
  exact comap_measurable _

theorem nv_measurable_ev [m : MeasurableSpace Ω] (ev : ι → Ω → ℝ)
    (hgen : m = ⨆ i, MeasurableSpace.comap (ev i) inferInstance) (i : ι) :
    Measurable (ev i) :=
  (measurable_pi_iff.1 (nv_measurable_evalVec ev hgen)) i

/-- Two probability measures on a carrier generated by real evaluation maps with the same
finite-dimensional marginals are equal. -/
theorem nv_measure_ext_of_generatedBy_evaluations [m : MeasurableSpace Ω] (ev : ι → Ω → ℝ)
    (hgen : m = ⨆ i, MeasurableSpace.comap (ev i) inferInstance)
    (μ ν : Measure Ω) [IsProbabilityMeasure μ] [IsProbabilityMeasure ν]
    (h : ∀ s : Finset ι,
      μ.map (fun ω (i : s) => ev i ω) = ν.map (fun ω (i : s) => ev i ω)) :
    μ = ν := by
  have hΦ := nv_measurable_evalVec ev hgen
  have hres : ∀ s : Finset ι, Measurable (s.restrict : (ι → ℝ) → (s → ℝ)) := fun s =>
    measurable_pi_iff.2 fun i => measurable_pi_apply (i : ι)
  have hlim : (μ.map (nv_evalVec ev)) = ν.map (nv_evalVec ev) := by
    refine IsProjectiveLimit.unique (P := fun s : Finset ι => ν.map (fun ω (i : s) => ev i ω))
      (fun s => ?_) (fun s => ?_)
    · rw [Measure.map_map (hres s) hΦ]
      exact h s
    · rw [Measure.map_map (hres s) hΦ]
      rfl
  ext A hA
  rw [nv_eq_comap_evalVec ev hgen] at hA
  obtain ⟨B, hB, rfl⟩ := hA
  have h1 := congrArg (fun κ : Measure (ι → ℝ) => κ B) hlim
  simpa only [Measure.map_apply hΦ hB] using h1

/-- Two-measure form: if the evaluation marginals of `μ` pushed by `T` equal those of `ν`,
then `μ.map T = ν`. -/
theorem nv_map_eq_of_evaluation_marginals [m : MeasurableSpace Ω] (ev : ι → Ω → ℝ)
    (hgen : m = ⨆ i, MeasurableSpace.comap (ev i) inferInstance)
    (T : Ω → Ω) (hT : Measurable T) (μ ν : Measure Ω) [IsProbabilityMeasure μ]
    [IsProbabilityMeasure ν]
    (h : ∀ s : Finset ι,
      μ.map (fun ω (i : s) => ev i (T ω)) = ν.map (fun ω (i : s) => ev i ω)) :
    μ.map T = ν := by
  refine nv_measure_ext_of_generatedBy_evaluations ev hgen _ _ (fun s => ?_)
  have hs : Measurable (fun ω (i : s) => ev i ω) :=
    measurable_pi_iff.2 fun i => nv_measurable_ev ev hgen i
  rw [Measure.map_map hs hT]
  exact h s

/-- Invariance form: a measurable `T` preserving all finite-dimensional evaluation marginals
of a probability measure preserves the measure. -/
theorem nv_map_eq_self_of_evaluation_marginals [m : MeasurableSpace Ω] (ev : ι → Ω → ℝ)
    (hgen : m = ⨆ i, MeasurableSpace.comap (ev i) inferInstance)
    (T : Ω → Ω) (hT : Measurable T) (μ : Measure Ω) [IsProbabilityMeasure μ]
    (h : ∀ s : Finset ι,
      μ.map (fun ω (i : s) => ev i (T ω)) = μ.map (fun ω (i : s) => ev i ω)) :
    μ.map T = μ :=
  nv_map_eq_of_evaluation_marginals ev hgen T hT μ μ h

/-- Witness: the identity map on the real line with the single evaluation `id`. -/
example : (Measure.dirac (0 : ℝ)).map (id : ℝ → ℝ) = Measure.dirac 0 := by
  have h0 : IsProbabilityMeasure (Measure.dirac (0 : ℝ)) := inferInstance
  exact nv_map_eq_self_of_evaluation_marginals (Ω := ℝ) (ι := Unit) (fun _ => id)
    (by simp [MeasurableSpace.comap_id]) id measurable_id _ (fun _ => rfl)

end SuperdiffusionCLT.Assumptions.ShellLaw.Model
