/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousLinearMap
public import SuperdiffusionCLT.Assumptions.ShellLaw.Model.ShellAssembly
public import SuperdiffusionCLT.Assumptions.ShellLaw.Model.LawUniqueness
public import SuperdiffusionCLT.Assumptions.ShellLaw.Model.LawUniquenessB

/-!
# Law uniqueness for scalar `C^2` fields

The Borel sigma-algebra of the scalar carrier is generated by the value evaluations at points.
Consequently a map into the carrier is measurable as soon as its value evaluations (at
rational points) are measurable, and two probability laws with the same finite-dimensional
value marginals coincide.
-/

@[expose] public section

namespace SuperdiffusionCLT.Assumptions.ShellLaw.Model

open Homogenization MeasureTheory

variable {d : ℕ}

/-- Point evaluation of the value of a scalar field. -/
def nv_scalarEv (d : ℕ) : Vec d → ScalarC2Field d → ℝ := fun x f => f x

theorem nv_scalarEv_measurable (d : ℕ) (x : Vec d) : Measurable (nv_scalarEv d x) :=
  ScalarC2Field.measurable_eval x

theorem nv_scalar_borel_ambient (d : ℕ) : BorelSpace (ScalarAmbient d) := by
  have h1 : SecondCountableTopology C(Vec d, ℝ) := inferInstance
  have h2 : SecondCountableTopology C(Vec d, Vec d →L[ℝ] ℝ) := inferInstance
  have h3 : SecondCountableTopology C(Vec d, Vec d →L[ℝ] (Vec d →L[ℝ] ℝ)) := inferInstance
  have h4 : SecondCountableTopology (C(Vec d, Vec d →L[ℝ] ℝ) ×
      C(Vec d, Vec d →L[ℝ] (Vec d →L[ℝ] ℝ))) := inferInstance
  exact Prod.borelSpace

theorem nv_scalar_ms_eq (d : ℕ) :
    (inferInstance : MeasurableSpace (ScalarC2Field d)) =
      MeasurableSpace.comap (Subtype.val : ScalarC2Field d → ScalarAmbient d) inferInstance := by
  have := nv_scalar_borel_ambient d
  rw [BorelSpace.measurable_eq (α := ScalarAmbient d)]
  exact borel_comap

/-- The sigma-algebra generated by the value evaluations of the scalar carrier. -/
abbrev nv_scalarEvalSigma (d : ℕ) : MeasurableSpace (ScalarC2Field d) :=
  ⨆ x, MeasurableSpace.comap (nv_scalarEv d x) (inferInstance : MeasurableSpace ℝ)

theorem nv_scalar_val_measurable (d : ℕ) :
    Measurable[nv_scalarEvalSigma d] (Subtype.val : ScalarC2Field d → ScalarAmbient d) := by
  let _ : MeasurableSpace (ScalarC2Field d) := nv_scalarEvalSigma d
  have hv : ∀ x : Vec d, Measurable fun f : ScalarC2Field d => f x := fun x =>
    (comap_measurable (nv_scalarEv d x)).mono
      (le_iSup (fun x => MeasurableSpace.comap (nv_scalarEv d x) inferInstance) x) le_rfl
  have hB1 : BorelSpace (Vec d →L[ℝ] ℝ) := inferInstance
  have hS1 : SecondCountableTopology (Vec d →L[ℝ] ℝ) := inferInstance
  have hS0 : SecondCountableTopology ℝ := inferInstance
  have hR : RegularSpace (Vec d →L[ℝ] Vec d →L[ℝ] ℝ) :=
    @UniformSpace.to_regularSpace _
      (PseudoMetricSpace.toUniformSpace (self := SeminormedAddCommGroup.toPseudoMetricSpace
        (self := NormedAddCommGroup.toSeminormedAddCommGroup
          (E := Vec d →L[ℝ] Vec d →L[ℝ] ℝ))))
  have hD1 : ∀ x : Vec d, Measurable fun f : ScalarC2Field d => ScalarC2Field.deriv f x := fun x =>
    nv_measurable_clm_of_apply inferInstance hS0 _ fun v =>
      nv_measurable_dirDeriv inferInstance hS0 (fun (f : ScalarC2Field d) (y : Vec d) => f y)
        (fun f y => ScalarC2Field.deriv f y) ScalarC2Field.hasFDerivAt hv x v
  have hD2 : ∀ x : Vec d, Measurable fun f : ScalarC2Field d => ScalarC2Field.secondDeriv f x :=
    fun x => nv_measurable_clm_of_apply hB1 hS1 _ fun v =>
      nv_measurable_dirDeriv hB1 hS1
        (fun (f : ScalarC2Field d) (y : Vec d) => ScalarC2Field.deriv f y)
        (fun f y => ScalarC2Field.secondDeriv f y) ScalarC2Field.deriv_hasFDerivAt hD1 x v
  exact (ContinuousMap.measurable_iff_eval.2 hv).prodMk
    ((ContinuousMap.measurable_iff_eval.2 hD1).prodMk (ContinuousMap.measurable_iff_eval.2 hD2))

/-- The Borel sigma-algebra of the scalar carrier is generated by value evaluations. -/
theorem nv_scalarField_generatedBy_eval (d : ℕ) :
    (inferInstance : MeasurableSpace (ScalarC2Field d)) = nv_scalarEvalSigma d := by
  refine le_antisymm ?_ (iSup_le fun x => (nv_scalarEv_measurable d x).comap_le)
  rw [nv_scalar_ms_eq d]
  exact (measurable_iff_comap_le (m₁ := nv_scalarEvalSigma d)).1 (nv_scalar_val_measurable d)

/-- A rational point of `Vec d`. -/
def nv_ratPt (d : ℕ) (q : Fin d → ℚ) : Vec d := fun i => (q i : ℝ)

theorem nv_denseRange_ratPt (d : ℕ) : DenseRange (nv_ratPt d) :=
  DenseRange.piMap (fun _ : Fin d => Rat.denseRange_cast (𝕜 := ℝ))

/-- Pointwise measurability of a continuous-in-the-point family follows from rational points. -/
theorem nv_measurable_of_rational {Ω : Type*} [MeasurableSpace Ω] (F : Ω → Vec d → ℝ)
    (hc : ∀ ω, Continuous (F ω)) (h : ∀ q, Measurable fun ω => F ω (nv_ratPt d q)) (x : Vec d) :
    Measurable fun ω => F ω x := by
  have hx : x ∈ closure (Set.range (nv_ratPt d)) := (nv_denseRange_ratPt d) x
  obtain ⟨u, hu, hlim⟩ := mem_closure_iff_seq_limit.1 hx
  choose q hq using hu
  refine measurable_of_tendsto_metrizable (fun n => h (q n)) (tendsto_pi_nhds.2 fun ω => ?_)
  have : Filter.Tendsto (fun n => nv_ratPt d (q n)) Filter.atTop (nhds x) := by
    simpa only [hq] using hlim
  exact ((hc ω).tendsto x).comp this

/-- A map into the scalar carrier is measurable iff its value at rational points is. -/
theorem nv_measurable_scalar_iff_rational {Ω : Type*} [MeasurableSpace Ω]
    (g : Ω → ScalarC2Field d) :
    Measurable g ↔ ∀ q : Fin d → ℚ, Measurable fun ω => g ω (nv_ratPt d q) := by
  refine ⟨fun hg q => (ScalarC2Field.measurable_eval _).comp hg, fun h => ?_⟩
  have hx := nv_measurable_of_rational (fun ω => g ω) (fun ω => (g ω).1.1.continuous) h
  rw [measurable_iff_comap_le]
  refine le_of_eq_of_le (congrArg (MeasurableSpace.comap g) (nv_scalarField_generatedBy_eval d)) ?_
  rw [MeasurableSpace.comap_iSup]
  refine iSup_le fun x => ?_
  rw [MeasurableSpace.comap_comp]
  exact (hx x).comap_le

/-- A map into the scalar carrier is measurable iff its value and stored derivatives at every
(rational) point are measurable. -/
theorem nv_measurable_scalar_iff_eval {Ω : Type*} [MeasurableSpace Ω] (g : Ω → ScalarC2Field d) :
    Measurable g ↔ (∀ x, Measurable fun ω => g ω x) ∧
      (∀ x v, Measurable fun ω => (g ω).deriv x v) ∧
      (∀ x v w, Measurable fun ω => (g ω).secondDeriv x v w) := by
  refine ⟨fun hg => ⟨fun x => (ScalarC2Field.measurable_eval x).comp hg,
    fun x v => (ScalarC2Field.measurable_eval_deriv x v).comp hg,
    fun x v w => (ScalarC2Field.measurable_eval_secondDeriv x v w).comp hg⟩, fun h => ?_⟩
  exact (nv_measurable_scalar_iff_rational g).2 fun q => h.1 _

/-- Two-measure transport form on the scalar carrier. -/
theorem nv_scalarField_map_eq (d : ℕ) (T : ScalarC2Field d → ScalarC2Field d)
    (hT : Measurable T) (μ ν : Measure (ScalarC2Field d))
    [IsProbabilityMeasure μ] [IsProbabilityMeasure ν]
    (h : ∀ s : Finset (Vec d),
      μ.map (fun f (x : s) => T f (x : Vec d)) = ν.map (fun f (x : s) => f (x : Vec d))) :
    μ.map T = ν :=
  nv_map_eq_of_evaluation_marginals (nv_scalarEv d) (nv_scalarField_generatedBy_eval d) T hT μ ν h

/-- Invariance form on the scalar carrier. -/
theorem nv_scalarField_map_eq_self (d : ℕ) (T : ScalarC2Field d → ScalarC2Field d)
    (hT : Measurable T) (μ : Measure (ScalarC2Field d)) [IsProbabilityMeasure μ]
    (h : ∀ s : Finset (Vec d),
      μ.map (fun f (x : s) => T f (x : Vec d)) = μ.map (fun f (x : s) => f (x : Vec d))) :
    μ.map T = μ :=
  nv_scalarField_map_eq d T hT μ μ h

/-- Witness: the identity preserves a Dirac law on the scalar carrier. -/
example (f : ScalarC2Field d) :
    (Measure.dirac f).map (id : ScalarC2Field d → ScalarC2Field d) = Measure.dirac f := by
  have : IsProbabilityMeasure (Measure.dirac f) := inferInstance
  exact nv_scalarField_map_eq_self d id measurable_id _ (fun _ => rfl)

end SuperdiffusionCLT.Assumptions.ShellLaw.Model
