/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Assumptions.ShellLaw.Model.SeedIndepD
public import SuperdiffusionCLT.Assumptions.ShellLaw.Model.SeedShellLaw

/-!
# Independence of the seed shell law on separated sets

The scalar seed law `nv_seedLaw d ε` has independent value sigma-algebras on sets at Euclidean
distance at least one, and so has the seed shell law, whose entries are independent scalar seeds.
Since the restriction sigma-algebra of a shell field is generated by values on the set, this is the
range of dependence of the seed shell in the exact form of the restriction statement.

## Main results

* `nv_indep_scalarValSigma`: scalar seed law
* `nv_indep_seedShell_valSigma`: seed shell law, value sigma-algebras
* `nv_seedShell_indep_restriction`: restriction sigma-algebras at distance `√d`
-/

@[expose] public section

namespace SuperdiffusionCLT.Assumptions.ShellLaw.Model

open Homogenization MeasureTheory ProbabilityTheory
open SuperdiffusionCLT.Frozen.Assumptions

noncomputable section

variable {d : ℕ}

/-- The sigma-algebra on scalar fields generated by the values at the points of `S`. -/
@[instance_reducible]
def nv_scalarValSigma (S : Set (Vec d)) : MeasurableSpace (ScalarC2Field d) :=
  ⨆ x : S, MeasurableSpace.comap (fun f : ScalarC2Field d ↦ f (x : Vec d)) inferInstance

theorem nv_scalarValSigma_le (S : Set (Vec d)) :
    nv_scalarValSigma S ≤ (inferInstance : MeasurableSpace (ScalarC2Field d)) :=
  iSup_le fun x ↦ (ScalarC2Field.measurable_eval (x : Vec d)).comap_le

theorem nv_comap_seedMap_scalarValSigma_le (ε : ℝ) (S : Set (Vec d)) :
    MeasurableSpace.comap (nv_seedMap ε) (nv_scalarValSigma S) ≤ nv_evalSigma S := by
  unfold nv_scalarValSigma nv_evalSigma
  rw [MeasurableSpace.comap_iSup]
  refine iSup_mono fun x ↦ ?_
  rw [MeasurableSpace.comap_comp]
  have h : (fun ξ : NvNoise d ↦ nv_seedMap ε ξ (x : Vec d)) =
      (fun r : ℝ ↦ ε * r) ∘ fun ξ ↦ nv_seed ξ (x : Vec d) := by
    funext ξ; rfl
  change MeasurableSpace.comap (fun ξ : NvNoise d ↦ nv_seedMap ε ξ (x : Vec d)) _ ≤ _
  rw [h, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono (measurable_const.mul measurable_id).comap_le

/-- **Independence of the scaled scalar seed on separated sets.** -/
theorem nv_indep_scalarValSigma (ε : ℝ) (U V : Set (Vec d))
    (h : ∀ ⦃x y : Vec d⦄, x ∈ U → y ∈ V → 1 ≤ Book.Ch02.vecNorm (x - y)) :
    Indep (nv_scalarValSigma U) (nv_scalarValSigma V) (nv_seedLaw d ε) := by
  unfold nv_seedLaw
  refine nv_indep_map _ _ _ _ (nv_measurable_seedMap ε) (nv_scalarValSigma_le U)
    (nv_scalarValSigma_le V) ?_
  exact indep_of_indep_of_le_right
    (indep_of_indep_of_le_left (nv_indep_evalSigma U V h) (nv_comap_seedMap_scalarValSigma_le ε U))
    (nv_comap_seedMap_scalarValSigma_le ε V)

theorem nv_measurable_skewCoef_of_coord {Ω : Type*} [MeasurableSpace Ω] (c : SkewIdx d → Ω → ℝ)
    (hc : ∀ p, Measurable (c p)) (i k : Fin d) :
    Measurable fun ω ↦ nv_skewCoef (fun p ↦ c p ω) i k := by
  unfold nv_skewCoef
  by_cases h : i < k
  · simp only [h, dite_true]; exact hc _
  · by_cases h' : k < i
    · simp only [h, h', dite_true, dite_false]; exact (hc _).neg
    · simp only [h, h', dite_false]; exact measurable_const

theorem nv_comap_assembleSkew_valSigma_le (U : Set (Vec d)) :
    MeasurableSpace.comap (assembleSkew (d := d)) (nv_shellValSigma U) ≤
      ⨆ p : SkewIdx d, MeasurableSpace.comap (fun φ : SkewIdx d → ScalarC2Field d ↦ φ p)
        (nv_scalarValSigma U) := by
  unfold nv_shellValSigma
  rw [MeasurableSpace.comap_iSup]
  refine iSup_le fun x ↦ ?_
  rw [MeasurableSpace.comap_iSup]
  refine iSup_le fun i ↦ ?_
  rw [MeasurableSpace.comap_iSup]
  refine iSup_le fun k ↦ ?_
  rw [MeasurableSpace.comap_comp]
  refine Measurable.comap_le ?_
  have hc : ∀ p : SkewIdx d, Measurable[⨆ q : SkewIdx d, MeasurableSpace.comap
      (fun φ : SkewIdx d → ScalarC2Field d ↦ φ q) (nv_scalarValSigma U)]
      fun φ : SkewIdx d → ScalarC2Field d ↦ φ p (x : Vec d) := fun p ↦ by
    have h1 : Measurable[MeasurableSpace.comap
        (fun φ : SkewIdx d → ScalarC2Field d ↦ φ p) (nv_scalarValSigma U)]
        fun φ : SkewIdx d → ScalarC2Field d ↦ φ p (x : Vec d) :=
      @Measurable.comp _ _ _ (MeasurableSpace.comap
        (fun φ : SkewIdx d → ScalarC2Field d ↦ φ p) (nv_scalarValSigma U))
        (nv_scalarValSigma U) _ (fun f : ScalarC2Field d ↦ f (x : Vec d)) _
        (by
          have h0 : Measurable[nv_scalarValSigma U] fun f : ScalarC2Field d ↦ f (x : Vec d) :=
            Measurable.mono (comap_measurable _) (le_iSup (fun y : U ↦ MeasurableSpace.comap
              (fun f : ScalarC2Field d ↦ f (y : Vec d)) inferInstance) x) le_rfl
          exact h0)
        (comap_measurable _)
    exact h1.mono (le_iSup (fun q : SkewIdx d ↦ MeasurableSpace.comap
      (fun φ : SkewIdx d → ScalarC2Field d ↦ φ q) (nv_scalarValSigma U)) p) le_rfl
  have e : ((fun j : ShellField d ↦ j (x : Vec d) i k) ∘ assembleSkew) =
      fun φ : SkewIdx d → ScalarC2Field d ↦ nv_skewCoef (fun p ↦ φ p (x : Vec d)) i k :=
    funext fun φ ↦ assembleSkew_apply φ (x : Vec d) i k
  rw [e]
  exact @nv_measurable_skewCoef_of_coord d _ (⨆ q : SkewIdx d, MeasurableSpace.comap
      (fun φ : SkewIdx d → ScalarC2Field d ↦ φ q) (nv_scalarValSigma U))
    (fun p φ ↦ φ p (x : Vec d)) hc i k

end

end SuperdiffusionCLT.Assumptions.ShellLaw.Model
