/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Assumptions.ShellLaw.Model.SeedIndepC

/-!
# Independence for products and for push-forwards

Two general facts used to pass from the noise space to the assembled skew field:

* if two sub-sigma-algebras `A`, `B` are independent for `μ`, then the sigma-algebras generated by
  their coordinate pullbacks on a finite product are independent for the product measure;
* independence of pullbacks along a measurable map `T` gives independence of the sigma-algebras
  themselves under the push-forward law.
-/

@[expose] public section

namespace SuperdiffusionCLT.Assumptions.ShellLaw.Model

open Homogenization MeasureTheory ProbabilityTheory

noncomputable section

/-- Independent sub-sigma-algebras stay independent, coordinatewise, in a finite product. The
sub-sigma-algebras are bundled with their comparison to the ambient one so that they are not taken
for measurable-space instances. -/
theorem nv_indep_pi {ι Ω : Type*} [Fintype ι] [mΩ : MeasurableSpace Ω]
    (A B : {m : MeasurableSpace Ω // m ≤ mΩ}) (μ : Measure Ω) [IsProbabilityMeasure μ]
    (h : Indep A.1 B.1 μ) :
    Indep (⨆ p : ι, MeasurableSpace.comap (fun ω : ι → Ω ↦ ω p) A.1)
      (⨆ p : ι, MeasurableSpace.comap (fun ω : ι → Ω ↦ ω p) B.1)
      (Measure.pi fun _ : ι ↦ μ) := by
  classical
  have hgA := @generateFrom_pi ι (fun _ ↦ Ω) _ (fun _ ↦ A.1)
  have hgB := @generateFrom_pi ι (fun _ ↦ Ω) _ (fun _ ↦ B.1)
  have hpA := @isPiSystem_pi ι (fun _ ↦ Ω) (fun _ ↦ A.1)
  have hpB := @isPiSystem_pi ι (fun _ ↦ Ω) (fun _ ↦ B.1)
  have hle : ∀ C : {m : MeasurableSpace Ω // m ≤ mΩ},
      (⨆ p : ι, MeasurableSpace.comap (fun ω : ι → Ω ↦ ω p) C.1) ≤
        (MeasurableSpace.pi : MeasurableSpace (ι → Ω)) := fun C ↦
    iSup_le fun p ↦ (MeasurableSpace.comap_mono C.2).trans
      (le_iSup (fun p : ι ↦ MeasurableSpace.comap (fun ω : ι → Ω ↦ ω p) mΩ) p)
  refine IndepSets.indep (hle A) (hle B) hpA hpB hgA.symm hgB.symm ?_
  rw [IndepSets_iff]
  rintro _ _ ⟨E, hE, rfl⟩ ⟨F, hF, rfl⟩
  rw [← Set.pi_inter_distrib, Measure.pi_pi, Measure.pi_pi, Measure.pi_pi,
    ← Finset.prod_mul_distrib]
  refine Finset.prod_congr rfl fun p _ ↦ ?_
  exact (Indep_iff _ _ _).1 h _ _ (hE p (Set.mem_univ p)) (hF p (Set.mem_univ p))

/-- Independence of pullbacks under a measurable map gives independence under the push-forward. -/
theorem nv_indep_map {Ω Ω' : Type*} (A B : MeasurableSpace Ω') [mΩ : MeasurableSpace Ω]
    [mΩ' : MeasurableSpace Ω'] (μ : Measure Ω) (T : Ω → Ω') (hT : Measurable T)
    (hA : A ≤ mΩ') (hB : B ≤ mΩ')
    (h : Indep (MeasurableSpace.comap T A) (MeasurableSpace.comap T B) μ) :
    Indep A B (μ.map T) := by
  rw [Indep_iff] at h ⊢
  intro s t hs ht
  have hsM := hA _ hs
  have htM := hB _ ht
  rw [Measure.map_apply hT (hsM.inter htM), Measure.map_apply hT hsM, Measure.map_apply hT htM,
    Set.preimage_inter]
  exact h _ _ ⟨s, hs, rfl⟩ ⟨t, ht, rfl⟩

/-- On a subsingleton every pair of sub-sigma-algebras is independent. -/
theorem nv_indep_of_subsingleton {Ω : Type*} (A B : MeasurableSpace Ω) [mΩ : MeasurableSpace Ω]
    [Subsingleton Ω] (μ : Measure Ω) [IsProbabilityMeasure μ] :
    Indep A B μ := by
  rw [Indep_iff]
  intro s t _ _
  rcases s.eq_empty_or_nonempty with rfl | hs
  · simp
  rcases t.eq_empty_or_nonempty with rfl | ht
  · simp
  have h1 : s = Set.univ := Set.eq_univ_of_forall fun x ↦ by
    obtain ⟨y, hy⟩ := hs; rwa [Subsingleton.elim x y]
  have h2 : t = Set.univ := Set.eq_univ_of_forall fun x ↦ by
    obtain ⟨y, hy⟩ := ht; rwa [Subsingleton.elim x y]
  simp [h1, h2]

end

end SuperdiffusionCLT.Assumptions.ShellLaw.Model
