/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Assumptions.ShellLaw.Model.SeedIndepB
public import SuperdiffusionCLT.Assumptions.ShellField.RestrictionSigma

/-!
# The restriction sigma-algebra is generated by values on the set

For a measurable set `U`, the pointwise-restriction sigma-algebra of shell fields is contained in
the sigma-algebra generated by the matrix-entry values at the points of `U`. The proof of the
integral lane uses that a family of functions continuous on `U` and measurable at each point of
`U` has measurable parametric integrals against `1_U`.

## Main results

* `nv_measurable_integral_indicator`: parametric integral of a Caratheodory family on `U`
* `nv_shellValSigma`: the sigma-algebra generated by the entry values at the points of `U`
* `nv_shellRestrictionSigma_le`: `shellRestrictionSigma U hU ≤ nv_shellValSigma U`
-/

@[expose] public section

namespace SuperdiffusionCLT.Assumptions.ShellLaw.Model

open Homogenization MeasureTheory ProbabilityTheory
open SuperdiffusionCLT.Frozen.Assumptions

noncomputable section

variable {d : ℕ}

/-- A family continuous on `U`, measurable at each point of `U`, is jointly measurable after
restriction to `U`. -/
theorem nv_measurable_indicator_uncurry {Ω : Type*} [MeasurableSpace Ω] (F : Ω → Vec d → ℝ)
    {U : Set (Vec d)} (hU : MeasurableSet U) (hc : ∀ ω, ContinuousOn (F ω) U)
    (hm : ∀ x ∈ U, Measurable fun ω ↦ F ω x) :
    Measurable fun p : Vec d × Ω ↦ U.indicator (F p.2) p.1 := by
  classical
  let u : U → Ω → ℝ := fun x ω ↦ F ω x
  have hu : Measurable (Function.uncurry u) :=
    measurable_uncurry_of_continuous_of_measurable
      (fun ω ↦ (hc ω).domRestrict) (fun x ↦ hm x.1 x.2)
  have hs : MeasurableSet {p : Vec d × Ω | p.1 ∈ U} := measurable_fst hU
  have hf : Measurable fun q : {p : Vec d × Ω | p.1 ∈ U} ↦
      Function.uncurry u (⟨q.1.1, q.2⟩, q.1.2) :=
    hu.comp ((Measurable.subtype_mk (measurable_fst.comp (measurable_subtype_coe))).prodMk
      (measurable_snd.comp measurable_subtype_coe))
  have h := Measurable.dite (s := {p : Vec d × Ω | p.1 ∈ U}) hf
    (measurable_const (a := (0 : ℝ))) hs
  convert h using 1
  funext p
  by_cases hp : p.1 ∈ U
  · simp [hp, u]
  · simp [hp]

/-- **Measurable parametric integrals.** -/
theorem nv_measurable_integral_indicator {Ω : Type*} [MeasurableSpace Ω] (F : Ω → Vec d → ℝ)
    {U : Set (Vec d)} (hU : MeasurableSet U) (hc : ∀ ω, ContinuousOn (F ω) U)
    (hm : ∀ x ∈ U, Measurable fun ω ↦ F ω x) {φ : Vec d → ℝ} (hφ : Measurable φ) :
    Measurable fun ω ↦ ∫ x, U.indicator (F ω) x * φ x ∂volume := by
  have h1 := nv_measurable_indicator_uncurry F hU hc hm
  have h2 : Measurable fun p : Ω × Vec d ↦ U.indicator (F p.1) p.2 * φ p.2 :=
    (h1.comp measurable_swap).mul (hφ.comp measurable_snd)
  exact h2.stronglyMeasurable.integral_prod_right'.measurable

/-- The sigma-algebra on shell fields generated by the matrix-entry values at the points of `U`. -/
@[instance_reducible]
def nv_shellValSigma (U : Set (Vec d)) : MeasurableSpace (ShellField d) :=
  ⨆ (x : U) (i : Fin d) (k : Fin d),
    MeasurableSpace.comap (fun j : ShellField d ↦ j (x : Vec d) i k) inferInstance

theorem nv_shellValSigma_le (U : Set (Vec d)) :
    nv_shellValSigma U ≤ shellFieldMeasurableSpace d :=
  iSup_le fun x ↦ iSup_le fun i ↦ iSup_le fun k ↦
    (ShellField.measurable_eval_entry (x : Vec d) i k).comap_le

theorem nv_measurable_entry_valSigma (U : Set (Vec d)) {x : Vec d} (hx : x ∈ U) (i k : Fin d) :
    Measurable[nv_shellValSigma U] fun j : ShellField d ↦ j x i k := by
  have h : Measurable[MeasurableSpace.comap (fun j : ShellField d ↦ j x i k) inferInstance]
      fun j : ShellField d ↦ j x i k := comap_measurable _
  refine h.mono ?_ le_rfl
  exact le_iSup_of_le (⟨x, hx⟩ : U) (le_iSup_of_le i (le_iSup_of_le k le_rfl))

theorem nv_restrict_entry_eq (U : Set (Vec d)) (hU : MeasurableSet U) (j : ShellField d)
    (x : Vec d) (i k : Fin d) :
    restrictReg U hU (ShellField.forgetShell j) x i k = U.indicator (fun y ↦ j y i k) x :=
  restrictReg_apply_entry U hU (ShellField.forgetShell j) x i k

theorem nv_measurable_restrictReg_entry (U : Set (Vec d)) (hU : MeasurableSet U) (x : Vec d)
    (i k : Fin d) :
    Measurable[nv_shellValSigma U] fun j : ShellField d ↦ restrictReg U hU (ShellField.forgetShell j) x i k := by
  have e : (fun j : ShellField d ↦ restrictReg U hU (ShellField.forgetShell j) x i k) =
      fun j : ShellField d ↦ U.indicator (fun y ↦ j y i k) x :=
    funext fun j ↦ nv_restrict_entry_eq U hU j x i k
  rw [e]
  by_cases hx : x ∈ U
  · have h := nv_measurable_entry_valSigma U hx i k
    simpa only [Set.indicator_of_mem hx] using h
  · simpa only [Set.indicator_of_notMem hx] using
      (measurable_const : Measurable[nv_shellValSigma U] fun _ : ShellField d ↦ (0 : ℝ))

theorem nv_measurable_restrictReg_entryTest (U : Set (Vec d)) (hU : MeasurableSet U)
    (i k : Fin d) {φ : Vec d → ℝ} (hφ : IsProbeR φ) :
    Measurable[nv_shellValSigma U] fun j : ShellField d ↦
      entryTestR i k φ (restrictReg U hU (ShellField.forgetShell j)) := by
  let _ : MeasurableSpace (ShellField d) := nv_shellValSigma U
  have h := nv_measurable_integral_indicator (fun (j : ShellField d) (y : Vec d) ↦ j y i k) hU
    (fun j ↦ ((continuous_apply k).comp ((continuous_apply i).comp
      j.1.1.continuous)).continuousOn)
    (fun x hx ↦ nv_measurable_entry_valSigma U hx i k) hφ.measurable
  have e : (fun j : ShellField d ↦ entryTestR i k φ (restrictReg U hU (ShellField.forgetShell j))) =
      fun j : ShellField d ↦ ∫ x, U.indicator (fun y ↦ j y i k) x * φ x ∂volume := by
    funext j
    simp only [entryTestR, nv_restrict_entry_eq]
  rw [e]
  exact h

theorem nv_measurable_pi_entries {Ω : Type*} [MeasurableSpace Ω] (g : Ω → Vec d → Mat d)
    (h : ∀ x i k, Measurable fun ω ↦ g ω x i k) :
    @Measurable Ω (Vec d → Mat d) _ MeasurableSpace.pi g :=
  measurable_pi_iff.2 fun x ↦ measurable_pi_iff.2 fun i ↦ measurable_pi_iff.2 fun k ↦ h x i k

theorem nv_measurable_restrictReg_valSigma (U : Set (Vec d)) (hU : MeasurableSet U) :
    Measurable[nv_shellValSigma U] fun j : ShellField d ↦
      restrictReg U hU (ShellField.forgetShell j) := by
  rw [measurable_iff_comap_le]
  change MeasurableSpace.comap _ (pointwiseSigmaR d ⊔ entryTestSigmaR d) ≤ _
  rw [MeasurableSpace.comap_sup]
  refine sup_le ?_ ?_
  · unfold pointwiseSigmaR
    rw [MeasurableSpace.comap_comp]
    refine Measurable.comap_le ?_
    exact @nv_measurable_pi_entries d (ShellField d) (nv_shellValSigma U)
      (fun j ↦ (restrictReg U hU (ShellField.forgetShell j)).toFun)
      (fun x i k ↦ nv_measurable_restrictReg_entry U hU x i k)
  · unfold entryTestSigmaR
    rw [MeasurableSpace.comap_generateFrom]
    refine MeasurableSpace.generateFrom_le ?_
    rintro _ ⟨_, ⟨i, k, φ, hφ, t, ht, rfl⟩, rfl⟩
    exact nv_measurable_restrictReg_entryTest U hU i k hφ ht

/-- **The restriction sigma-algebra is generated by the values on the set.** -/
theorem nv_shellRestrictionSigma_le (U : Set (Vec d)) (hU : MeasurableSet U) :
    ShellField.shellRestrictionSigma U hU ≤ nv_shellValSigma U :=
  (measurable_iff_comap_le.1 (nv_measurable_restrictReg_valSigma U hU))

end

end SuperdiffusionCLT.Assumptions.ShellLaw.Model
