/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Assumptions.ShellLaw.Model.SeedIndep
import Mathlib.Probability.Distributions.Gaussian.IsGaussianProcess.Basic

/-!
# Independence of the seed field on separated sets

For sets `U`, `V` at Euclidean distance at least one the sigma-algebras generated by the values of
the seed field at the points of `U`, respectively `V`, are independent under the noise law. Only
values are used: the restriction sigma-algebra of a shell field depends on values alone, and the
stored derivatives are limits of values, so no derivative covariance and no open-set hypothesis is
needed.

## Main results

* `nv_evalSigma`: the sigma-algebra generated by the seed values on a set
* `nv_indep_evalSigma`: independence for sets at distance at least one
-/

@[expose] public section

namespace SuperdiffusionCLT.Assumptions.ShellLaw.Model

open Homogenization MeasureTheory ProbabilityTheory

noncomputable section

variable {d : ℕ}

/-- The sigma-algebra on the noise space generated by the seed values at the points of `S`. -/
@[instance_reducible]
def nv_evalSigma (S : Set (Vec d)) : MeasurableSpace (NvNoise d) :=
  ⨆ x : S, MeasurableSpace.comap (fun ξ : NvNoise d ↦ nv_seed ξ (x : Vec d)) inferInstance

theorem nv_comap_pi_eq_evalSigma (S : Set (Vec d)) :
    MeasurableSpace.comap (fun (ξ : NvNoise d) (x : S) ↦ nv_seed ξ (x : Vec d))
      (MeasurableSpace.pi) = nv_evalSigma S := by
  unfold nv_evalSigma MeasurableSpace.pi
  rw [MeasurableSpace.comap_iSup]
  refine iSup_congr fun x ↦ ?_
  rw [MeasurableSpace.comap_comp]
  rfl

/-- **Independence of the seed field on separated sets.** -/
theorem nv_indep_evalSigma (U V : Set (Vec d))
    (h : ∀ ⦃x y : Vec d⦄, x ∈ U → y ∈ V → 1 ≤ Book.Ch02.vecNorm (x - y)) :
    Indep (nv_evalSigma U) (nv_evalSigma V) (nvNoiseLaw d) := by
  have hXY : IsGaussianProcess
      (Sum.elim (fun (x : U) (ξ : NvNoise d) ↦ nv_seed ξ (x : Vec d))
        (fun (y : V) (ξ : NvNoise d) ↦ nv_seed ξ (y : Vec d))) (nvNoiseLaw d) := by
    have := nv_isGaussianProcess_seed.comp_right
      (Sum.elim (Subtype.val : U → Vec d) (Subtype.val : V → Vec d))
    convert this using 1
    funext s ξ
    rcases s with s | s <;> rfl
  have hI := IsGaussianProcess.indepFun_of_covariance_eq_zero hXY
    (fun x ↦ (nv_measurable_seed (x : Vec d)).aemeasurable)
    (fun y ↦ (nv_measurable_seed (y : Vec d)).aemeasurable)
    (fun x y ↦ nv_covariance_seed_eq_zero_of_one_le_vecNorm (h x.2 y.2))
  have h2 := (IndepFun_iff_Indep _ _ _).1 hI
  rw [nv_comap_pi_eq_evalSigma, nv_comap_pi_eq_evalSigma] at h2
  exact h2

/-- Witness at `d = 2`: the singletons at `0` and at `(1, 1)` are separated by `√2 ≥ 1`. -/
example : Indep (nv_evalSigma ({0} : Set (Vec 2))) (nv_evalSigma ({fun _ ↦ (1 : ℝ)} : Set (Vec 2)))
    (nvNoiseLaw 2) :=
  nv_indep_evalSigma _ _ (by
    rintro x y rfl rfl
    unfold Book.Ch02.vecNorm
    rw [EuclideanSpace.norm_eq]
    refine Real.one_le_sqrt.2 ?_
    simp)

end

end SuperdiffusionCLT.Assumptions.ShellLaw.Model
