/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Section8.DivergenceForm.BoundedMeasurableLimit
public import MarkovProcess.Kernel.Resolvent
public import SuperdiffusionCLT.Section8.DivergenceForm.WholeSpace.ExcessiveMinimalMaximum
public import SuperdiffusionCLT.Section8.DivergenceForm.WholeSpace.KernelIdentificationOpenApprox
public import MarkovProcess.Killed.GluingPotential

/-!
# Identification of the direct whole-space kernel resolvent

The kernel resolvent generated by the directly assembled analytic minimal
`C₀` resolvent agrees with the cubic analytic supremum on every nonnegative
bounded measurable observable.  The proof first establishes monotone
continuity of the analytic supremum from the corresponding bounded-domain
regularity statement, then uses a monotone-class argument starting from
continuous observables vanishing at infinity.
-/

@[expose] public section

namespace SuperdiffusionCLT.Section8.DivergenceForm

open Filter Homogenization MeasureTheory Set Topology
open MarkovProcess MarkovProcess.Semigroup
open scoped ENNReal ZeroAtInfty

noncomputable section

variable {d : ℕ} [NeZero d]

namespace WholeSpaceAnalyticData

variable (A : WholeSpaceAnalyticData d)

omit [NeZero d] in
theorem abs_le_norm_identification (f : C₀(Vec d, ℝ)) (y : Vec d) :
    |f y| ≤ ‖f‖ := by
  rw [← Real.norm_eq_abs, ← ZeroAtInftyContinuousMap.norm_toBCF_eq_norm]
  exact BoundedContinuousFunction.norm_coe_le_norm f.toBCF y

/-- Inputs needed by the S-free monotone-class identification: agreement on
`C₀` data and the analytic and kernel constant-one normalizations. -/
structure KernelIdentificationInput where
  R : PositiveC0ContractiveResolvent (Vec d)
  operator_eq : ∀ (mu : PositiveShift) (f : C₀(Vec d, ℝ)) (x : Vec d),
    R.toContractiveResolvent.operator mu f x =
      A.analyticMinimalResolventReal mu f f.continuous.measurable
        (abs_le_norm_identification f) x
  kernel_one : ∀ (mu : PositiveShift) (x : Vec d),
    ENNReal.ofReal (mu : ℝ) * R.kernelSemigroup.kernelResolvent
      (mu : ℝ) (fun _ ↦ 1) x = 1
  analytic_one : ∀ (mu : PositiveShift) (x : Vec d),
    ENNReal.ofReal (mu : ℝ) * A.analyticMinimalResolvent mu
      (fun _ : Vec d ↦ (1 : ℝ)) measurable_const
      (D := 1) (fun _ ↦ by norm_num) x = 1

private theorem tendsto_analyticCubeResolvent_of_bounded_tendsto
    (mu : PositiveShift) {f : ℕ → Vec d → ℝ} {g : Vec d → ℝ}
    (hf : ∀ n, Measurable (f n)) (hg : Measurable g) {D : ℝ} (hD : 0 ≤ D)
    (hfD : ∀ n x, |f n x| ≤ D) (hgD : ∀ x, |g x| ≤ D)
    (hpt : ∀ x, Tendsto (fun n ↦ f n x) atTop (nhds (g x)))
    (m : ℕ) (x : Vec d) :
    Tendsto (fun n ↦ A.analyticCubeResolvent mu (f n) (hf n) (hfD n) m x)
      atTop (nhds (A.analyticCubeResolvent mu g hg hgD m x)) := by
  by_cases hx : x ∈ wholeSpaceCube d m
  · let hU := isOpenBoundedConvexDomain_wholeSpaceCube d m
    let F : ℕ → ScalarL2 (wholeSpaceCube d m) := fun n ↦
      boundedMeasurableToScalarL2 hU ((hf n).comp measurable_subtype_coe)
        (fun y ↦ hfD n y)
    let G : ScalarL2 (wholeSpaceCube d m) :=
      boundedMeasurableToScalarL2 hU (hg.comp measurable_subtype_coe)
        (fun y ↦ hgD y)
    have hFG : ∀ᵐ y ∂volumeMeasureOn (wholeSpaceCube d m),
        ∀ n, |F n y - G y| ≤ 2 * D := by
      rw [ae_all_iff]
      intro n
      filter_upwards [boundedMeasurableToScalarL2_coeFn hU
          ((hf n).comp measurable_subtype_coe) (fun y ↦ hfD n y),
        boundedMeasurableToScalarL2_coeFn hU
          (hg.comp measurable_subtype_coe) (fun y ↦ hgD y),
        ae_restrict_mem hU.isOpen.measurableSet] with y hyf hyg hyU
      rw [hyf, hyg, domainExtension_of_mem hyU, domainExtension_of_mem hyU]
      calc
        |f n y - g y| ≤ |f n y| + |g y| := abs_sub _ _
        _ ≤ D + D := add_le_add (hfD n y) (hgD y)
        _ = 2 * D := by ring
    have hFGpt : ∀ᵐ y ∂volumeMeasureOn (wholeSpaceCube d m),
        Tendsto (fun n ↦ F n y) atTop (nhds (G y)) := by
      filter_upwards [ae_all_iff.2 fun n ↦ boundedMeasurableToScalarL2_coeFn hU
          ((hf n).comp measurable_subtype_coe) (fun y ↦ hfD n y),
        boundedMeasurableToScalarL2_coeFn hU
          (hg.comp measurable_subtype_coe) (fun y ↦ hgD y),
        ae_restrict_mem hU.isOpen.measurableSet] with y hyf hyg hyU
      have hyfn : ∀ n, F n y = f n y := by
        intro n
        rw [hyf n, domainExtension_of_mem hyU]
        rfl
      rw [hyg, domainExtension_of_mem hyU]
      simp only [hyfn]
      exact hpt y
    have hFG_each : ∀ n, ∀ᵐ y ∂volumeMeasureOn (wholeSpaceCube d m),
        |F n y - G y| ≤ 2 * D := fun n ↦ hFG.mono fun _ hy ↦ hy n
    have hL2 : Tendsto (fun n ↦ ‖F n - G‖) atTop (nhds 0) :=
      tendsto_norm_scalarL2_sub_of_bounded_ae_tendsto hU hFG hFGpt
    have hrep := tendsto_representative_of_tendsto_norm_freezing A.hd A.a hU
      A.hnu A.hsymm (A.skewContinuousOnCube m) mu.property A.hnu
      (A.cubeEllipticity m) (M := 2 * D) (mul_nonneg (by norm_num) hD)
      hFG_each hL2
      (wk := fun n ↦ continuousCoeffBoundedResolvent A.a hU A.hnu A.hnu
        (A.cubeEllipticity m) A.hsymm (A.skewContinuousOnCube m) A.hd mu
        ((hf n).comp measurable_subtype_coe) (fun y ↦ hfD n y))
      (w := continuousCoeffBoundedResolvent A.a hU A.hnu A.hnu
        (A.cubeEllipticity m) A.hsymm (A.skewContinuousOnCube m) A.hd mu
        (hg.comp measurable_subtype_coe) (fun y ↦ hgD y))
      (fun n ↦ continuousOn_continuousCoeffBoundedResolvent A.a hU A.hnu
        A.hnu (A.cubeEllipticity m) A.hsymm (A.skewContinuousOnCube m) A.hd
        mu ((hf n).comp measurable_subtype_coe) (fun y ↦ hfD n y))
      (fun n ↦ continuousCoeffBoundedResolvent_ae A.a hU A.hnu A.hnu
        (A.cubeEllipticity m) A.hsymm (A.skewContinuousOnCube m) A.hd mu
        ((hf n).comp measurable_subtype_coe) (fun y ↦ hfD n y))
      (continuousOn_continuousCoeffBoundedResolvent A.a hU A.hnu A.hnu
        (A.cubeEllipticity m) A.hsymm (A.skewContinuousOnCube m) A.hd mu
        (hg.comp measurable_subtype_coe) (fun y ↦ hgD y))
      (continuousCoeffBoundedResolvent_ae A.a hU A.hnu A.hnu
        (A.cubeEllipticity m) A.hsymm (A.skewContinuousOnCube m) A.hd mu
        (hg.comp measurable_subtype_coe) (fun y ↦ hgD y)) hx
    simpa only [analyticCubeResolvent, hx, ↓reduceDIte] using hrep
  · have hz : ∀ n, A.analyticCubeResolvent mu (f n) (hf n) (hfD n) m x = 0 :=
      fun n ↦ by rw [analyticCubeResolvent, dite_eq_right hx]
    rw [analyticCubeResolvent, dite_eq_right hx]
    simpa only [hz] using
      (tendsto_const_nhds : Tendsto (fun _ : ℕ ↦ (0 : ℝ)) atTop (nhds 0))

private theorem analyticMinimalResolvent_iSup_of_monotone
    (mu : PositiveShift) {f : ℕ → Vec d → ℝ} {g : Vec d → ℝ}
    (hf : ∀ n, Measurable (f n)) (hg : Measurable g)
    {D : ℝ} (hD : 0 ≤ D) (hfD : ∀ n x, |f n x| ≤ D)
    (hgD : ∀ x, |g x| ≤ D) (hmono : Monotone f)
    (hpt : ∀ x, Tendsto (fun n ↦ f n x) atTop (nhds (g x))) (x : Vec d) :
    A.analyticMinimalResolvent mu g hg hgD x =
      ⨆ n, A.analyticMinimalResolvent mu (f n) (hf n) (hfD n) x := by
  unfold analyticMinimalResolvent
  rw [iSup_comm]
  apply iSup_congr
  intro m
  have hmonoCube : Monotone fun n ↦
      A.analyticCubeResolventENN mu (f n) (hf n) (hfD n) m x := by
    intro n k hnk
    exact ENNReal.ofReal_le_ofReal (A.analyticCubeResolvent_mono mu
      (hf n) (hf k) (hfD n) (hfD k) (fun y ↦ hmono hnk y) m x)
  have htendsto : Tendsto (fun n ↦
      A.analyticCubeResolventENN mu (f n) (hf n) (hfD n) m x) atTop
      (nhds (A.analyticCubeResolventENN mu g hg hgD m x)) := by
    exact (ENNReal.continuous_ofReal.tendsto _).comp
      (A.tendsto_analyticCubeResolvent_of_bounded_tendsto mu hf hg hD hfD hgD
        hpt m x)
  exact (iSup_eq_of_tendsto hmonoCube htendsto).symm

omit [NeZero d] in
private theorem indicator_nonneg (T : Set (Vec d)) (y : Vec d) :
    0 ≤ T.indicator (fun _ ↦ (1 : ℝ)) y := by
  classical
  rw [Set.indicator_apply]
  split_ifs <;> norm_num

omit [NeZero d] in
private theorem abs_indicator_le_one (T : Set (Vec d)) (y : Vec d) :
    |T.indicator (fun _ ↦ (1 : ℝ)) y| ≤ 1 := by
  classical
  rw [Set.indicator_apply]
  split_ifs <;> norm_num

private def IndicatorAgreement (S : KernelIdentificationInput A)
    (mu : PositiveShift) (x : Vec d) (T : Set (Vec d))
    (hT : MeasurableSet T) : Prop :=
  S.R.kernelSemigroup.kernelResolvent
      (mu : ℝ) (T.indicator (fun _ ↦ (1 : ℝ≥0∞))) x =
    A.analyticMinimalResolvent mu (T.indicator (fun _ ↦ (1 : ℝ)))
      (measurable_const.indicator hT) (D := 1) (abs_indicator_le_one T) x

private theorem kernelResolvent_eq_analyticMinimalResolvent_of_c0
    (S : KernelIdentificationInput A) (mu : PositiveShift)
    (f : C₀(Vec d, ℝ)) (hf0 : ∀ y, 0 ≤ f y) (hf1 : ∀ y, |f y| ≤ 1)
    (x : Vec d) :
    S.R.kernelSemigroup.kernelResolvent
        (mu : ℝ) (fun y ↦ ENNReal.ofReal (f y)) x =
      A.analyticMinimalResolvent mu f f.continuous.measurable hf1 x := by
  let R := S.R
  have hrepresented := R.kernelResolvent_ofReal_eq_operator mu f hf0 x
  have hop : R.toContractiveResolvent.operator mu f x =
      A.analyticMinimalResolventReal mu f f.continuous.measurable hf1 x := by
    exact (S.operator_eq mu f x).trans
      (A.analyticMinimalResolventReal_bound_irrel mu f.continuous.measurable
        (abs_le_norm_identification f) hf1 x)
  have hreal := A.analyticMinimalResolventReal_eq_toReal mu
    f.continuous.measurable hf0 hf1 x
  have hfinite := A.analyticMinimalResolvent_ne_top mu f.continuous.measurable
    hf0 (by norm_num : (0 : ℝ) ≤ 1) hf1 x
  calc
    R.kernelSemigroup.kernelResolvent (mu : ℝ)
        (fun y ↦ ENNReal.ofReal (f y)) x =
      ENNReal.ofReal (R.toContractiveResolvent.operator mu f x) := hrepresented
    _ = ENNReal.ofReal
        (A.analyticMinimalResolventReal mu f f.continuous.measurable hf1 x) :=
      congrArg ENNReal.ofReal hop
    _ = ENNReal.ofReal
        (A.analyticMinimalResolvent mu f f.continuous.measurable hf1 x).toReal :=
      congrArg ENNReal.ofReal hreal
    _ = A.analyticMinimalResolvent mu f f.continuous.measurable hf1 x :=
      ENNReal.ofReal_toReal hfinite

private theorem indicatorAgreement_univ (S : KernelIdentificationInput A)
    (mu : PositiveShift) (x : Vec d) :
    A.IndicatorAgreement S mu x Set.univ MeasurableSet.univ := by
  unfold IndicatorAgreement
  simp only [Set.indicator_univ]
  apply (ENNReal.mul_right_inj
    (ENNReal.ofReal_pos.mpr mu.property).ne' ENNReal.ofReal_ne_top).mp
  rw [S.kernel_one mu x, S.analytic_one mu x]

private theorem indicatorAgreement_open (S : KernelIdentificationInput A)
    (mu : PositiveShift) (x : Vec d) {G : Set (Vec d)} (hG : IsOpen G) :
    A.IndicatorAgreement S mu x G hG.measurableSet := by
  by_cases hGuniv : G = Set.univ
  · subst G
    exact A.indicatorAgreement_univ S mu x
  let f : ℕ → Vec d → ℝ := fun n ↦ wholeSpaceOpenApprox G n
  let g : Vec d → ℝ := G.indicator fun _ ↦ 1
  have hf : ∀ n, Measurable (f n) := fun n ↦
    (continuous_wholeSpaceOpenApprox G n).measurable
  have hg : Measurable g := measurable_const.indicator hG.measurableSet
  have hf0 : ∀ n y, 0 ≤ f n y := fun n y ↦ wholeSpaceOpenApprox_nonneg G n y
  have hg0 : ∀ y, 0 ≤ g y := by
    intro y
    classical
    simp only [g, Set.indicator_apply]
    split_ifs <;> norm_num
  have hf1 : ∀ n y, |f n y| ≤ 1 := fun n y ↦
    abs_wholeSpaceOpenApprox_le_one G n y
  have hg1 : ∀ y, |g y| ≤ 1 := by
    intro y
    classical
    simp only [g, Set.indicator_apply]
    split_ifs <;> norm_num
  have hmono : Monotone f := fun n k hnk y ↦ monotone_wholeSpaceOpenApprox G y hnk
  have hpt : ∀ y, Tendsto (fun n ↦ f n y) atTop (nhds (g y)) := fun y ↦
    tendsto_wholeSpaceOpenApprox G hG hGuniv y
  have hkernel := S.R.kernelSemigroup.kernelResolvent_iSup
    (mu : ℝ) (fun n ↦ ENNReal.measurable_ofReal.comp (hf n))
    (fun n k hnk y ↦ ENNReal.ofReal_le_ofReal (hmono hnk y)) x
  have hanalytic := A.analyticMinimalResolvent_iSup_of_monotone mu hf hg
    (by norm_num : (0 : ℝ) ≤ 1) hf1 hg1 hmono hpt x
  have heach : ∀ n,
      S.R.kernelSemigroup.kernelResolvent
          (mu : ℝ) (fun y ↦ ENNReal.ofReal (f n y)) x =
        A.analyticMinimalResolvent mu (f n) (hf n) (hf1 n) x := by
    intro n
    exact A.kernelResolvent_eq_analyticMinimalResolvent_of_c0 S mu
      (wholeSpaceOpenApproxC0 G n) (hf0 n) (hf1 n) x
  unfold IndicatorAgreement
  calc
    S.R.kernelSemigroup.kernelResolvent
        (mu : ℝ) (G.indicator (fun _ ↦ (1 : ℝ≥0∞))) x =
      S.R.kernelSemigroup.kernelResolvent
        (mu : ℝ) (fun y ↦ ENNReal.ofReal (g y)) x := by
      congr 2
      funext y
      classical
      simp only [g, Set.indicator_apply]
      split_ifs <;> norm_num
    _ = S.R.kernelSemigroup.kernelResolvent
        (mu : ℝ) (fun y ↦ ⨆ n, ENNReal.ofReal (f n y)) x := by
      congr 2
      funext y
      rw [iSup_wholeSpaceOpenApprox G hG hGuniv]
      classical
      dsimp only [g]
      by_cases hy : y ∈ G <;> simp [hy]
    _ = ⨆ n, S.R.kernelSemigroup.kernelResolvent
        (mu : ℝ) (fun y ↦ ENNReal.ofReal (f n y)) x := hkernel
    _ = ⨆ n, A.analyticMinimalResolvent mu (f n) (hf n) (hf1 n) x :=
      iSup_congr heach
    _ = A.analyticMinimalResolvent mu g hg hg1 x := hanalytic.symm
    _ = A.analyticMinimalResolvent mu (G.indicator (fun _ ↦ (1 : ℝ)))
        (measurable_const.indicator hG.measurableSet) (abs_indicator_le_one G) x := by
      rfl

private theorem indicatorAgreement_empty (S : KernelIdentificationInput A)
    (mu : PositiveShift) (x : Vec d) :
    A.IndicatorAgreement S mu x ∅ MeasurableSet.empty := by
  unfold IndicatorAgreement
  simp only [Set.indicator_empty]
  have hzero := A.kernelResolvent_eq_analyticMinimalResolvent_of_c0 S mu
    (0 : C₀(Vec d, ℝ)) (fun _ ↦ le_rfl) (fun _ ↦ by norm_num) x
  convert hzero using 1
  all_goals first
    | rfl
    | simp only [ZeroAtInftyContinuousMap.coe_zero, Pi.zero_apply, ENNReal.ofReal_zero]

private theorem indicatorAgreement_union (S : KernelIdentificationInput A)
    (mu : PositiveShift) (x : Vec d) {E F : Set (Vec d)}
    (hE : MeasurableSet E) (hF : MeasurableSet F) (hdisj : Disjoint E F)
    (hAE : A.IndicatorAgreement S mu x E hE)
    (hAF : A.IndicatorAgreement S mu x F hF) :
    A.IndicatorAgreement S mu x (E ∪ F) (hE.union hF) := by
  let R := S.R
  have hreal : (E ∪ F).indicator (fun _ ↦ (1 : ℝ)) =
      fun y ↦ E.indicator (fun _ ↦ (1 : ℝ)) y +
        F.indicator (fun _ ↦ (1 : ℝ)) y := by
    funext y
    classical
    by_cases he : y ∈ E
    · have hf : y ∉ F := Set.disjoint_left.1 hdisj he
      simp [he, hf]
    · by_cases hf : y ∈ F <;> simp [he, hf]
  have henn : (E ∪ F).indicator (fun _ ↦ (1 : ℝ≥0∞)) =
      fun y ↦ E.indicator (fun _ ↦ (1 : ℝ≥0∞)) y +
        F.indicator (fun _ ↦ (1 : ℝ≥0∞)) y := by
    funext y
    classical
    by_cases he : y ∈ E
    · have hf : y ∉ F := Set.disjoint_left.1 hdisj he
      simp [he, hf]
    · by_cases hf : y ∈ F <;> simp [he, hf]
  unfold IndicatorAgreement at hAE hAF ⊢
  rw [henn, R.kernelSemigroup.kernelResolvent_add (mu : ℝ)
    (measurable_const.indicator hE) x, hAE, hAF]
  have hadd := (A.analyticMinimalResolvent_add mu
    (measurable_const.indicator hE) (measurable_const.indicator hF)
    (indicator_nonneg E) (indicator_nonneg F)
    (abs_indicator_le_one E) (abs_indicator_le_one F)
    (fun y ↦ (abs_add_le _ _).trans <|
      add_le_add (abs_indicator_le_one E y) (abs_indicator_le_one F y)) x).symm
  exact hadd.trans <| A.analyticMinimalResolvent_congr_ae mu
    ((measurable_const.indicator hE).add (measurable_const.indicator hF))
    (measurable_const.indicator (hE.union hF))
    (fun y ↦ (abs_add_le _ _).trans <|
      add_le_add (abs_indicator_le_one E y) (abs_indicator_le_one F y))
    (abs_indicator_le_one (E ∪ F))
    (Eventually.of_forall fun y ↦ (congrFun hreal y).symm) x

private theorem indicatorAgreement_measurable (S : KernelIdentificationInput A)
    (mu : PositiveShift) (x : Vec d) {T : Set (Vec d)} (hT : MeasurableSet T) :
    A.IndicatorAgreement S mu x T hT := by
  let R := S.R
  refine MeasurableSpace.induction_on_inter
    (C := fun E hE ↦ A.IndicatorAgreement S mu x E hE)
    (s := {E : Set (Vec d) | IsOpen E}) BorelSpace.measurable_eq
    isPiSystem_isOpen (A.indicatorAgreement_empty S mu x)
    (fun _ hG ↦ A.indicatorAgreement_open S mu x hG) ?_ ?_ T hT
  · intro E hEm ih
    have hEc : MeasurableSet Eᶜ := hEm.compl
    unfold IndicatorAgreement at ih ⊢
    have hsum' :
        R.kernelSemigroup.kernelResolvent (mu : ℝ)
            (E.indicator (fun _ ↦ (1 : ℝ≥0∞))) x +
          R.kernelSemigroup.kernelResolvent (mu : ℝ)
            (Eᶜ.indicator (fun _ ↦ (1 : ℝ≥0∞))) x =
        A.analyticMinimalResolvent mu (E.indicator (fun _ ↦ (1 : ℝ)))
            (measurable_const.indicator hEm) (abs_indicator_le_one E) x +
          A.analyticMinimalResolvent mu (Eᶜ.indicator (fun _ ↦ (1 : ℝ)))
            (measurable_const.indicator hEc) (abs_indicator_le_one Eᶜ) x := by
      rw [← R.kernelSemigroup.kernelResolvent_add (mu : ℝ)
        (measurable_const.indicator hEm) x,
        ← A.analyticMinimalResolvent_add mu
          (measurable_const.indicator hEm) (measurable_const.indicator hEc)
          (indicator_nonneg E) (indicator_nonneg Eᶜ)
          (abs_indicator_le_one E) (abs_indicator_le_one Eᶜ)
          (fun y ↦ (abs_add_le _ _).trans <|
            add_le_add (abs_indicator_le_one E y) (abs_indicator_le_one Eᶜ y)) x]
      have huniv := A.indicatorAgreement_univ S mu x
      unfold IndicatorAgreement at huniv
      have hreal : (fun y ↦ E.indicator (fun _ ↦ (1 : ℝ)) y +
          Eᶜ.indicator (fun _ ↦ (1 : ℝ)) y) =
          Set.univ.indicator (fun _ ↦ (1 : ℝ)) := by
        funext y
        classical
        by_cases hy : y ∈ E <;> simp [hy]
      have henn : (fun y ↦ E.indicator (fun _ ↦ (1 : ℝ≥0∞)) y +
          Eᶜ.indicator (fun _ ↦ (1 : ℝ≥0∞)) y) =
          Set.univ.indicator (fun _ ↦ (1 : ℝ≥0∞)) := by
        funext y
        classical
        by_cases hy : y ∈ E <;> simp [hy]
      calc
        R.kernelSemigroup.kernelResolvent (mu : ℝ)
            (fun y ↦ E.indicator (fun _ ↦ (1 : ℝ≥0∞)) y +
              Eᶜ.indicator (fun _ ↦ (1 : ℝ≥0∞)) y) x =
          R.kernelSemigroup.kernelResolvent (mu : ℝ)
            (Set.univ.indicator (fun _ ↦ (1 : ℝ≥0∞))) x := by rw [henn]
        _ = A.analyticMinimalResolvent mu
            (Set.univ.indicator (fun _ ↦ (1 : ℝ)))
            (measurable_const.indicator MeasurableSet.univ)
            (abs_indicator_le_one Set.univ) x := huniv
        _ = A.analyticMinimalResolvent mu
            (fun y ↦ E.indicator (fun _ ↦ (1 : ℝ)) y +
              Eᶜ.indicator (fun _ ↦ (1 : ℝ)) y)
            ((measurable_const.indicator hEm).add
              (measurable_const.indicator hEc))
            (fun y ↦ (abs_add_le _ _).trans <|
              add_le_add (abs_indicator_le_one E y)
                (abs_indicator_le_one Eᶜ y)) x :=
          A.analyticMinimalResolvent_congr_ae mu
            (measurable_const.indicator MeasurableSet.univ)
            ((measurable_const.indicator hEm).add
              (measurable_const.indicator hEc))
            (abs_indicator_le_one Set.univ)
            (fun y ↦ (abs_add_le _ _).trans <|
              add_le_add (abs_indicator_le_one E y)
                (abs_indicator_le_one Eᶜ y))
            (Eventually.of_forall fun y ↦ (congrFun hreal y).symm) x
    rw [ih] at hsum'
    exact (ENNReal.add_right_inj (A.analyticMinimalResolvent_ne_top mu
      (measurable_const.indicator hEm) (indicator_nonneg E)
      (by norm_num : (0 : ℝ) ≤ 1) (abs_indicator_le_one E) x)).mp hsum'
  · intro F hdisj hFm ih
    set G : ℕ → Set (Vec d) := fun n ↦ ⋃ i, ⋃ (_ : i < n), F i with hGdef
    have hGmeas : ∀ n, MeasurableSet (G n) := fun n ↦
      MeasurableSet.iUnion fun i ↦ MeasurableSet.iUnion fun _ ↦ hFm i
    have hGmem : ∀ (n : ℕ) (y : Vec d), y ∈ G n ↔ ∃ i < n, y ∈ F i := by
      intro n y
      simp [hGdef]
    have hpartial : ∀ n, A.IndicatorAgreement S mu x (G n) (hGmeas n) := by
      intro n
      induction n with
      | zero =>
          have hG0 : G 0 = ∅ := by ext y; simp [hGmem]
          simpa only [hG0] using A.indicatorAgreement_empty S mu x
      | succ n ihn =>
          have hd : Disjoint (G n) (F n) := Set.disjoint_left.2 fun y hyG hyF ↦ by
            obtain ⟨i, hi, hiy⟩ := (hGmem n y).1 hyG
            exact Set.disjoint_left.1 (hdisj hi.ne) hiy hyF
          have hs := A.indicatorAgreement_union S mu x (hGmeas n) (hFm n) hd ihn (ih n)
          have hstep : G n ∪ F n = G (n + 1) := by
            ext y
            simp only [Set.mem_union, hGmem]
            constructor
            · rintro (⟨i, hi, hiy⟩ | hy)
              · exact ⟨i, Nat.lt_succ_of_lt hi, hiy⟩
              · exact ⟨n, Nat.lt_succ_self n, hy⟩
            · rintro ⟨i, hi, hiy⟩
              rcases Nat.lt_succ_iff_lt_or_eq.1 hi with hi | rfl
              · exact Or.inl ⟨i, hi, hiy⟩
              · exact Or.inr hiy
          simpa only [hstep] using hs
    let f : ℕ → Vec d → ℝ := fun n ↦ (G n).indicator fun _ ↦ 1
    let g : Vec d → ℝ := (⋃ i, F i).indicator fun _ ↦ 1
    have hf : ∀ n, Measurable (f n) := fun n ↦
      measurable_const.indicator (hGmeas n)
    have hg : Measurable g := measurable_const.indicator (MeasurableSet.iUnion hFm)
    have hmono : Monotone f := by
      intro n k hnk y
      dsimp only [f]
      classical
      by_cases hy : y ∈ G n
      · rw [Set.indicator_of_mem hy, Set.indicator_of_mem]
        exact (hGmem k y).2 <| by
          obtain ⟨i, hi, hiy⟩ := (hGmem n y).1 hy
          exact ⟨i, lt_of_lt_of_le hi hnk, hiy⟩
      · rw [Set.indicator_of_notMem hy]
        exact indicator_nonneg (G k) y
    have hpt : ∀ y, Tendsto (fun n ↦ f n y) atTop (nhds (g y)) := by
      intro y
      by_cases hy : y ∈ ⋃ i, F i
      · obtain ⟨i, hi⟩ := Set.mem_iUnion.1 hy
        rw [show g y = 1 by simp [g, hy]]
        refine tendsto_atTop_of_eventually_const (i₀ := i + 1) ?_
        intro n hn
        exact Set.indicator_of_mem ((hGmem n y).2
          ⟨i, lt_of_lt_of_le (Nat.lt_succ_self i) hn, hi⟩) _
      · rw [show g y = 0 by simp [g, hy]]
        have hz : ∀ n, f n y = 0 := fun n ↦ Set.indicator_of_notMem
          (fun hmem ↦ hy <| by
            obtain ⟨i, -, hi⟩ := (hGmem n y).1 hmem
            exact Set.mem_iUnion.2 ⟨i, hi⟩) _
        simpa only [hz] using
          (tendsto_const_nhds : Tendsto (fun _ : ℕ ↦ (0 : ℝ)) atTop (nhds 0))
    have heach : ∀ n,
        R.kernelSemigroup.kernelResolvent (mu : ℝ)
            (fun y ↦ ENNReal.ofReal (f n y)) x =
          A.analyticMinimalResolvent mu (f n) (hf n)
            (fun y ↦ abs_indicator_le_one (G n) y) x := by
      intro n
      have hn := hpartial n
      unfold IndicatorAgreement at hn
      calc
        R.kernelSemigroup.kernelResolvent (mu : ℝ)
            (fun y ↦ ENNReal.ofReal (f n y)) x =
          R.kernelSemigroup.kernelResolvent (mu : ℝ)
            ((G n).indicator (fun _ ↦ (1 : ℝ≥0∞))) x := by
              congr 2
              funext y
              classical
              by_cases hy : y ∈ G n <;> simp [f, hy]
        _ = A.analyticMinimalResolvent mu ((G n).indicator (fun _ ↦ (1 : ℝ)))
            (measurable_const.indicator (hGmeas n))
            (abs_indicator_le_one (G n)) x := hn
        _ = A.analyticMinimalResolvent mu (f n) (hf n)
            (fun y ↦ abs_indicator_le_one (G n) y) x := by rfl
    have hkernel := R.kernelSemigroup.kernelResolvent_iSup (mu : ℝ)
      (fun n ↦ ENNReal.measurable_ofReal.comp (hf n))
      (fun n k hnk y ↦ ENNReal.ofReal_le_ofReal (hmono hnk y)) x
    unfold IndicatorAgreement
    calc
      R.kernelSemigroup.kernelResolvent (mu : ℝ)
          ((⋃ i, F i).indicator (fun _ ↦ (1 : ℝ≥0∞))) x =
        R.kernelSemigroup.kernelResolvent (mu : ℝ)
          (fun y ↦ ⨆ n, ENNReal.ofReal (f n y)) x := by
            congr 2
            funext y
            by_cases hy : y ∈ ⋃ i, F i
            · obtain ⟨i, hi⟩ := Set.mem_iUnion.1 hy
              have hfi : f (i + 1) y = 1 := Set.indicator_of_mem
                ((hGmem (i + 1) y).2 ⟨i, Nat.lt_succ_self i, hi⟩) _
              rw [Set.indicator_of_mem hy]
              apply le_antisymm
              · exact le_iSup_of_le (i + 1) (by rw [hfi]; norm_num)
              · refine iSup_le fun n ↦ ?_
                dsimp only [f]
                by_cases hn : y ∈ G n <;> simp [hn]
            · rw [Set.indicator_of_notMem hy]
              apply le_antisymm bot_le
              refine iSup_le fun n ↦ ?_
              have hn : y ∉ G n := fun hyn ↦ hy <| by
                obtain ⟨i, -, hi⟩ := (hGmem n y).1 hyn
                exact Set.mem_iUnion.2 ⟨i, hi⟩
              simp [f, hn]
      _ = ⨆ n, R.kernelSemigroup.kernelResolvent (mu : ℝ)
          (fun y ↦ ENNReal.ofReal (f n y)) x := by
            exact hkernel
      _ = ⨆ n, A.analyticMinimalResolvent mu (f n) (hf n)
          (fun y ↦ abs_indicator_le_one (G n) y) x := iSup_congr heach
      _ = A.analyticMinimalResolvent mu g hg (abs_indicator_le_one _) x :=
        (A.analyticMinimalResolvent_iSup_of_monotone mu hf hg
          (by norm_num : (0 : ℝ) ≤ 1) (fun n ↦ abs_indicator_le_one (G n))
          (abs_indicator_le_one _) hmono hpt x).symm
      _ = A.analyticMinimalResolvent mu ((⋃ i, F i).indicator (fun _ ↦ (1 : ℝ)))
          (measurable_const.indicator (MeasurableSet.iUnion hFm))
          (abs_indicator_le_one _) x := by rfl

private theorem analyticMinimalResolvent_smul_nonneg
    (mu : PositiveShift) {c : ℝ} (hc : 0 ≤ c) {f : Vec d → ℝ}
    (hf : Measurable f) (hf0 : ∀ y, 0 ≤ f y) {D : ℝ} (hD : 0 ≤ D)
    (hfD : ∀ y, |f y| ≤ D) (x : Vec d) :
    A.analyticMinimalResolvent mu (c • f) (hf.const_smul c)
        (fun y ↦ by
          change |c * f y| ≤ c * D
          rw [abs_mul, abs_of_nonneg hc]
          exact mul_le_mul_of_nonneg_left (hfD y) hc) x =
      ENNReal.ofReal c * A.analyticMinimalResolvent mu f hf hfD x := by
  let hcf : ∀ y, |c * f y| ≤ c * D := fun y ↦ by
    rw [abs_mul, abs_of_nonneg hc]
    exact mul_le_mul_of_nonneg_left (hfD y) hc
  have hleft := A.analyticMinimalResolvent_ne_top mu (hf.const_smul c)
    (fun y ↦ mul_nonneg hc (hf0 y)) (mul_nonneg hc hD)
    hcf x
  have hright : ENNReal.ofReal c * A.analyticMinimalResolvent mu f hf hfD x ≠ ⊤ :=
    ENNReal.mul_ne_top ENNReal.ofReal_ne_top
    (A.analyticMinimalResolvent_ne_top mu hf hf0 hD hfD x)
  apply (ENNReal.toReal_eq_toReal_iff' hleft hright).mp
  have h := A.toReal_analyticMinimalResolvent_smul mu hc hf hf0 hD hfD x
  rw [ENNReal.toReal_mul, ENNReal.toReal_ofReal hc]
  exact h

omit [NeZero d] in
private theorem ennreal_toReal_le_one {q : ℝ≥0∞} (hq : q ≤ 1) : q.toReal ≤ 1 := by
  simpa only [ENNReal.toReal_one] using ENNReal.toReal_mono ENNReal.one_ne_top hq

/-- The generated kernel resolvent agrees with the analytic cubic minimal
resolvent on every nonnegative measurable observable bounded by one whenever
the `C₀` identification and both constant-one normalizations are available. -/
theorem kernelResolventIdentifiesAnalyticMinimal_of_input
    (S : KernelIdentificationInput A) :
    A.KernelResolventIdentifiesAnalyticMinimal
      S.R := by
  intro mu f hf hf0 hf1 x
  let R := S.R
  let h : Vec d → ℝ≥0∞ := fun y ↦ ENNReal.ofReal (f y)
  have hh : Measurable h := ENNReal.measurable_ofReal.comp hf
  have hle : ∀ y, h y ≤ 1 := by
    intro y
    exact ENNReal.ofReal_le_one.mpr <| by
      have hy := hf1 y
      rwa [abs_of_nonneg (hf0 y)] at hy
  have hind : ∀ {q : Vec d → ℝ≥0∞}, (hq : Measurable q) →
      (hbound : ∀ y, q y ≤ 1) →
      R.kernelSemigroup.kernelResolvent (mu : ℝ) q x =
        A.analyticMinimalResolvent mu (fun y ↦ (q y).toReal)
          hq.ennreal_toReal (fun y ↦ by
            rw [abs_of_nonneg ENNReal.toReal_nonneg]
            exact ennreal_toReal_le_one (hbound y)) x := by
    intro q hq
    refine Measurable.ennreal_induction
      (motive := fun q ↦ ∀ (hq : Measurable q) (hbound : ∀ y, q y ≤ 1),
        R.kernelSemigroup.kernelResolvent (mu : ℝ) q x =
          A.analyticMinimalResolvent mu (fun y ↦ (q y).toReal)
            hq.ennreal_toReal (fun y ↦ by
              rw [abs_of_nonneg ENNReal.toReal_nonneg]
              exact ennreal_toReal_le_one (hbound y)) x) ?_ ?_ ?_ hq hq
    · intro c E hE _hq hbound
      by_cases hEn : E.Nonempty
      · obtain ⟨y₀, hy₀⟩ := hEn
        have hc1 : c ≤ 1 := by
          simpa only [Set.indicator_of_mem hy₀] using hbound y₀
        have hctop : c ≠ ⊤ := ne_top_of_le_ne_top ENNReal.one_ne_top hc1
        have hc0 : 0 ≤ c.toReal := ENNReal.toReal_nonneg
        have hfun : E.indicator (fun _ ↦ c) =
            fun y ↦ ENNReal.ofReal c.toReal *
              E.indicator (fun _ ↦ (1 : ℝ≥0∞)) y := by
          funext y
          classical
          by_cases hy : y ∈ E <;> simp [hy, ENNReal.ofReal_toReal hctop]
        have hindicator := A.indicatorAgreement_measurable S mu x hE
        unfold IndicatorAgreement at hindicator
        calc
          R.kernelSemigroup.kernelResolvent (mu : ℝ)
              (E.indicator fun _ ↦ c) x =
            R.kernelSemigroup.kernelResolvent (mu : ℝ)
              (fun y ↦ ENNReal.ofReal c.toReal *
                E.indicator (fun _ ↦ (1 : ℝ≥0∞)) y) x :=
            congrArg (fun z ↦ R.kernelSemigroup.kernelResolvent (mu : ℝ) z x) hfun
          _ = ENNReal.ofReal c.toReal *
              R.kernelSemigroup.kernelResolvent (mu : ℝ)
                (E.indicator (fun _ ↦ (1 : ℝ≥0∞))) x :=
            R.kernelSemigroup.kernelResolvent_const_mul (mu : ℝ)
              (ENNReal.ofReal c.toReal) (measurable_const.indicator hE) x
          _ = ENNReal.ofReal c.toReal *
              A.analyticMinimalResolvent mu (E.indicator (fun _ ↦ (1 : ℝ)))
                (measurable_const.indicator hE) (abs_indicator_le_one E) x := by
            rw [hindicator]
          _ = A.analyticMinimalResolvent mu
              (c.toReal • E.indicator (fun _ ↦ (1 : ℝ)))
              ((measurable_const.indicator hE).const_smul c.toReal)
              (fun y ↦ by
                change |c.toReal * E.indicator (fun _ ↦ (1 : ℝ)) y| ≤ c.toReal * 1
                rw [abs_mul, abs_of_nonneg hc0]
                exact mul_le_mul_of_nonneg_left (abs_indicator_le_one E y) hc0) x :=
            (A.analyticMinimalResolvent_smul_nonneg mu hc0
              (measurable_const.indicator hE) (indicator_nonneg E)
              (by norm_num : (0 : ℝ) ≤ 1) (abs_indicator_le_one E) x).symm
          _ = A.analyticMinimalResolvent mu
              (fun y ↦ (E.indicator (fun _ ↦ c) y).toReal)
              _hq.ennreal_toReal
              (fun y ↦ by
                rw [abs_of_nonneg ENNReal.toReal_nonneg]
                exact ennreal_toReal_le_one (hbound y)) x :=
            A.analyticMinimalResolvent_congr_ae mu
              ((measurable_const.indicator hE).const_smul c.toReal)
              _hq.ennreal_toReal
              (fun y ↦ by
                change |c.toReal * E.indicator (fun _ ↦ (1 : ℝ)) y| ≤ c.toReal * 1
                rw [abs_mul, abs_of_nonneg hc0]
                exact mul_le_mul_of_nonneg_left (abs_indicator_le_one E y) hc0)
              (fun y ↦ by
                rw [abs_of_nonneg ENNReal.toReal_nonneg]
                exact ennreal_toReal_le_one (hbound y))
              (Eventually.of_forall fun y ↦ by
                classical
                by_cases hy : y ∈ E <;> simp [hy]) x
      · have hE0 : E = ∅ := Set.not_nonempty_iff_eq_empty.mp hEn
        subst E
        have hempty := A.indicatorAgreement_empty S mu x
        unfold IndicatorAgreement at hempty
        simpa only [Set.indicator_empty, ENNReal.toReal_zero] using hempty
    · intro q r _hdisj hqm hrm ihq ihr _hqr hbound
      have hq1 : ∀ y, q y ≤ 1 := fun y ↦
        (show q y ≤ q y + r y from le_add_right le_rfl).trans (hbound y)
      have hr1 : ∀ y, r y ≤ 1 := fun y ↦
        (show r y ≤ q y + r y from le_add_left le_rfl).trans (hbound y)
      have hqtop : ∀ y, q y ≠ ⊤ := fun y ↦
        ne_top_of_le_ne_top ENNReal.one_ne_top (hq1 y)
      have hrtop : ∀ y, r y ≠ ⊤ := fun y ↦
        ne_top_of_le_ne_top ENNReal.one_ne_top (hr1 y)
      change R.kernelSemigroup.kernelResolvent (mu : ℝ)
        (fun y ↦ q y + r y) x = _
      rw [R.kernelSemigroup.kernelResolvent_add (mu : ℝ) hqm x,
        ihq hqm hq1, ihr hrm hr1]
      rw [← A.analyticMinimalResolvent_add mu hqm.ennreal_toReal
        hrm.ennreal_toReal (fun _ ↦ ENNReal.toReal_nonneg)
        (fun _ ↦ ENNReal.toReal_nonneg)
        (fun y ↦ by rw [abs_of_nonneg ENNReal.toReal_nonneg]; exact
          ennreal_toReal_le_one (hq1 y))
        (fun y ↦ by rw [abs_of_nonneg ENNReal.toReal_nonneg]; exact
          ennreal_toReal_le_one (hr1 y))
        (fun y ↦ by
          rw [abs_of_nonneg (add_nonneg ENNReal.toReal_nonneg ENNReal.toReal_nonneg)]
          exact add_le_add
            (ennreal_toReal_le_one (hq1 y))
            (ennreal_toReal_le_one (hr1 y))) x]
      apply A.analyticMinimalResolvent_congr_ae mu
        (hqm.ennreal_toReal.add hrm.ennreal_toReal)
        (hqm.add hrm).ennreal_toReal
        (fun y ↦ by
          rw [Pi.add_apply, abs_of_nonneg (add_nonneg ENNReal.toReal_nonneg ENNReal.toReal_nonneg)]
          exact add_le_add
            (ennreal_toReal_le_one (hq1 y))
            (ennreal_toReal_le_one (hr1 y)))
        (fun y ↦ by
          rw [abs_of_nonneg ENNReal.toReal_nonneg]
          exact ennreal_toReal_le_one (hbound y))
        (Eventually.of_forall fun y ↦
          (ENNReal.toReal_add (hqtop y) (hrtop y)).symm) x
    · intro q hqm hmono ihq _hqSup hbound
      have hqn1 : ∀ n y, q n y ≤ 1 := fun n y ↦
        (le_iSup (fun k ↦ q k y) n).trans (hbound y)
      have hrealMono : Monotone fun n y ↦ (q n y).toReal := fun n k hnk y ↦
        ENNReal.toReal_mono (ne_top_of_le_ne_top ENNReal.one_ne_top (hqn1 k y)) (hmono hnk y)
      have hpt : ∀ y, Tendsto (fun n ↦ (q n y).toReal) atTop
          (nhds ((⨆ n, q n y).toReal)) := fun y ↦
        (ENNReal.tendsto_toReal
          (ne_top_of_le_ne_top ENNReal.one_ne_top (hbound y))).comp
            (tendsto_atTop_iSup (fun _ _ hnk ↦ hmono hnk y))
      rw [R.kernelSemigroup.kernelResolvent_iSup (mu : ℝ) hqm hmono x,
        iSup_congr fun n ↦ ihq n (hqm n) (hqn1 n)]
      exact (A.analyticMinimalResolvent_iSup_of_monotone mu
        (fun n ↦ (hqm n).ennreal_toReal) _hqSup.ennreal_toReal
        (by norm_num : (0 : ℝ) ≤ 1)
        (fun n y ↦ by rw [abs_of_nonneg ENNReal.toReal_nonneg]; exact
          ennreal_toReal_le_one (hqn1 n y))
        (fun y ↦ by rw [abs_of_nonneg ENNReal.toReal_nonneg]; exact
          ennreal_toReal_le_one (hbound y)) hrealMono hpt x).symm
  have hmain := hind hh hle
  change R.kernelSemigroup.kernelResolvent (mu : ℝ) h x = _
  rw [hmain]
  apply A.analyticMinimalResolvent_congr_ae mu hh.ennreal_toReal hf
    (fun y ↦ by rw [abs_of_nonneg ENNReal.toReal_nonneg]; exact
      ennreal_toReal_le_one (hle y)) hf1
  exact Eventually.of_forall fun y ↦ ENNReal.toReal_ofReal (hf0 y)

end WholeSpaceAnalyticData

end

end SuperdiffusionCLT.Section8.DivergenceForm
