/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Frozen.Assumptions.ShellLawJ2
public import SuperdiffusionCLT.Probability.IndexSigma

/-!
# Consequences of marginal shell-law assumption J2

This file derives the paper's arbitrary-disjoint-subcollection
formulation of J2 from the canonical mutual-independence encoding in
`ShellLawJ2`.
-/

@[expose] public section

namespace SuperdiffusionCLT.Frozen.Assumptions

open MeasureTheory ProbabilityTheory

/-- Under J2, the sigma-fields generated by two disjoint subcollections of
shell coordinates are independent. -/
theorem ShellLawJ2.indep_subcollections {d : ℕ}
    {P : ProbabilityMeasure (ℕ → ShellField d)}
    (hJ2 : ShellLawJ2 d P) (A B : Set ℕ) (hAB : Disjoint A B) :
    Indep
      (SuperdiffusionCLT.Probability.indexSigma
        (fun F : ℕ → ShellField d ↦ F) A)
      (SuperdiffusionCLT.Probability.indexSigma
        (fun F : ℕ → ShellField d ↦ F) B)
      P.toMeasure := by
  exact SuperdiffusionCLT.Probability.indep_indexSigma_of_disjoint
    (fun F : ℕ → ShellField d ↦ F) P.toMeasure
    (fun n ↦ ShellField.measurable_shellCoordinate n)
    hJ2.independent hAB

end SuperdiffusionCLT.Frozen.Assumptions
