/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Probability.ConditionalGammaTail
public import SuperdiffusionCLT.Section2.Cutoff.Finite
public import SuperdiffusionCLT.Frozen.Assumptions.ShellLawJ2
public import Homogenization.Book.Ch04.Theorems.Concentration
public import Mathlib.Probability.ConditionalExpectation

/-!
# Conditioning on a sub-family of shell coordinates

`P.toMeasure` is *not* a product measure: it is an arbitrary probability measure on
`ShellSeq d = ℕ → ShellField d` whose coordinate projections are independent
(`ShellLawJ2`). Independence of the coordinates is nevertheless exactly what the
conditional concentration step of the printed argument needs, because the
conditioning σ-algebra `F_> = σ(j_r : r > ℓ)` is generated by a *sub-family* of the
coordinates and the summands are functionals of the complementary coordinates. For
those, conditioning needs no disintegration: the conditional expectation given the
upper coordinates of a function of the lower coordinates is its constant integral,
which is `MeasureTheory.condExp_indep_eq` fed by the independence of the two
σ-algebras (`ProbabilityTheory.indep_iSup_of_disjoint`) and the coordinate
projections' measurability.

## Main results

* `shellSigma S`: the σ-algebra generated by the shell coordinates in `S`.
* `indep_shellSigma_of_disjoint`: disjoint coordinate families generate independent
  σ-algebras under `ShellLawJ2`.
* `condExp_shellSigma_eq_integral_of_measurable`: **the partial-integral step.** For a
  function of the complement coordinates, `μ[f | shellSigma S]` is a.e. the constant
  `∫ f ∂μ`.
* **The conditional centring is derived.** `∫ X ∂μ = 0` together with complement measurability gives
  `μ[X | shellSigma S] =ᵐ 0`; the conditional centring is therefore *not* an extra
  hypothesis in this setting.
* `CondIsBigOWith.of_isBigOWith_of_compl`: an unconditional `IsBigOWith` bound
  for a complement-coordinate variable transfers to a conditional `Γ` bound at the
  same constant amplitude.
* `condIsBigO_gammaSigma_finsetAverage_of_compl`: **the conditional concentration
  step.** Summands that are functionals of the complementary coordinates, are
  unconditionally independent, and carry unconditional `Γ_σ` bounds and vanishing
  means satisfy the conditional `Γ_σ` bound for the normalized average, at the
  constant of the unconditional independent-sum theorem.

The hypotheses retained throughout are the standing one (`ShellLawJ2`), the
disjointness of the two coordinate families, the complement measurability of the
summands, and the summands' unconditional `Γ_σ` bounds and vanishing means — the
printed argument's own input. No `StandardBorelSpace` instance, no conditional
kernel, and no conditional centring hypothesis is used. Conditional independence of
the summands given the upper coordinates is not assumed either: `ShellLawJ2` plus
complement measurability gives it, because the conditioning σ-algebra and the
summands' σ-algebra are independent sub-σ-algebras of the ambient one.

## What is not covered

The one place where the transfer is not free is the amplitude. Every statement here
bounds the conditional tail at an envelope `θ` that dominates the *constant* of the
unconditional theorem pointwise. That is the correct direction — a larger
threshold makes the tail event smaller — and it covers the printed random
upper-coordinate envelope. It does **not** cover a threshold that falls strictly
below that constant on a set of positive measure, notably the effective amplitude
`Wbar ω · A · t` of a quotient whose weight `Wbar` is a non-degenerate random
variable: conditioning on the upper coordinates does not make such a weight
constant, and the conditional law of a complement-coordinate quantity at a threshold
that depends on the conditioning variable is not accessible from the unconditional
theorem. Any further reduction there needs the tail event itself to be
complement-measurable, which is where this route stops.
-/

@[expose] public section

namespace SuperdiffusionCLT.Probability

open MeasureTheory

open SuperdiffusionCLT.Section2.Cutoff

variable {d : ℕ}

/-! ## The σ-algebra of a coordinate family -/

/-- The σ-algebra generated by the shell coordinates in `S`. This is the concrete
form of the printed conditioning σ-algebra: for `S = {r : r > ℓ}` it is
`F_> = σ(j_r : r > ℓ)`. -/
@[instance_reducible]
noncomputable def shellSigma (S : Set ℕ) : MeasurableSpace (ShellSeq d) :=
  ⨆ n ∈ S,
    MeasurableSpace.comap (fun F : ShellSeq d => F n)
      (inferInstance : MeasurableSpace (SuperdiffusionCLT.Frozen.Assumptions.ShellField d))

/-- Every coordinate σ-algebra is a sub-σ-algebra of the ambient one. -/
theorem shellSigma_le_ambient (S : Set ℕ) :
    shellSigma (d := d) S ≤ (inferInstance : MeasurableSpace (ShellSeq d)) :=
  iSup_le fun n => iSup_le fun _ => (measurable_pi_apply n).comap_le

/-- A larger coordinate family generates a larger σ-algebra. -/
theorem shellSigma_mono {S T : Set ℕ} (h : S ⊆ T) :
    shellSigma (d := d) S ≤ shellSigma (d := d) T :=
  iSup_le fun n => iSup_le fun hn => le_iSup₂_of_le n (h hn) le_rfl

/-! ## Independence of disjoint coordinate families -/

/-- **The product structure.** Under `ShellLawJ2` the σ-algebras generated by two
disjoint families of shell coordinates are independent. This is the only structural
fact about the carrier that the conditional concentration step consumes. -/
theorem indep_shellSigma_of_disjoint {μ : Measure (ShellSeq d)} {S T : Set ℕ}
    (hST : Disjoint S T)
    (hJ2 : ProbabilityTheory.iIndepFun (fun n : ℕ => fun F : ShellSeq d => F n) μ) :
    ProbabilityTheory.Indep (shellSigma (d := d) S) (shellSigma (d := d) T) μ :=
  ProbabilityTheory.indep_iSup_of_disjoint (fun n => (measurable_pi_apply n).comap_le)
    (hJ2.iIndep (m := fun _ => inferInstance)) hST

/-- The form of `indep_shellSigma_of_disjoint` at the carrier's own standing law:
`ShellLawJ2` alone gives the independence of disjoint coordinate families under
`P.toMeasure`. -/
theorem indep_shellSigma_of_shellLawJ2 {P : ProbabilityMeasure (ShellSeq d)} {S T : Set ℕ}
    (hST : Disjoint S T)
    (hJ2 : SuperdiffusionCLT.Frozen.Assumptions.ShellLawJ2 d P) :
    ProbabilityTheory.Indep (shellSigma (d := d) S) (shellSigma (d := d) T) P.toMeasure :=
  indep_shellSigma_of_disjoint (d := d) hST hJ2.independent

/-- Complement measurability implies ambient measurability. -/
theorem Measurable.of_compl_ambient {T : Set ℕ} {f : ShellSeq d → ℝ}
    (hf : Measurable[shellSigma (d := d) T] f) : Measurable f :=
  hf.mono (shellSigma_le_ambient (d := d) T) le_rfl

/-- The tail-set indicator of a complement-coordinate variable is complement
measurable. -/
theorem measurableSet_upperTail_of_compl {T : Set ℕ} {X : ShellSeq d → ℝ}
    (hX : StronglyMeasurable[shellSigma (d := d) T] X) (c : ℝ) :
    MeasurableSet[shellSigma (d := d) T]
      (Homogenization.IndependentSums.upperTailEvent X c) :=
  StronglyMeasurable.measurableSet_lt stronglyMeasurable_const hX

/-! ## The partial-integral step -/

/-- **The conditional expectation of a complement-coordinate function is its
constant integral.** For `f` measurable with respect to the coordinates in `T`, the
conditional expectation given the coordinates in `S` is a.e. `∫ f ∂μ`: on the
product carrier the conditional law of the `T`-coordinates given the `S`-coordinates
is their unconditional law, so the partial integral collapses to the full integral
against the probability measure. -/
theorem condExp_shellSigma_eq_integral_of_measurable {μ : Measure (ShellSeq d)}
    [IsFiniteMeasure μ] {S T : Set ℕ} (hST : Disjoint S T)
    (hJ2 : ProbabilityTheory.iIndepFun (fun n : ℕ => fun F : ShellSeq d => F n) μ)
    {f : ShellSeq d → ℝ} (hf : StronglyMeasurable[shellSigma (d := d) T] f) :
    μ[f|shellSigma (d := d) S] =ᵐ[μ] fun _ => ∫ ω, f ω ∂μ := by
  have hfin : IsFiniteMeasure (μ.trim (shellSigma_le_ambient (d := d) S)) :=
    isFiniteMeasure_trim _
  exact condExp_indep_eq (shellSigma_le_ambient (d := d) T) (shellSigma_le_ambient (d := d) S)
    hf (indep_shellSigma_of_disjoint (d := d) hST hJ2).symm

/-- The indicator form of the partial-integral step: the conditional probability
given `S` of a `T`-measurable event is its unconditional probability. -/
theorem condExp_indicator_shellSigma_eq_measureReal {μ : Measure (ShellSeq d)}
    [IsFiniteMeasure μ] {S T : Set ℕ} (hST : Disjoint S T)
    (hJ2 : ProbabilityTheory.iIndepFun (fun n : ℕ => fun F : ShellSeq d => F n) μ)
    {s : Set (ShellSeq d)} (hs : MeasurableSet[shellSigma (d := d) T] s) :
    μ[Set.indicator s (fun _ => (1 : ℝ))|shellSigma (d := d) S] =ᵐ[μ]
      fun _ => μ.real s := by
  have hsm : StronglyMeasurable[shellSigma (d := d) T]
      (Set.indicator s (fun _ => (1 : ℝ))) :=
    StronglyMeasurable.indicator stronglyMeasurable_const hs
  have h := condExp_shellSigma_eq_integral_of_measurable (d := d) hST hJ2 hsm
  have hamp : MeasurableSet s := shellSigma_le_ambient (d := d) T s hs
  filter_upwards [h] with ω hω
  rw [hω]
  exact integral_indicator_one hamp

/-! ## The conditional centring is derived -/

/-! ## Transfer of an unconditional bound to a conditional one -/

/-- **The conditional transfer at a constant envelope.** An unconditional
weak-Orlicz bound for a complement-coordinate variable is a conditional bound given
the upper coordinates at the same constant amplitude: its conditional tail is its
unconditional tail. -/
theorem CondIsBigOWith.of_isBigOWith_of_compl {μ : Measure (ShellSeq d)}
    [IsFiniteMeasure μ] {S T : Set ℕ} (hST : Disjoint S T)
    (hJ2 : ProbabilityTheory.iIndepFun (fun n : ℕ => fun F : ShellSeq d => F n) μ)
    {Ψ : ℝ → ℝ} {X : ShellSeq d → ℝ} {A : ℝ}
    (hX : StronglyMeasurable[shellSigma (d := d) T] X)
    (h : Homogenization.IndependentSums.IsBigOWith μ Ψ X A) :
    CondIsBigOWith μ (shellSigma (d := d) S) Ψ X (fun _ => A) := by
  intro t ht
  have hs := measurableSet_upperTail_of_compl (d := d) (T := T) hX (A * t)
  have hc := condExp_indicator_shellSigma_eq_measureReal (d := d) hST hJ2 hs
  simp only [upperTailSet_const]
  filter_upwards [hc] with ω hω
  rw [hω]
  exact h ht

/-- The symmetric form of the conditional transfer. -/
theorem CondIsBigO.of_isBigO_of_compl {μ : Measure (ShellSeq d)}
    [IsFiniteMeasure μ] {S T : Set ℕ} (hST : Disjoint S T)
    (hJ2 : ProbabilityTheory.iIndepFun (fun n : ℕ => fun F : ShellSeq d => F n) μ)
    {Ψ : ℝ → ℝ} {X : ShellSeq d → ℝ} {A : ℝ}
    (hX : StronglyMeasurable[shellSigma (d := d) T] (fun ω => |X ω|))
    (h : Homogenization.IndependentSums.IsBigO μ Ψ X A) :
    CondIsBigO μ (shellSigma (d := d) S) Ψ X (fun _ => A) :=
  CondIsBigOWith.of_isBigOWith_of_compl (d := d) hST hJ2 hX h

/-! ## The conditional envelope -/

/-! ## The conditional concentration step -/

/-- A normalized finite average of complement-coordinate variables is complement
measurable. -/
theorem stronglyMeasurable_finsetAverage_of_compl {T : Set ℕ} {ι : Type*}
    {X : ι → ShellSeq d → ℝ} {s : Finset ι}
    (hX : ∀ i, StronglyMeasurable[shellSigma (d := d) T] (X i)) :
    StronglyMeasurable[shellSigma (d := d) T]
      (fun ω => ((s.card : ℝ)⁻¹) * ∑ i ∈ s, X i ω) := by
  have hsum : StronglyMeasurable[shellSigma (d := d) T] (∑ i ∈ s, X i) :=
    Finset.stronglyMeasurable_sum s fun i _ => hX i
  have hmul : StronglyMeasurable[shellSigma (d := d) T]
      (fun x => ((s.card : ℝ)⁻¹) * (∑ i ∈ s, X i) x) := hsum.const_mul _
  simpa only [Finset.sum_apply] using hmul

/-- The normalized finite average of complement-coordinate variables has a
complement-measurable absolute value. -/
theorem stronglyMeasurable_abs_finsetAverage_of_compl {T : Set ℕ} {ι : Type*}
    {X : ι → ShellSeq d → ℝ} {s : Finset ι}
    (hX : ∀ i, StronglyMeasurable[shellSigma (d := d) T] (X i)) :
    StronglyMeasurable[shellSigma (d := d) T]
      (fun ω => |((s.card : ℝ)⁻¹) * ∑ i ∈ s, X i ω|) := by
  have havg : StronglyMeasurable[shellSigma (d := d) T]
      (fun ω => ((s.card : ℝ)⁻¹) * ∑ i ∈ s, X i ω) :=
    stronglyMeasurable_finsetAverage_of_compl (d := d) hX
  exact continuous_abs.comp_stronglyMeasurable havg

/-- **The conditional concentration step.** Let the summands be measurable with
respect to the coordinates complementary to `S` — the printed situation, where the
summands are functionals of the shells below the cutoff and `S` indexes the shells
above it. Then the normalized average of the summands satisfies the conditional
`Γ_σ` bound at the constant of the unconditional independent-sum theorem.
The conditional independence of the summands given `shellSigma S` is automatic from
`ShellLawJ2`, and so is their conditional centring
(`∫ X ∂μ = 0` with complement measurability gives `μ[X | shellSigma S] =ᵐ 0`). -/
theorem condIsBigO_gammaSigma_finsetAverage_of_compl {μ : Measure (ShellSeq d)}
    [IsProbabilityMeasure μ] {S T : Set ℕ} (hST : Disjoint S T)
    (hJ2 : ProbabilityTheory.iIndepFun (fun n : ℕ => fun F : ShellSeq d => F n) μ)
    {ι : Type*} {X : ι → ShellSeq d → ℝ} {s : Finset ι} {σ K : ℝ}
    (h_indep : ProbabilityTheory.iIndepFun X μ)
    (h_meas : ∀ i, Measurable (X i))
    (h_compl : ∀ i, StronglyMeasurable[shellSigma (d := d) T] (X i))
    (hs : s.Nonempty) (hσ₀ : 0 < σ) (hσ₂ : σ ≤ 2) (hK : 0 < K)
    (hX : ∀ i ∈ s, Homogenization.IndependentSums.IsBigO μ
      (Homogenization.IndependentSums.gammaSigma σ) (X i) K)
    (h_mean : ∀ i ∈ s, ∫ ω, X i ω ∂μ = 0) :
    CondIsBigO μ (shellSigma (d := d) S) (Homogenization.IndependentSums.gammaSigma σ)
      (fun ω => ((s.card : ℝ)⁻¹) * ∑ i ∈ s, X i ω)
      (fun _ => Homogenization.Book.Ch04.gammaSigmaIndependentSumConst σ *
        (Real.sqrt (s.card : ℝ) / (s.card : ℝ)) * K) := by
  have habs : StronglyMeasurable[shellSigma (d := d) T]
      (fun ω => |((s.card : ℝ)⁻¹) * ∑ i ∈ s, X i ω|) :=
    stronglyMeasurable_abs_finsetAverage_of_compl (d := d) h_compl
  have huncond :=
    Homogenization.Book.Ch04.isBigO_gammaSigma_finsetAverage_of_iIndepFun_of_isBigO_of_integral_eq_zero
      h_indep h_meas hs hσ₀ hσ₂ hK hX h_mean
  exact CondIsBigO.of_isBigO_of_compl (d := d) hST hJ2 habs huncond

end SuperdiffusionCLT.Probability
