/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import Mathlib.Probability.Independence.Basic

/-!
# Sigma-fields generated by indexed coordinates

This file defines the sigma-field generated by coordinates in an index set and
records its elementary measurability and independence API.

## Main definitions

* `indexSigma`: the sigma-field generated by a chosen set of coordinates.

## Main results

* `measurable_coordinate_of_mem`: a selected coordinate is measurable with
  respect to its index sigma-field.
* `indep_indexSigma_of_disjoint`: mutually independent measurable coordinates
  generate independent sigma-fields on disjoint index sets.
-/

@[expose] public section

namespace SuperdiffusionCLT.Probability

open MeasureTheory ProbabilityTheory

variable {ι Ω β : Type*} [MeasurableSpace β]

/-- The sigma-field on `Ω` generated by the coordinates of `coordinates` whose
indices belong to `I`. -/
@[instance_reducible]
def indexSigma (coordinates : Ω → ι → β) (I : Set ι) : MeasurableSpace Ω :=
  ⨆ i ∈ I, MeasurableSpace.comap (fun ω ↦ coordinates ω i) inferInstance

/-- The sigma-field generated by one coordinate is contained in the sigma-field
generated by every index set containing that coordinate. -/
theorem comap_coordinate_le_indexSigma (coordinates : Ω → ι → β) {I : Set ι}
    {i : ι} (hi : i ∈ I) :
    MeasurableSpace.comap (fun ω ↦ coordinates ω i) inferInstance ≤
      indexSigma coordinates I := by
  exact le_iSup_of_le i <| le_iSup_of_le hi le_rfl

/-- Coordinates indexed by `I` are measurable with respect to
`indexSigma coordinates I`. -/
theorem measurable_coordinate_of_mem (coordinates : Ω → ι → β) {I : Set ι}
    {i : ι} (hi : i ∈ I) :
    Measurable[indexSigma coordinates I] (fun ω ↦ coordinates ω i) :=
  Measurable.of_comap_le (comap_coordinate_le_indexSigma coordinates hi)

section

variable [MeasurableSpace Ω]

/-- Mutually independent measurable coordinates generate independent sigma-fields
on disjoint index sets. -/
theorem indep_indexSigma_of_disjoint (coordinates : Ω → ι → β) (μ : Measure Ω)
    (h_measurable : ∀ i, Measurable fun ω ↦ coordinates ω i)
    (h_indep : iIndepFun (fun i ω ↦ coordinates ω i) μ) {I J : Set ι}
    (hIJ : Disjoint I J) :
    Indep (indexSigma coordinates I) (indexSigma coordinates J) μ := by
  exact indep_iSup_of_disjoint
    (fun i ↦ (h_measurable i).comap_le) h_indep.iIndep hIJ

end

end SuperdiffusionCLT.Probability
