/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Probability.RealizationSecondConjunct
public import SuperdiffusionCLT.Section3.Terms.LHSTerm1Realization

/-!
# The second conjunct from the per-test-function divergence step

`SuperdiffusionCLT.Probability.RealizationDivFree` defines the orbit divergence.  The
target statement is: for an `L²(Ω)` field `G` whose class is solenoidal and a smooth
compactly supported `θ : Vec d → ℝ`, the orbit divergence

`orbitDivergenceField G θ ω = ∫ x, vecDot (G (x +ᵥ ω)) (∇θ x)`

vanishes for `μ`-almost every `ω`.  That step is owned elsewhere and is taken here as the
named hypothesis `divFreeStep`.

This module builds everything above it, at the concrete carrier `Ω := ShellSeq d`,
`μ := P.toMeasure`, and with the countable dense family of test functions named explicitly:

* the countable intersection of the per-`θ` full-measure sets gives one null set serving the
  whole family (`divFreeStep_ae_all`);
* the orbit-divergence integral of a test function supported in the cube is the `L²(U)` inner
  product of the anchor slice against the gradient class of that test function
  (`integral_eq_setIntegral`, `integral_testGrad_eq_inner`);
* density of the family's gradient classes in the `H¹₀` gradient space upgrades the family
  vanishing to every `φ : H10Function U` (`hpair_of_divFreeStep`), which is exactly the
  hypothesis `hpair` of `RealizationSecondConjunct.exists_realization_of_anchorPairing`;
* the second conjunct then follows by composing with the proved first conjunct.

The countable family is the one input this file does not construct: Mathlib and the pinned
packages have no ready countable dense family of test functions for `H¹₀` of a cube, and the
exact statement needed is recorded as `CountableTestGradientsDense`.
-/

@[expose] public section

open MeasureTheory ProbabilityTheory Homogenization
open SuperdiffusionCLT.Section2.Cutoff
open scoped ENNReal Topology

noncomputable section

namespace SuperdiffusionCLT.Probability.Stationary

variable {d : ℕ}

/-! ## The per-test-function step as a named hypothesis -/

/-- **The `RealizationDivFree` target, carried as a hypothesis.**  For an `L²(Ω)` field `G`
whose `L²` class lies in the solenoidal subspace `stationarySolenoidalSubspace` — the orthogonal
complement of the closed stationary potential subspace — and for every smooth compactly
supported `θ : Vec d → ℝ`, the orbit divergence `∫ x, vecDot (G (x +ᵥ ω)) (∇θ x)` vanishes
for almost every `ω`.  This is one fixed `θ` at a time, which is exactly why the assembly
below needs a countable dense family.

`RealizationDivFree.vecField G` is by construction `fun ω => HilbertVec.ofVec (G ω)`, so the
`MemLp` hypothesis here is literally the file's `MemLp (vecField G) 2 P.toMeasure`, and the
displayed integral is literally its `orbitDivergenceField G θ ω` (both by definitional
unfolding). -/
def divFreeStep (P : ProbabilityMeasure (ShellSeq d))
    [VAddInvariantMeasure (Vec d) (ShellSeq d) P.toMeasure] : Prop :=
  ∀ (G : ShellSeq d → Vec d)
    (hG : MemLp (fun ω => HilbertVec.ofVec (G ω)) 2 P.toMeasure),
    hG.toLp (fun ω => HilbertVec.ofVec (G ω)) ∈
      stationarySolenoidalSubspace (μ := P.toMeasure) (d := d) →
    ∀ (θ : Vec d → ℝ), ContDiff ℝ 1 θ → HasCompactSupport θ →
      ∀ᵐ ω ∂P.toMeasure, ∫ x, vecDot (G (x +ᵥ ω)) (euclideanGradient θ x) = 0

/-- The coordinate kernel of a `C¹` function is continuous. -/
theorem continuous_coordFderiv {θ : Vec d → ℝ} (hθ : ContDiff ℝ 1 θ) (i : Fin d) :
    Continuous (fun y : Vec d => fderiv ℝ θ y (basisVec i)) :=
  (hθ.continuous_fderiv (by simp)).clm_apply continuous_const

/-- The coordinate kernel of a `C¹` function of compact support is integrable: its pointwise
support lies in `tsupport θ` by `fderiv_of_notMem_tsupport`, so its topological support lies
there too. -/
theorem integrable_coordFderiv {θ : Vec d → ℝ} (hθ : ContDiff ℝ 1 θ)
    (hθc : HasCompactSupport θ) (i : Fin d) :
    Integrable (fun y : Vec d => fderiv ℝ θ y (basisVec i)) volume := by
  refine Continuous.integrable_of_hasCompactSupport (continuous_coordFderiv hθ i) ?_
  have hsub : Function.support (fun y : Vec d => fderiv ℝ θ y (basisVec i)) ⊆ tsupport θ := by
    intro y hy
    by_contra hmem
    exact hy (by
      show (fderiv ℝ θ y) (basisVec i) = 0
      rw [fderiv_of_notMem_tsupport (𝕜 := ℝ) hmem]
      rfl)
  exact hθc.of_isClosed_subset (isClosed_tsupport _)
    (closure_minimal hsub (isClosed_tsupport _))

/-! ## The countable dense family of test functions -/

/-- **The countable dense family.**  A sequence of smooth compactly supported test functions
on the cube, fixed once and for all, whose `L²(U)` gradient classes are dense in the gradient
space `{∇φ : φ ∈ H¹₀(U)}` generated by the `H¹₀` test functions of the weak equation.

This is the step that genuinely needs a countable family: `divFreeStep` is per-`θ`, so the null
set it produces depends on `θ`; intersecting countably many of them gives a single null set, and
density of the family then serves the uncountably many `φ : H10Function U` at once. -/
def CountableTestGradientsDense (Q : TriadicCube d) : Prop :=
  ∃ (θs : ℕ → Vec d → ℝ)
    (hθ : ∀ j, ContDiff ℝ 1 (θs j) ∧ HasCompactSupport (θs j) ∧
      tsupport (θs j) ⊆ openCubeSet Q),
    ∀ φ : H10Function (openCubeSet Q),
      φ.toH1Function.gradToHilbertVectorL2 ∈
        closure (Set.range fun j =>
          (H1Function.ofContDiff (isOpen_openCubeSet Q) (hθ j).1
            (hθ j).2.1).gradToHilbertVectorL2)

/-! ## Countable intersection of the per-test-function null sets -/

/-- Intersecting the countably many full-measure sets produced by `divFreeStep`, one per test
function, gives a single null set serving the whole family.  This is the step that makes the
uncountable family `H10Function (openCubeSet Q)` tractable: only a *countable* family of test
functions is ever fed to `divFreeStep`. -/
theorem divFreeStep_ae_all {P : ProbabilityMeasure (ShellSeq d)}
    [VAddInvariantMeasure (Vec d) (ShellSeq d) P.toMeasure]
    (hstep : divFreeStep (d := d) P) {G : ShellSeq d → Vec d}
    (hG : MemLp (fun ω => HilbertVec.ofVec (G ω)) 2 P.toMeasure)
    (hGsol : hG.toLp (fun ω => HilbertVec.ofVec (G ω)) ∈
      stationarySolenoidalSubspace (μ := P.toMeasure) (d := d))
    (θs : ℕ → Vec d → ℝ) (hθ : ∀ j, ContDiff ℝ 1 (θs j))
    (hθs : ∀ j, HasCompactSupport (θs j)) :
    ∀ᵐ ω ∂P.toMeasure, ∀ j,
      ∫ x, vecDot (G (x +ᵥ ω)) (euclideanGradient (θs j) x) = 0 :=
  MeasureTheory.ae_all_iff.2 fun j => hstep G hG hGsol (θs j) (hθ j) (hθs j)

/-! ## Support restriction and the inner-product bridge -/

/-- A test function whose topological support lies in the cube has zero Euclidean gradient off
that support, hence the unrestricted integral is the integral over the cube alone. -/
theorem integral_eq_setIntegral {Q : TriadicCube d} {θ : Vec d → ℝ}
    (hsub : tsupport θ ⊆ openCubeSet Q) (G : ShellSeq d → Vec d) (ω : ShellSeq d) :
    (∫ x, vecDot (G (x +ᵥ ω)) (euclideanGradient θ x)) =
      ∫ x in openCubeSet Q, vecDot (G (x +ᵥ ω)) (euclideanGradient θ x) :=
  (MeasureTheory.setIntegral_eq_integral_of_forall_compl_eq_zero fun x hx => by
    rw [euclideanGradient_eq_zero_of_notMem_tsupport fun h => hx (hsub h),
      vecDot_zero_right]).symm

/-- **The divergence pairing against a smooth test, as an `L²(U)` inner product.**  Reading the
test function through `H1Function.ofContDiff` — whose `grad` is definitionally the Euclidean
gradient — turns the weak-equation functional into the inner product of the slice class
of the field with the gradient class of the test function. -/
theorem integral_testGrad_eq_inner {Q : TriadicCube d} {θ : Vec d → ℝ}
    {W : ShellSeq d → Vec d} {ω : ShellSeq d} (hθ : ContDiff ℝ 1 θ)
    (hθc : HasCompactSupport θ)
    (hWsl : MemLp (fun x => HilbertVec.ofVec (W (x +ᵥ ω))) 2
      (volumeMeasureOn (openCubeSet Q))) :
    ∫ x in openCubeSet Q, vecDot (W (x +ᵥ ω)) (euclideanGradient θ x) =
      inner ℝ (hWsl.toLp (fun x => HilbertVec.ofVec (W (x +ᵥ ω))))
        (H1Function.ofContDiff (isOpen_openCubeSet Q) hθ hθc).gradToHilbertVectorL2 := by
  have hgrad : (H1Function.ofContDiff (isOpen_openCubeSet Q) hθ hθc).grad =
      euclideanGradient θ := rfl
  rw [← hgrad]
  exact integral_vecDot_eq_inner_of_ae_eq (MemLp.coeFn_toLp hWsl) _

/-! ## Density: a countable family serves the whole `H¹₀` equation -/

/-- **Families of test functions, not single tests, serve the `H¹₀` equation.**  Fix a sample
`ω` at which the orbit divergence vanishes against every member of a countable family whose
gradient classes are dense.  The functional `v ↦ inner ℝ slice v` is continuous, so its zero
set is closed; it contains every family member by the inner-product bridge, hence contains the
closure of the family, hence — by the density hypothesis — the gradient class of every `H¹₀`
test function. -/
theorem pairing_zero_of_family_zero {Q : TriadicCube d} {θs : ℕ → Vec d → ℝ}
    (hθ : ∀ j, ContDiff ℝ 1 (θs j) ∧ HasCompactSupport (θs j) ∧
      tsupport (θs j) ⊆ openCubeSet Q)
    (hdense : ∀ φ : H10Function (openCubeSet Q),
      φ.toH1Function.gradToHilbertVectorL2 ∈
        closure (Set.range fun j =>
          (H1Function.ofContDiff (isOpen_openCubeSet Q) (hθ j).1
            (hθ j).2.1).gradToHilbertVectorL2))
    {W : ShellSeq d → Vec d} {ω : ShellSeq d}
    (hWsl : MemLp (fun x => HilbertVec.ofVec (W (x +ᵥ ω))) 2
      (volumeMeasureOn (openCubeSet Q)))
    (hzero : ∀ j, ∫ x, vecDot (W (x +ᵥ ω)) (euclideanGradient (θs j) x) = 0) :
    ∀ φ : H10Function (openCubeSet Q),
      ∫ x in openCubeSet Q, vecDot (W (x +ᵥ ω)) (φ.toH1Function.grad x) = 0 := by
  set cls := hWsl.toLp (fun x => HilbertVec.ofVec (W (x +ᵥ ω))) with hcls
  set Gcls : ℕ → HilbertVectorL2 (openCubeSet Q) := fun j =>
    (H1Function.ofContDiff (isOpen_openCubeSet Q) (hθ j).1 (hθ j).2.1).gradToHilbertVectorL2
    with hGcls
  have hinner : ∀ j, inner ℝ cls (Gcls j) = 0 := by
    intro j
    rw [hcls, hGcls]
    rw [← integral_testGrad_eq_inner (hθ j).1 (hθ j).2.1 hWsl]
    rw [← integral_eq_setIntegral (hθ j).2.2 W ω]
    exact hzero j
  have hclosed : IsClosed {v : HilbertVectorL2 (openCubeSet Q) | inner ℝ cls v = 0} :=
    isClosed_eq (by fun_prop) continuous_const
  have hsub : Set.range Gcls ⊆
      {v : HilbertVectorL2 (openCubeSet Q) | inner ℝ cls v = 0} := by
    rintro v ⟨j, rfl⟩
    exact hinner j
  intro φ
  have hmem : φ.toH1Function.gradToHilbertVectorL2 ∈ closure (Set.range Gcls) := by
    rw [hGcls]
    exact hdense φ
  have hzeroφ : inner ℝ cls φ.toH1Function.gradToHilbertVectorL2 = 0 :=
    closure_minimal hsub hclosed hmem
  rw [integral_vecDot_eq_inner_of_ae_eq (MemLp.coeFn_toLp hWsl) φ.toH1Function, ← hcls]
  exact hzeroφ

/-! ## The per-sample anchor pairing, from `divFreeStep` -/

/-- **The second conjunct's per-sample pairing, from `divFreeStep`.**  The anchor field
`gradHatW + F (·) 0` is replaced by a measurable representative of its class, solenoidal by
`anchorStationaryField_toLp_mem_stationarySolenoidalSubspace`; `divFreeStep` is applied to the
countable family and `pairing_zero_of_family_zero` extends the vanishing to every `H¹₀` test
function; one `integral_congr_ae` returns to the literal anchor field. -/
theorem hpair_of_divFreeStep {P : ProbabilityMeasure (ShellSeq d)}
    [VAddInvariantMeasure (Vec d) (ShellSeq d) P.toMeasure]
    (M : ℕ) {F : ShellSeq d → Vec d → Vec d} {gradHatW : ShellSeq d → Vec d}
    (hstep : divFreeStep (d := d) P)
    (hdense : CountableTestGradientsDense (originCube d (M : ℤ)))
    (hFmemLp : MemLp (fun ω : ShellSeq d => HilbertVec.ofVec (F ω 0)) 2 P.toMeasure)
    (hGmemLp : MemLp (fun ω : ShellSeq d => HilbertVec.ofVec (gradHatW ω)) 2 P.toMeasure)
    (hproj : hGmemLp.toLp (fun ω : ShellSeq d => HilbertVec.ofVec (gradHatW ω)) =
      -stationaryPotentialProjection (μ := P.toMeasure) (d := d)
        (hFmemLp.toLp (fun ω : ShellSeq d => HilbertVec.ofVec (F ω 0)))) :
    ∀ᵐ ω ∂P.toMeasure, ∀ φ : H10Function (openCubeSet (originCube d (M : ℤ))),
      ∫ x in openCubeSet (originCube d (M : ℤ)),
        vecDot (anchorStationaryField gradHatW F (x +ᵥ ω)) (φ.toH1Function.grad x) = 0 := by
  classical
  obtain ⟨θs, hθ, hdense'⟩ := hdense
  obtain ⟨W, hWm, hWmem, hWtoLp⟩ := exists_measurable_representative_of_vectorL2 (P := P)
    ((anchorStationaryField_memLp (P := P) hFmemLp hGmemLp).toLp
      (fun ω : ShellSeq d => HilbertVec.ofVec (anchorStationaryField gradHatW F ω)))
  have hWsol : hWmem.toLp (fun ω : ShellSeq d => HilbertVec.ofVec (W ω)) ∈
      stationarySolenoidalSubspace (μ := P.toMeasure) (d := d) := by
    rw [hWtoLp]
    exact anchorStationaryField_toLp_mem_stationarySolenoidalSubspace (P := P) hproj
  have hstep_all : ∀ᵐ ω ∂P.toMeasure, ∀ j,
      ∫ x, vecDot (W (x +ᵥ ω)) (euclideanGradient (θs j) x) = 0 :=
    divFreeStep_ae_all (P := P) hstep hWmem hWsol θs
      (fun j => (hθ j).1) (fun j => (hθ j).2.1)
  have hWae : W =ᵐ[P.toMeasure] anchorStationaryField gradHatW F := by
    have h1 : (hWmem.toLp (fun ω : ShellSeq d => HilbertVec.ofVec (W ω)) :
        ShellSeq d → HilbertVec d) =ᵐ[P.toMeasure] fun ω => HilbertVec.ofVec (W ω) :=
      MemLp.coeFn_toLp hWmem
    have h2 : (hWmem.toLp (fun ω : ShellSeq d => HilbertVec.ofVec (W ω)) :
        ShellSeq d → HilbertVec d) =ᵐ[P.toMeasure]
        fun ω => HilbertVec.ofVec (anchorStationaryField gradHatW F ω) := by
      rw [hWtoLp]
      exact MemLp.coeFn_toLp (anchorStationaryField_memLp (P := P) hFmemLp hGmemLp)
    exact (h1.symm.trans h2).mono fun _ hω => by
      have h := congrArg HilbertVec.toVec hω
      simpa only [HilbertVec.toVec_ofVec] using h
  have hWslice := ae_memLp_slice_openCube_vec (P := P) (originCube d (M : ℤ)) hWm hWmem
  have hsliceEq := ae_slice_eq_of_ae_eq (P := P) hWae (originCube d (M : ℤ))
  filter_upwards [hstep_all, hWslice, hsliceEq] with ω hωzero hωsl hωeq
  have hkey : ∀ φ : H10Function (openCubeSet (originCube d (M : ℤ))),
      ∫ x in openCubeSet (originCube d (M : ℤ)),
        vecDot (W (x +ᵥ ω)) (φ.toH1Function.grad x) = 0 :=
    pairing_zero_of_family_zero (Q := originCube d (M : ℤ)) hθ hdense' hωsl hωzero
  intro φ
  have hcongr : (fun x => vecDot (W (x +ᵥ ω)) (φ.toH1Function.grad x))
      =ᵐ[volumeMeasureOn (openCubeSet (originCube d (M : ℤ)))]
      fun x => vecDot (anchorStationaryField gradHatW F (x +ᵥ ω))
        (φ.toH1Function.grad x) := by
    filter_upwards [hωeq] with x hx
    rw [hx]
  rw [← MeasureTheory.integral_congr_ae hcongr]
  exact hkey φ

/-! ## The second conjunct from `divFreeStep` -/

/-- **The second conjunct at the concrete carrier, carrying `divFreeStep`.**  This is the
whole conclusion of
`SuperdiffusionCLT.Frozen.Section3.stationaryPotentialRealization` (both conjuncts: the `H¹`
realization of the translated potential field, which is the proved first conjunct, and the
per-sample weak equation, which is the second) at `Ω := ShellSeq d`, `μ := P.toMeasure` and cube
side `M`.  The assembly is `RealizationSecondConjunct.exists_realization_of_anchorPairing`,
whose only per-sample input is `hpair`; that input is produced here by `hpair_of_divFreeStep`
from the per-test-function step `divFreeStep` and the countable dense family of test functions. -/
theorem exists_realization_of_divFreeStep {P : ProbabilityMeasure (ShellSeq d)}
    [VAddInvariantMeasure (Vec d) (ShellSeq d) P.toMeasure]
    (M : ℕ) {F : ShellSeq d → Vec d → Vec d} {gradHatW : ShellSeq d → Vec d}
    (hstep : divFreeStep (d := d) P)
    (hdense : CountableTestGradientsDense (originCube d (M : ℤ)))
    (hcocycle : ∀ (ω : ShellSeq d) (x y : Vec d), F (x +ᵥ ω) y = F ω (y + x))
    (hFmemLp : MemLp (fun ω : ShellSeq d => HilbertVec.ofVec (F ω 0)) 2 P.toMeasure)
    (hGmemLp : MemLp (fun ω : ShellSeq d => HilbertVec.ofVec (gradHatW ω)) 2 P.toMeasure)
    (hproj : hGmemLp.toLp (fun ω : ShellSeq d => HilbertVec.ofVec (gradHatW ω)) =
      -stationaryPotentialProjection (μ := P.toMeasure) (d := d)
        (hFmemLp.toLp (fun ω : ShellSeq d => HilbertVec.ofVec (F ω 0)))) :
    ∃ uReal : ShellSeq d → H1Function (openCubeSet (originCube d (M : ℤ))),
      (∀ᵐ ω ∂P.toMeasure,
        (uReal ω).grad =ᵐ[volumeMeasureOn (openCubeSet (originCube d (M : ℤ)))]
          fun x => gradHatW (x +ᵥ ω)) ∧
      (∀ᵐ ω ∂P.toMeasure, ∀ φ : H10Function (openCubeSet (originCube d (M : ℤ))),
        ∫ x in openCubeSet (originCube d (M : ℤ)),
            vecDot ((uReal ω).grad x) (φ.toH1Function.grad x) =
          -∫ x in openCubeSet (originCube d (M : ℤ)),
            vecDot (F ω x) (φ.toH1Function.grad x)) :=
  exists_realization_of_anchorPairing (P := P) M hcocycle hFmemLp hGmemLp hproj
    (hpair_of_divFreeStep (P := P) M hstep hdense hFmemLp hGmemLp hproj)

/-! ## The term `l.LHS.term1` -/

open MeasureTheory ProbabilityTheory Homogenization Homogenization.Book.Ch02
  Homogenization.IndependentSums SuperdiffusionCLT.Frozen.Assumptions
  SuperdiffusionCLT.Frozen.Section2 SuperdiffusionCLT.Probability
  SuperdiffusionCLT.Section2.Norms SuperdiffusionCLT.Section3.ResponseFields
  SuperdiffusionCLT.Section3.Setup in
/-- **`l.LHS.term1` from `divFreeStep` and the countable dense family.**  The conclusion is the
statement of `l.LHS.term1` character for character, as in
`LHSTerm1Realization.lhs_term1_statement_of_cocycle`; the two hypotheses beyond it are the
per-test-function step `divFreeStep` for every shell law and the countable dense family of test
functions on every cube.  Inside the proof the cocycle of the glued flux is
`sandwichFlux_cocycle`, so no cocycle clause reaches the statement's surface. -/
theorem lhs_term1_of_divFreeStep (d : ℕ) [NeZero d] (hd : 2 ≤ d)
    (hstep : ∀ (P : MeasureTheory.ProbabilityMeasure (ShellSeq d))
      [VAddInvariantMeasure (Vec d) (ShellSeq d) P.toMeasure], divFreeStep (d := d) P)
    (hdense : ∀ M : ℕ, CountableTestGradientsDense (originCube d M)) :
    ∃ C : ℝ, 1 ≤ C ∧
      ∀ (nu : ℝ), 0 < nu → nu ≤ 1 →
        ∀ (P : MeasureTheory.ProbabilityMeasure (ShellSeq d))
          (hPrefix : ShellLawPrefix d P), ShellLawJ1Restriction d P →
          ∀ (hJ2 : ShellLawJ2 d P) (hJ3 : ShellLawJ3 d P), ShellLawJ4 d P →
          ∀ (cStar K : ℝ), ShellLawJ5 d P cStar K hPrefix hJ2 hJ3 →
          ∀ (S : ScaleSelection), ScalesOrdering S →
          ∀ (e : Vec d), Homogenization.vecNormSq e = 1 →
            Homogenization.Book.Ch02.vecNorm e = 1 →
            ∀ (p : Vec d), p = testVector nu S.LPrime P S.n e →
            ∀ (F : ShellSeq d → Vec d → Vec d),
              (∀ omega : ShellSeq d, F omega = fun x =>
                Homogenization.matVecMul
                  (SuperdiffusionCLT.Frozen.Section2.streamCutoff
                      omega S.LPrime x -
                    SuperdiffusionCLT.Frozen.Section2.streamCutoff
                      omega S.ellPrime x) p) →
              ∀ (w : ShellSeq d →
                  Homogenization.H10Function
                    (Homogenization.openCubeSet
                      (Homogenization.originCube d (S.m : ℤ)))),
                (∀ omega : ShellSeq d,
                  IsCubeDirichletResponse (originCube d (S.m : ℤ)) (F omega)
                    (w omega)) →
                |(∫⁻ omega : ShellSeq d,
                      vecCubeLpENorm (originCube d (S.m : ℤ)) 2
                        (w omega).toH1Function.grad ^ (2 : ℕ) ∂P.toMeasure :
                  ℝ≥0∞).toReal -
                  cStar * Real.log 3 * ((S.m - S.n : ℕ) : ℝ) * vecNormSq p| ≤
                (C * (1 + ((S.LPrime - S.m : ℕ) : ℝ)) + K) * vecNormSq p :=
  SuperdiffusionCLT.Section3.Terms.lhs_term1_statement_of_cocycle d hd
    fun P hPrefix hJ2 S F gradHatW hcocycle hFmemLp hGmemLp hproj => by
      let := Frozen.Assumptions.ShellField.vaddInvariantMeasure hPrefix hJ2
      exact exists_realization_of_divFreeStep (P := P) S.m (hstep P) (hdense S.m)
        hcocycle hFmemLp hGmemLp hproj

end SuperdiffusionCLT.Probability.Stationary

end
