/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Section3.Terms.RHSTerm2Decoupling
public import SuperdiffusionCLT.Section3.Terms.GluedFieldAverages

/-!
# `hDecouple` from J2, and `l.RHS.term2` with that input discharged

The paper justifies the
vanishing `E[(R)_{z+cu_n}·((∇ũ_{n,z})_{z+cu_n} − p̃)] = 0` in one sentence:

> Let `F_> := σ(j_r : r > ℓ)`.  The field `R` is `F_>`-measurable, while
> `∇ũ_n` is measurable with respect to `σ(j_r : r ≤ ℓ)`.

and the independence of those two sigma-fields is exactly
`ShellLawJ2`: the shells are mutually independent, so complementary blocks of
shells generate independent sigma-fields.

This module carries that deduction.  `lowShellSigma` and `highShellSigma` are
the two sigma-fields of the paper, `indep_high_low_shellSigma` is their
independence from `ShellLawJ2.independent` through Mathlib's
`indep_iSup_of_disjoint`, and `indepFun_high_low_of_shellLawJ2` turns it into
the independence of a `F_>`-measurable observable and a `σ(j_r : r ≤ ℓ)`
-measurable one.

`decoupling_bridge_of_shellLawJ2` is then `decoupling_bridge` of
`RHSTerm2Decoupling.lean` with its one non-J2 input replaced by the printed
measurability sentence, read on the two *cube mean vectors* — the only form of
it the vanishing uses, and a weaker demand than measurability of the fields
themselves, since a cube mean of an `F_>`-measurable field is `F_>`-measurable.

`l_RHS_term2_of_anchors` is `l_RHS_term2_constFirst` of `RHSTerm2Glued.lean`
with the binder `hDecouple` removed and that sentence, together with the
sample-level typing data of `independence_decoupling`, put in its place.  The
shell law `ShellLawJ2` is already one of the binders of the statement, so J2 is
consumed inside the theorem and nothing new about the law is assumed.

## What stays explicit, and why

* the two measurability hypotheses.  `R = (k_{L'} − k_ℓ)^t ∇w` is built from
  the Dirichlet response `w`, a free binder of the rendered statement given
  only by `IsDirichletResponse`; nothing in the statement records how `w`
  depends on the shells.  For the proxy the carrier is
  `gluedGradientField` at cutoff `ℓ`, whose cube pieces come from
  `Book.Ch02.responseExistenceTheory` through a choice (see `qVector_apply` of
  `GluedField`), so no declaration gives joint measurability in
  `omega` for it either.  These are the range-of-dependence facts the paper
  asserts and never proves.
* `hRint`, integrability in the sample of the cube means of `R`.  It is typing
  data of the same kind the statement already carries for the four annealed
  cube norms (`hmR`, `hmDR`, `hmDiff`, `hmProx`), and it is unavailable for the
  same reason: `w` is a free binder.
* `hTint` and `hmean` for the proxy.  For the glued proxy both are
  reachable — `hTint` from `integrable_sigmaStarInvCoarse` of
  `GluedFieldAverages` at the translated cube through
  `volumeAverageVec_gluedGradientField`, and `hmean` from
  `integral_sigmaStarInvCoarse_openCubeSet_eq` of `GluedField` at the
  cutoff level `ℓ` — but `uTildeGlued` is a free binder of
  `l_RHS_term2_constFirst`, so at this surface they stay explicit.
-/

@[expose] public section

namespace SuperdiffusionCLT.Section3.Terms

open MeasureTheory
open ProbabilityTheory
open SuperdiffusionCLT.Section2.Cutoff
open SuperdiffusionCLT.Frozen.Assumptions
open SuperdiffusionCLT.Frozen.Section2
open SuperdiffusionCLT.Section3.ResponseFields
open SuperdiffusionCLT.Section3.Setup
open SuperdiffusionCLT.Section2.Estimates.Stream
open Homogenization
open Homogenization.Book.Ch02
open scoped ENNReal

noncomputable section

variable {d : ℕ}

/-! ## The two sigma-fields of the independence argument -/

/-- The sigma-field generated by the shell `j_r` alone, read on the sequence
carrier. -/
@[instance_reducible]
def shellCoordSigma (d r : ℕ) : MeasurableSpace (ShellSeq d) :=
  MeasurableSpace.comap (fun omega : ShellSeq d => omega r) inferInstance

theorem shellCoordSigma_le (r : ℕ) :
    shellCoordSigma d r ≤ (inferInstance : MeasurableSpace (ShellSeq d)) :=
  (ShellField.measurable_shellCoordinate (d := d) r).comap_le

/-- `σ(j_r : r ≤ ℓ)`: the information the coefficient cutoff at
scale `ℓ`, hence the proxy `∇ũ_n`, can read. -/
@[instance_reducible]
def lowShellSigma (d ell : ℕ) : MeasurableSpace (ShellSeq d) :=
  ⨆ r ∈ Set.Iic ell, shellCoordSigma d r

/-- `F_> = σ(j_r : r > ℓ)`: the information the increment
`k_{L'} − k_ℓ`, hence the field `R`, can read. -/
@[instance_reducible]
def highShellSigma (d ell : ℕ) : MeasurableSpace (ShellSeq d) :=
  ⨆ r ∈ Set.Ioi ell, shellCoordSigma d r

theorem disjoint_Ioi_Iic (ell : ℕ) : Disjoint (Set.Ioi ell) (Set.Iic ell) := by
  rw [Set.disjoint_left]
  intro r hr hr'
  exact absurd (Set.mem_Iic.1 hr') (not_le.2 (Set.mem_Ioi.1 hr))

/-! ## J2 makes the two blocks independent -/

/-- **Disjoint blocks of shells are independent.**  `ShellLawJ2` is the mutual
independence of the coordinate maps of the shell sequence; Mathlib's
`indep_iSup_of_disjoint` upgrades it to independence of the joins over two
disjoint sets of shells. -/
theorem indep_shellRange_of_shellLawJ2 {P : ProbabilityMeasure (ShellSeq d)}
    (hJ2 : ShellLawJ2 d P) {S T : Set ℕ} (hST : Disjoint S T) :
    Indep (⨆ r ∈ S, shellCoordSigma d r) (⨆ r ∈ T, shellCoordSigma d r) P.toMeasure :=
  indep_iSup_of_disjoint (fun r => shellCoordSigma_le r) hJ2.independent.iIndep hST

/-- **`F_>` and `σ(j_r : r ≤ ℓ)` are independent**, the
consequence of `a.j.indy` used in the paper. -/
theorem indep_high_low_shellSigma {P : ProbabilityMeasure (ShellSeq d)}
    (hJ2 : ShellLawJ2 d P) (ell : ℕ) :
    Indep (highShellSigma d ell) (lowShellSigma d ell) P.toMeasure :=
  indep_shellRange_of_shellLawJ2 hJ2 (disjoint_Ioi_Iic ell)

/-- **The printed decoupling of two observables**: an `F_>`-measurable
observable and a `σ(j_r : r ≤ ℓ)`-measurable one are independent under
`ShellLawJ2`. -/
theorem indepFun_high_low_of_shellLawJ2 {P : ProbabilityMeasure (ShellSeq d)}
    (hJ2 : ShellLawJ2 d P) (ell : ℕ) {beta gamma : Type*}
    [MeasurableSpace beta] [MeasurableSpace gamma]
    {f : ShellSeq d → beta} {g : ShellSeq d → gamma}
    (hf : Measurable[highShellSigma d ell] f)
    (hg : Measurable[lowShellSigma d ell] g) :
    IndepFun f g P.toMeasure :=
  indep_of_indep_of_le_right
    (indep_of_indep_of_le_left (indep_high_low_shellSigma hJ2 ell) hf.comap_le)
    hg.comap_le

/-! ## `hDecouple` from J2 and the printed measurability sentence -/

/-- **`hDecouple` from `ShellLawJ2`**: `decoupling_bridge` of
`RHSTerm2Decoupling` with its independence input replaced by the measurability
sentence of the paper, read on the cube means.  J2 supplies the independence of
the two blocks of shells; the two hypotheses `hRmeas` and `hTmeas` are the
measurability half of that sentence, which is not derived here (see
the module docstring). -/
theorem decoupling_bridge_of_shellLawJ2 {n m ell : ℕ}
    {P : ProbabilityMeasure (ShellSeq d)}
    {Rf UT : ShellSeq d → Vec d → Vec d} {pT : Vec d} (hJ2 : ShellLawJ2 d P)
    (hR : ∀ omega : ShellSeq d,
      MemVectorL2 (openCubeSet (originCube d (m : ℤ))) (Rf omega))
    (hT : ∀ omega : ShellSeq d,
      MemVectorL2 (openCubeSet (originCube d (m : ℤ))) (UT omega))
    (hRmeas : ∀ z ∈ largeCubeSubcubes d n m, Measurable[highShellSigma d ell]
      (fun omega : ShellSeq d => volumeAverageVec (openCubeSet z) (Rf omega)))
    (hTmeas : ∀ z ∈ largeCubeSubcubes d n m, Measurable[lowShellSigma d ell]
      (fun omega : ShellSeq d => volumeAverageVec (openCubeSet z) (UT omega)))
    (hRint : ∀ z ∈ largeCubeSubcubes d n m, ∀ i : Fin d, Integrable
      (fun omega : ShellSeq d => volumeAverageVec (openCubeSet z) (Rf omega) i) P.toMeasure)
    (hTint : ∀ z ∈ largeCubeSubcubes d n m, ∀ i : Fin d, Integrable
      (fun omega : ShellSeq d => volumeAverageVec (openCubeSet z) (UT omega) i) P.toMeasure)
    (hmean : ∀ z ∈ largeCubeSubcubes d n m, ∀ i : Fin d,
      ∫ omega : ShellSeq d,
        volumeAverageVec (openCubeSet z) (UT omega) i ∂P.toMeasure = pT i)
    (hIntProxy : Integrable (fun omega : ShellSeq d =>
      volumeAverage (openCubeSet (originCube d (m : ℤ)))
        (fun y => vecDot (Rf omega y) (UT omega y - pT))) P.toMeasure) :
    ∫ omega : ShellSeq d,
        volumeAverage (openCubeSet (originCube d (m : ℤ)))
          (fun y => vecDot (Rf omega y) (UT omega y - pT)) ∂P.toMeasure =
      ∫ omega : ShellSeq d,
        (((largeCubeSubcubes d n m).card : ℝ)⁻¹ *
          ∑ z ∈ largeCubeSubcubes d n m,
            volumeAverage (openCubeSet z)
              (fun y => vecDot
                (Rf omega y - volumeAverageVec (openCubeSet z) (Rf omega))
                (UT omega y -
                  volumeAverageVec (openCubeSet z) (UT omega)))) ∂P.toMeasure :=
  decoupling_bridge hR hT
    (fun z hz => indepFun_high_low_of_shellLawJ2 hJ2 ell (hRmeas z hz) (hTmeas z hz))
    hRint hTint hmean hIntProxy

/-! ## `l.RHS.term2` with `hDecouple` discharged -/

/-- **`l_RHS_term2_constFirst` with the binder `hDecouple` discharged**.
Everything is as in `l_RHS_term2_constFirst` of
`RHSTerm2Glued` except that the decoupling identity is no longer assumed:
in its place stand the printed measurability sentence on the
two cube mean vectors and the sample-level typing data of
`independence_decoupling`.  The independence itself is produced inside the
proof from the binder `ShellLawJ2` of the statement.

See the module docstring for why each of the five replacement hypotheses is not
derivable at this surface. -/
theorem l_RHS_term2_of_anchors (d : ℕ) [NeZero d] (hd : 2 ≤ d)
    (C₁ C₂ C₃ Cpoin : ℝ) (hC₁ : 1 ≤ C₁) (hC₂ : 1 ≤ C₂) (hC₃ : 1 ≤ C₃)
    (hCpoin : 0 ≤ Cpoin) :
    ∃ C : ℝ, 1 ≤ C ∧
      ∀ (nu : ℝ), 0 < nu → nu ≤ 1 →
      ∀ (P : ProbabilityMeasure (ShellSeq d)), ShellLawPrefix d P →
        ShellLawJ1Restriction d P → ShellLawJ2 d P → ShellLawJ3 d P → ShellLawJ4 d P →
      ∀ (S : ScaleSelection), ScalesOrdering S →
      ∀ (e : Vec d), vecNormSq e = 1 →
      ∀ (p : Vec d), p = testVector nu S.LPrime P S.n e →
      ∀ (w : ShellSeq d → H10Function (openCubeSet (originCube d (S.m : ℤ)))),
        (∀ omega : ShellSeq d,
          IsDirichletResponse omega S.LPrime S.ellPrime S.m p (w omega)) →
      ∀ (uNGlued uTildeGlued : ShellSeq d → Vec d → Vec d) (pTilde : Vec d)
        (DR : ShellSeq d → Fin d → Vec d → Vec d),
        (∀ omega : ShellSeq d, ∀ i : Fin d,
          HasWeakGradientOn (openCubeSet (originCube d (S.m : ℤ)))
            (fun x => (matVecMul ((coefficientCutoff nu omega S.LPrime).toCoeffField x -
                  (coefficientCutoff nu omega S.ell).toCoeffField x)
                ((w omega).toH1Function.grad x)) i) (DR omega i)) →
        ((∫⁻ omega : ShellSeq d,
              SuperdiffusionCLT.Section3.ResponseFields.vecCubeLpENorm
                (originCube d (S.m : ℤ)) 2
                (fun x => matVecMul ((coefficientCutoff nu omega S.LPrime).toCoeffField x -
                  (coefficientCutoff nu omega S.ell).toCoeffField x)
                  ((w omega).toH1Function.grad x)) ^
            (2 : ℕ) ∂P.toMeasure : ℝ≥0∞).toReal ^ ((1 : ℝ) / 2) +
          (3 : ℝ) ^ ((S.ell : ℕ) : ℝ) *
            (∫⁻ omega : ShellSeq d,
                SuperdiffusionCLT.Section2.Norms.cubeLpENorm
                    (originCube d (S.m : ℤ)) 2
                    (fun x => HilbertMat.ofMat (fun i j => DR omega i x j)) ^
              (2 : ℕ) ∂P.toMeasure : ℝ≥0∞).toReal ^ ((1 : ℝ) / 2) ≤
          C₁ * ((S.LPrime : ℕ) : ℝ) * Real.sqrt (vecNormSq p)) →
        ((∫⁻ omega : ShellSeq d,
              SuperdiffusionCLT.Section3.ResponseFields.vecCubeLpENorm
                  (originCube d (S.m : ℤ)) 2
                  (fun x => uNGlued omega x - uTildeGlued omega x) ^
            (2 : ℕ) ∂P.toMeasure : ℝ≥0∞).toReal ^ ((1 : ℝ) / 2) +
          Real.sqrt (vecNormSq (pTilde - p)) ≤
          C₂ * nu ^ (-((3 : ℝ) / 2)) * ((S.LPrime : ℕ) : ℝ) *
            (3 : ℝ) ^ (-((((S.ell - S.n : ℕ) : ℝ)) / 2)) *
            (sigmaBarStarInvSqrt nu S.LPrime P S.n)⁻¹) →
        ((∫⁻ omega : ShellSeq d,
              SuperdiffusionCLT.Section3.ResponseFields.vecCubeLpENorm
                  (originCube d (S.m : ℤ)) 2
                  (fun x => uTildeGlued omega x - pTilde) ^
            (2 : ℕ) ∂P.toMeasure : ℝ≥0∞).toReal ^ ((1 : ℝ) / 2) ≤
          C₃ * nu ^ (-(1 : ℝ)) * (sigmaBarStarInvSqrt nu S.LPrime P S.n)⁻¹) →
      ∀ (Rfield : ShellSeq d → Vec d → Vec d),
        (∀ (omega : ShellSeq d) (y : Vec d), Rfield omega y =
          matVecMul ((coefficientCutoff nu omega S.LPrime).toCoeffField y -
              (coefficientCutoff nu omega S.ell).toCoeffField y)
            ((w omega).toH1Function.grad y)) →
      ∀ (DRmat : ShellSeq d → Vec d → HilbertMat d),
        (∀ (omega : ShellSeq d) (x : Vec d), DRmat omega x =
          HilbertMat.ofMat (fun i j => DR omega i x j)) →
        (∀ omega : ShellSeq d,
          MemVectorL2 (openCubeSet (originCube d (S.m : ℤ))) (Rfield omega)) →
        (∀ omega : ShellSeq d,
          MemVectorL2 (openCubeSet (originCube d (S.m : ℤ))) (uNGlued omega)) →
        (∀ omega : ShellSeq d,
          MemVectorL2 (openCubeSet (originCube d (S.m : ℤ))) (uTildeGlued omega)) →
        (∀ omega : ShellSeq d,
          MemLp (DRmat omega) 2
            (volume.restrict (openCubeSet (originCube d (S.m : ℤ))))) →
        ((∫⁻ omega : ShellSeq d,
          vecCubeLpENorm (originCube d (S.m : ℤ)) 2 (Rfield omega) ^ (2 : ℕ)
            ∂P.toMeasure) ≠ ⊤) →
        ((∫⁻ omega : ShellSeq d,
          SuperdiffusionCLT.Section2.Norms.cubeLpENorm (originCube d (S.m : ℤ)) 2
            (DRmat omega) ^ (2 : ℕ) ∂P.toMeasure) ≠ ⊤) →
        ((∫⁻ omega : ShellSeq d,
          vecCubeLpENorm (originCube d (S.m : ℤ)) 2
            (fun x => uNGlued omega x - uTildeGlued omega x) ^ (2 : ℕ)
              ∂P.toMeasure) ≠ ⊤) →
        ((∫⁻ omega : ShellSeq d,
          vecCubeLpENorm (originCube d (S.m : ℤ)) 2
            (fun x => uTildeGlued omega x - pTilde) ^ (2 : ℕ) ∂P.toMeasure) ≠ ⊤) →
        (AEMeasurable (fun omega : ShellSeq d =>
          vecCubeLpENorm (originCube d (S.m : ℤ)) 2 (Rfield omega)) P.toMeasure) →
        (AEMeasurable (fun omega : ShellSeq d =>
          SuperdiffusionCLT.Section2.Norms.cubeLpENorm (originCube d (S.m : ℤ)) 2
            (DRmat omega)) P.toMeasure) →
        (AEMeasurable (fun omega : ShellSeq d =>
          vecCubeLpENorm (originCube d (S.m : ℤ)) 2
            (fun x => uNGlued omega x - uTildeGlued omega x)) P.toMeasure) →
        (AEMeasurable (fun omega : ShellSeq d =>
          vecCubeLpENorm (originCube d (S.m : ℤ)) 2
            (fun x => uTildeGlued omega x - pTilde)) P.toMeasure) →
        (Integrable (fun omega : ShellSeq d =>
          volumeAverage (openCubeSet (originCube d (S.m : ℤ)))
            (fun y => vecDot (Rfield omega y)
              (uNGlued omega y - uTildeGlued omega y))) P.toMeasure) →
        (Integrable (fun omega : ShellSeq d =>
          volumeAverage (openCubeSet (originCube d (S.m : ℤ)))
            (fun y => vecDot (Rfield omega y)
              (uTildeGlued omega y - pTilde))) P.toMeasure) →
        (Integrable (fun omega : ShellSeq d =>
          volumeAverage (openCubeSet (originCube d (S.m : ℤ)))
            (fun y => vecDot (Rfield omega y) (pTilde - p))) P.toMeasure) →
        (∀ (omega : ShellSeq d), ∀ z ∈ largeCubeSubcubes d S.n S.m,
          vecCubeLpENorm z 2
              (fun x => Rfield omega x -
                volumeAverageVec (openCubeSet z) (Rfield omega)) ≤
            ENNReal.ofReal (Cpoin * (3 : ℝ) ^ ((S.n : ℕ) : ℝ)) *
              SuperdiffusionCLT.Section2.Norms.cubeLpENorm z 2 (DRmat omega)) →
        (∀ z ∈ largeCubeSubcubes d S.n S.m,
          Measurable[highShellSigma d S.ell]
            (fun omega : ShellSeq d =>
              volumeAverageVec (openCubeSet z) (Rfield omega))) →
        (∀ z ∈ largeCubeSubcubes d S.n S.m,
          Measurable[lowShellSigma d S.ell]
            (fun omega : ShellSeq d =>
              volumeAverageVec (openCubeSet z) (uTildeGlued omega))) →
        (∀ z ∈ largeCubeSubcubes d S.n S.m, ∀ i : Fin d, Integrable
          (fun omega : ShellSeq d =>
            volumeAverageVec (openCubeSet z) (Rfield omega) i) P.toMeasure) →
        (∀ z ∈ largeCubeSubcubes d S.n S.m, ∀ i : Fin d, Integrable
          (fun omega : ShellSeq d =>
            volumeAverageVec (openCubeSet z) (uTildeGlued omega) i) P.toMeasure) →
        (∀ z ∈ largeCubeSubcubes d S.n S.m, ∀ i : Fin d,
          ∫ omega : ShellSeq d,
              volumeAverageVec (openCubeSet z) (uTildeGlued omega) i ∂P.toMeasure =
            pTilde i) →
        |∫ omega : ShellSeq d,
            ((SuperdiffusionCLT.Section2.Estimates.Stream.largeCubeSubcubes d
                S.n S.m).card : ℝ)⁻¹ *
              ∑ z ∈ SuperdiffusionCLT.Section2.Estimates.Stream.largeCubeSubcubes
                d S.n S.m,
                volumeAverage (openCubeSet z)
                  (fun y => vecDot ((w omega).toH1Function.grad y)
                    (matVecMul ((coefficientCutoff nu omega S.LPrime).toCoeffField y -
                      (coefficientCutoff nu omega S.ell).toCoeffField y)
                      (uNGlued omega y - p))) ∂P.toMeasure| ≤
          C * nu ^ (-(3 : ℝ)) * (((S.LPrime : ℕ) : ℝ) ^ (2 : ℕ)) *
            (3 : ℝ) ^ (-((((S.ell - S.n : ℕ) : ℝ)) / 2)) := by

  obtain ⟨C, hC1, hC⟩ := l_RHS_term2_constFirst d hd C₁ C₂ C₃ Cpoin hC₁ hC₂ hC₃ hCpoin
  refine ⟨C, hC1, ?_⟩
  intro nu hnu hnu1 P hPrefix hJ1V2 hJ2 hJ3 hJ4 S hSorder e he p hp w hw
    uNGlued uTildeGlued pTilde DR hDR hRb hPe hPen Rfield hRfield DRmat hDRmat
    hRL2 hUL2 hUtL2 hDRL2 hfinR hfinDR hfinDiff hfinProx hmR hmDR hmDiff hmProx
    hIntDiff hIntProxy hIntMean hPoincare hRmeas hTmeas hRint hTint hmean
  exact hC nu hnu hnu1 P hPrefix hJ1V2 hJ2 hJ3 hJ4 S hSorder e he p hp w hw
    uNGlued uTildeGlued pTilde DR hDR hRb hPe hPen Rfield hRfield DRmat hDRmat
    hRL2 hUL2 hUtL2 hDRL2 hfinR hfinDR hfinDiff hfinProx hmR hmDR hmDiff hmProx
    hIntDiff hIntProxy hIntMean hPoincare
    (decoupling_bridge_of_shellLawJ2 hJ2 hRL2 hUtL2 hRmeas hTmeas hRint hTint hmean
      hIntProxy)

/-! ## The two proxy inputs at the glued carriers -/

section GluedProxy

open scoped Matrix.Norms.Elementwise

/-- A matrix-valued Bochner-integrable observable of the shell sequence,
multiplied on the right by a fixed vector, integrates slot by slot. -/
private theorem integralMatVecMulSeq {mu : Measure (ShellSeq d)}
    {M : ShellSeq d → Mat d} (hM : Integrable M mu) (F : Vec d) :
    ∫ omega : ShellSeq d, matVecMul (M omega) F ∂mu =
      matVecMul (∫ omega : ShellSeq d, M omega ∂mu) F := by
  have hrow : ∀ i j : Fin d, Integrable (fun omega : ShellSeq d => M omega i j) mu :=
    fun i j => (hM.eval i).eval j
  have hcomp : ∀ i : Fin d,
      Integrable (fun omega : ShellSeq d => matVecMul (M omega) F i) mu := fun i =>
    integrable_finsetSum _ fun j _ => (hrow i j).mul_const (F j)
  funext i
  rw [MeasureTheory.eval_integral
    (f := fun omega : ShellSeq d => matVecMul (M omega) F) hcomp i]
  show ∫ omega : ShellSeq d, (∑ j, M omega i j * F j) ∂mu =
    ∑ j, (∫ omega : ShellSeq d, M omega ∂mu) i j * F j
  rw [integral_finsetSum _ fun j _ => (hrow i j).mul_const (F j)]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [integral_mul_const, Homogenization.integral_matrix_apply hM i j]

/-- **The `hTint` input at the glued proxy.**  On *every* sub-cube `z` of the
scale-`k` family — not only the centred one — the `z+cu_k`-average of the glued
field is an integrable observable: by `volumeAverageVec_gluedGradientField` it
is the quenched coarse matrix of that cube against the flux slot, and
`integrable_sigmaStarInvCoarse` of `GluedFieldAverages` integrates the
matrix on every triadic cube. -/
theorem integrable_volumeAverageVec_gluedGradientField [NeZero d] {nu : ℝ}
    (hnu : 0 < nu) {P : ProbabilityMeasure (ShellSeq d)} (hPrefix : ShellLawPrefix d P)
    (hJ2 : ShellLawJ2 d P) (hJ3 : ShellLawJ3 d P) (hJ4 : ShellLawJ4 d P)
    (L k m : ℕ) (F : Vec d) {z : TriadicCube d} (hz : z ∈ largeCubeSubcubes d k m) :
    Integrable (fun omega : ShellSeq d =>
      volumeAverageVec (openCubeSet z)
        (gluedGradientField hnu L k m F omega)) P.toMeasure := by
  have hident : (fun omega : ShellSeq d =>
      volumeAverageVec (openCubeSet z) (gluedGradientField hnu L k m F omega)) =
      fun omega : ShellSeq d => matVecMul (sigmaStarInvCoarse (openCubeSet z)
        (coefficientCutoff nu omega L).toCoeffField) F :=
    funext fun omega => volumeAverageVec_gluedGradientField hnu L k m F omega hz
  rw [hident]
  refine Integrable.of_eval fun i => ?_
  have hrow : ∀ j : Fin d, Integrable (fun omega : ShellSeq d =>
      sigmaStarInvCoarse (openCubeSet z)
        (coefficientCutoff nu omega L).toCoeffField i j) P.toMeasure := fun j =>
    (((integrable_sigmaStarInvCoarse hnu hPrefix hJ2 hJ3 hJ4 L z).eval i).eval j)
  show Integrable (fun omega : ShellSeq d =>
    ∑ j, sigmaStarInvCoarse (openCubeSet z)
      (coefficientCutoff nu omega L).toCoeffField i j * F j) P.toMeasure
  exact integrable_finsetSum _ fun j _ => (hrow j).mul_const (F j)

/-- **`E[(∇ũ_{n,z})_{z+cu_n}] = p̃` on every sub-cube of the family.**
The paper's "by stationarity" is
`integral_sigmaStarInvCoarse_openCubeSet_eq` of `GluedField`, which uses
`ShellLawPrefix` and `ShellLawJ2` and applies verbatim at the coefficient
cutoff level `ℓ` of the proxy; `volumeAverageVec_gluedGradientField` is the
quenched half. -/
theorem integral_volumeAverageVec_gluedGradientField_eq_annealedGluedAverage
    [NeZero d] {nu : ℝ} (hnu : 0 < nu) {P : ProbabilityMeasure (ShellSeq d)}
    (hPrefix : ShellLawPrefix d P) (hJ2 : ShellLawJ2 d P) (hJ3 : ShellLawJ3 d P)
    (hJ4 : ShellLawJ4 d P) (L : ℕ) {k m : ℕ} (hkm : k ≤ m) (F : Vec d)
    {z : TriadicCube d} (hz : z ∈ largeCubeSubcubes d k m) :
    ∫ omega : ShellSeq d,
        volumeAverageVec (openCubeSet z)
          (gluedGradientField hnu L k m F omega) ∂P.toMeasure =
      annealedGluedAverage hnu P L k m F := by
  have hscale : z.scale = (k : ℤ) := scale_of_mem_largeCubeSubcubes hkm hz
  have hI0 : Integrable (fun omega : ShellSeq d =>
      sigmaStarInvCoarse (openCubeSet (originCube d z.scale))
        (coefficientCutoff nu omega L).toCoeffField) P.toMeasure := by
    rw [hscale]
    exact integrable_sigmaStarInvCoarse hnu hPrefix hJ2 hJ3 hJ4 L (originCube d (k : ℤ))
  have hidz : (fun omega : ShellSeq d =>
      volumeAverageVec (openCubeSet z) (gluedGradientField hnu L k m F omega)) =
      fun omega : ShellSeq d => matVecMul (sigmaStarInvCoarse (openCubeSet z)
        (coefficientCutoff nu omega L).toCoeffField) F :=
    funext fun omega => volumeAverageVec_gluedGradientField hnu L k m F omega hz
  have hid0 : (fun omega : ShellSeq d =>
      volumeAverageVec (openCubeSet (originCube d (k : ℤ)))
        (gluedGradientField hnu L k m F omega)) =
      fun omega : ShellSeq d => matVecMul (sigmaStarInvCoarse
        (openCubeSet (originCube d (k : ℤ)))
        (coefficientCutoff nu omega L).toCoeffField) F :=
    funext fun omega => volumeAverageVec_gluedGradientField hnu L k m F omega
      (originCube_mem_largeCubeSubcubes hkm)
  rw [annealedGluedAverage_eq, hidz, hid0,
    integralMatVecMulSeq (integrable_sigmaStarInvCoarse hnu hPrefix hJ2 hJ3 hJ4 L z) F,
    integralMatVecMulSeq (integrable_sigmaStarInvCoarse hnu hPrefix hJ2 hJ3 hJ4 L
      (originCube d (k : ℤ))) F,
    integral_sigmaStarInvCoarse_openCubeSet_eq hPrefix hJ2 nu L z hI0, hscale]

/-- **The `hmean` input at the glued proxy**, coordinate by coordinate. -/
theorem integral_volumeAverageVec_gluedGradientField_apply_eq [NeZero d] {nu : ℝ}
    (hnu : 0 < nu) {P : ProbabilityMeasure (ShellSeq d)} (hPrefix : ShellLawPrefix d P)
    (hJ2 : ShellLawJ2 d P) (hJ3 : ShellLawJ3 d P) (hJ4 : ShellLawJ4 d P)
    (L : ℕ) {k m : ℕ} (hkm : k ≤ m) (F : Vec d)
    {z : TriadicCube d} (hz : z ∈ largeCubeSubcubes d k m) (i : Fin d) :
    ∫ omega : ShellSeq d,
        volumeAverageVec (openCubeSet z)
          (gluedGradientField hnu L k m F omega) i ∂P.toMeasure =
      annealedGluedAverage hnu P L k m F i := by
  rw [← integral_volumeAverageVec_gluedGradientField_eq_annealedGluedAverage hnu
    hPrefix hJ2 hJ3 hJ4 L hkm F hz]
  exact (MeasureTheory.eval_integral
    (f := fun omega : ShellSeq d => volumeAverageVec (openCubeSet z)
      (gluedGradientField hnu L k m F omega))
    (fun j => (integrable_volumeAverageVec_gluedGradientField hnu hPrefix hJ2 hJ3 hJ4
      L k m F hz).eval j) i).symm

end GluedProxy

end

end SuperdiffusionCLT.Section3.Terms
