/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Section8.Prereq.FieldProcessInputJ
public import SuperdiffusionCLT.Section8.DivergenceForm.WholeSpace.KernelIdentification
public import SuperdiffusionCLT.Section8.DivergenceForm.WholeSpace.ResolventTail
public import MarkovProcess.Kernel.ConservativeResolvent

/-!
# Conservativity of the kernel resolvent

Continuous compactly supported cutoffs transfer the analytic constant-one normalization to the
kernel resolvent generated by the `C₀` resolvent of the analytic minimal resolvent.  Both the
analytic and kernel normalizations are stated explicitly, and the generic monotone-class transfer
identifies the kernel resolvent with the analytic minimal resolvent.
-/

@[expose] public section

namespace SuperdiffusionCLT.Section8

open CompactlySupported Homogenization MeasureTheory Set Topology
open SuperdiffusionCLT.Section8.DivergenceForm
open MarkovProcess MarkovProcess.Semigroup
open MarkovProcess.SubMarkovKernelSemigroup
open scoped ENNReal ZeroAtInfty

noncomputable section

variable {d : ℕ} [NeZero d] {A : WholeSpaceAnalyticData d} {Sp : WholeSpaceLocalizedSplitData A}

omit [NeZero d] in
private theorem exists_c0_cutoff_one_on_cube (m : ℕ) :
    ∃ psi : C₀(Vec d, ℝ),
      (∀ y, 0 ≤ psi y) ∧ (∀ y, psi y ≤ 1) ∧
        ∀ y ∈ wholeSpaceCube d m, psi y = 1 := by
  have hcompact : IsCompact (closure (wholeSpaceCube d m)) :=
    (isOpenBoundedConvexDomain_wholeSpaceCube d m).isBoundedDomain.isBounded.isCompact_closure
  obtain ⟨cutoff, hone, hsupport, -, hbounds⟩ :=
    exists_continuousMap_one_of_isCompact_subset_isOpen hcompact isOpen_univ
      (subset_univ _)
  let psi : C₀(Vec d, ℝ) :=
    { toFun := cutoff
      continuous_toFun := cutoff.continuous
      zero_at_infty' := (hasCompactSupport_def.mpr hsupport).is_zero_at_infty }
  refine ⟨psi, fun y ↦ (hbounds y).1, fun y ↦ (hbounds y).2, ?_⟩
  intro y hy
  exact hone (subset_closure hy)

/-- The analytic minimal resolvent of one is bounded by the kernel resolvent
of one generated by the `C₀` resolver. -/
theorem LogGrowthBounds.minimalResolvent_one_le_kernelResolvent
    (T : LogGrowthBounds Sp)
    (mu : PositiveShift) (x : Vec d) :
    A.analyticMinimalResolvent mu
        (fun _ : Vec d ↦ (1 : ℝ)) measurable_const
        (D := 1) (fun _ ↦ by norm_num) x ≤
      (resolvent T).kernelSemigroup.kernelResolvent (mu : ℝ) (fun _ ↦ 1) x := by
  let R := resolvent T
  rw [SuperdiffusionCLT.Section8.DivergenceForm.WholeSpaceAnalyticData.analyticMinimalResolvent]
  refine iSup_le fun m ↦ ?_
  obtain ⟨psi, hpsi0, hpsi1, hpsiCube⟩ :=
    exists_c0_cutoff_one_on_cube (d := d) m
  have hpsiAbs : ∀ y, |psi y| ≤ 1 := by
    intro y
    rw [abs_le]
    exact ⟨(neg_nonpos.mpr zero_le_one).trans (hpsi0 y), hpsi1 y⟩
  have hlocal := A.analyticCubeResolvent_eq_of_eqOn mu
    psi.continuous.measurable measurable_const (D := 1) (E := 1) hpsiAbs
    (fun _ ↦ by norm_num) m hpsiCube x
  have hfinite := A.analyticMinimalResolvent_ne_top mu
    psi.continuous.measurable hpsi0 (by norm_num : (0 : ℝ) ≤ 1) hpsiAbs x
  have hpsiNorm : ∀ y, |psi y| ≤ ‖psi‖ := fun y ↦
    BoundedContinuousFunction.norm_coe_le_norm psi.toBCF y
  have hc0 : R.toContractiveResolvent.operator mu psi x =
      A.analyticMinimalResolventReal mu psi psi.continuous.measurable hpsiAbs x := by
    change A.analyticMinimalResolventReal mu psi psi.continuous.measurable
      hpsiNorm x = _
    apply A.analyticMinimalResolventReal_bound_irrel mu
  have hreal :
      A.analyticMinimalResolventReal mu psi psi.continuous.measurable hpsiAbs x =
        (A.analyticMinimalResolvent mu psi psi.continuous.measurable hpsiAbs x).toReal :=
    A.analyticMinimalResolventReal_eq_toReal mu psi.continuous.measurable
      hpsi0 hpsiAbs x
  have hminimal :
      A.analyticMinimalResolvent mu psi psi.continuous.measurable hpsiAbs x =
        ENNReal.ofReal (R.toContractiveResolvent.operator mu psi x) := by
    calc
      _ = ENNReal.ofReal
          (A.analyticMinimalResolvent mu psi psi.continuous.measurable hpsiAbs x).toReal :=
        (ENNReal.ofReal_toReal hfinite).symm
      _ = ENNReal.ofReal
          (A.analyticMinimalResolventReal mu psi psi.continuous.measurable hpsiAbs x) :=
        congrArg ENNReal.ofReal hreal.symm
      _ = _ := congrArg ENNReal.ofReal hc0.symm
  have hrepresented := R.kernelResolvent_ofReal_eq_operator mu psi hpsi0 x
  have hkernelMono : R.kernelSemigroup.kernelResolvent (mu : ℝ)
      (fun y ↦ ENNReal.ofReal (psi y)) x ≤
      R.kernelSemigroup.kernelResolvent (mu : ℝ) (fun _ ↦ 1) x := by
    apply R.kernelSemigroup.kernelResolvent_mono
    intro y
    exact ENNReal.ofReal_le_one.mpr (hpsi1 y)
  calc
    A.analyticCubeResolventENN mu (fun _ : Vec d ↦ (1 : ℝ))
        measurable_const (fun _ ↦ by norm_num) m x =
      A.analyticCubeResolventENN mu psi psi.continuous.measurable hpsiAbs m x := by
        simp only [WholeSpaceAnalyticData.analyticCubeResolventENN]
        exact congrArg ENNReal.ofReal hlocal.symm
    _ ≤ A.analyticMinimalResolvent mu psi psi.continuous.measurable hpsiAbs x :=
      le_iSup (fun n ↦ A.analyticCubeResolventENN mu psi
        psi.continuous.measurable hpsiAbs n x) m
    _ = ENNReal.ofReal (R.toContractiveResolvent.operator mu psi x) := hminimal
    _ = R.kernelSemigroup.kernelResolvent (mu : ℝ)
        (fun y ↦ ENNReal.ofReal (psi y)) x := hrepresented.symm
    _ ≤ R.kernelSemigroup.kernelResolvent (mu : ℝ) (fun _ ↦ 1) x := hkernelMono

/-- The generated kernel resolvent carries full constant-one mass. -/
theorem LogGrowthBounds.ofReal_mul_kernelResolvent_one
    (T : LogGrowthBounds Sp)
    (mu : PositiveShift) (x : Vec d) :
    ENNReal.ofReal (mu : ℝ) *
      (resolvent T).kernelSemigroup.kernelResolvent (mu : ℝ) (fun _ ↦ 1) x = 1 := by
  let R := resolvent T
  apply le_antisymm
  · calc
      ENNReal.ofReal (mu : ℝ) *
          R.kernelSemigroup.kernelResolvent (mu : ℝ) (fun _ ↦ 1) x ≤
        ENNReal.ofReal (mu : ℝ) * ENNReal.ofReal (mu : ℝ)⁻¹ :=
          mul_le_mul' le_rfl (R.kernelSemigroup.kernelResolvent_one_le mu.property x)
      _ = 1 := by
        rw [← ENNReal.ofReal_mul mu.property.le, mul_inv_cancel₀ mu.property.ne',
          ENNReal.ofReal_one]
  · calc
      1 = ENNReal.ofReal (mu : ℝ) * A.analyticMinimalResolvent mu
          (fun _ : Vec d ↦ (1 : ℝ)) measurable_const
          (D := 1) (fun _ ↦ by norm_num) x :=
        (ofReal_mul_minimalResolvent_one_eq T mu x).symm
      _ ≤ ENNReal.ofReal (mu : ℝ) *
          R.kernelSemigroup.kernelResolvent (mu : ℝ) (fun _ ↦ 1) x :=
        mul_le_mul' le_rfl
          (minimalResolvent_one_le_kernelResolvent T mu x)

/-- The kernel semigroup generated by the analytic minimal
resolvent is conservative. -/
theorem LogGrowthBounds.isConservative_kernelSemigroup
    (T : LogGrowthBounds Sp) :
    (resolvent T).kernelSemigroup.IsConservative := by
  apply SubMarkovKernelSemigroup.isConservative_of_kernelResolvent_one _ one_pos
  intro x
  exact ofReal_mul_kernelResolvent_one T ⟨(1 : ℝ), by norm_num⟩ x

/-- The kernel resolvent generated by the split-skew `C₀` resolver agrees
with the analytic cubic minimal resolvent on every nonnegative measurable
observable bounded by one.  The proof uses both model normalizations and the
generic monotone-class transfer. -/
theorem LogGrowthBounds.kernelResolventIdentifiesAnalyticMinimal
    (T : LogGrowthBounds Sp) :
    A.KernelResolventIdentifiesAnalyticMinimal
      (resolvent T) := by
  let R := resolvent T
  let I : A.KernelIdentificationInput :=
    { R := R
      operator_eq := by
        intro mu f x
        rfl
      kernel_one := ofReal_mul_kernelResolvent_one T
      analytic_one := ofReal_mul_minimalResolvent_one_eq T }
  exact A.kernelResolventIdentifiesAnalyticMinimal_of_input I

end

end SuperdiffusionCLT.Section8
