/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Section2.Annealed.Blocks
public import SuperdiffusionCLT.Assumptions.ShellLaw.J2Consequences
public import Mathlib.Probability.Independence.Integration

/-!
# The coarse block matrix of the cutoff field reads only the first shells

The proof of `l.b.ell.homogenization` factorizes an expectation
by range of dependence: the perturbation factor of the localization step is
measurable with respect to the shells `k < r <= l`, the coarse block matrix
`bfA_k(cu_n)` of the cutoff field `a_k = nu Id + k_k` is measurable with respect
to the shells `r <= k`, the two collections are independent by **J2**, and hence
the expectation of the product is the product of the expectations.

This module proves the two halves of that display that concern `bfA_k(cu_n)`.

## The sub-sigma-field of the first shells

`streamCutoff omega k = sum_{r <= k} j_r` is a finite sum of the coordinates
indexed by `Set.Iic k`, so it is measurable for the sigma-field
`indexSigma (fun F => F) (Set.Iic k)` generated by exactly those coordinates,
and so is `coefficientCutoff nu omega k`. The measurability of the four coarse
blocks in the source field is already proved for an arbitrary measurable space
on the sample carrier (`measurable_coarseBlockMatrix_upperLeft_apply` and its
companions in `Section2/Annealed/Measurability.lean`), so it applies verbatim in
the sub-sigma-field, with the unconditional admissibility of the cutoff field
supplying the ellipticity hypothesis at every sample.

## The product expectation

`integral_mul_of_indep_of_measurable` is the generic statement that two real
observables measurable for independent sub-sigma-fields have
`E[X Y] = E[X] E[Y]`; it is `ProbabilityTheory.IndepFun.integral_fun_mul_eq_mul_integral`
after transporting the independence of the sigma-fields along the comaps of the
two observables. No integrability hypothesis is needed: when either factor fails
to be integrable both sides vanish.

Specialized to the disjoint index sets `Set.Iic k` and `Set.Ioc k l` under
**J2**, and applied to the entries of `bfA_k(cu_Q)`, this gives the printed
factorization for an arbitrary observable of the shells `k < r <= l`. The
perturbation factor itself is defined elsewhere; every statement below is stated
for an abstract `Y`, so it can be instantiated at that factor.

## Main results

* `indexSigma_shellSeq_le`, `measurable_shellReg_indexSigma`,
  `measurable_streamCutoff_indexSigma`,
  `measurable_coefficientCutoff_indexSigma`: the cutoff at level `k` is a
  function of the shells `r <= k`.
* `measurable_coarseBlockMatrix_coefficientCutoff_indexSigma` and its three
  companions, and `measurable_blockMatEntry_coarseBlockMatrix_coefficientCutoff_indexSigma`:
  every entry of `bfA_k(cu_Q)` is measurable for `indexSigma (Set.Iic k)`.
* `integral_mul_of_indep_of_measurable`: the product expectation for two
  observables of independent sub-sigma-fields.
* `indep_indexSigma_Iic_Ioc`: independence of the two index sigma-fields
  under **J2**.
* `integral_mul_of_indexSigma_Iic_Ioc`: the product expectation for those two
  sigma-fields.
* `integral_mul_blockMatEntry_coarseBlockMatrix_coefficientCutoff` and the four
  block forms: the factorization at the entries of `bfA_k(cu_Q)`.
* `blockMatEntry_integral_smul_coarseBlockMatrix_coefficientCutoff`:
  `E[Y bfA_k(cu_Q)] = E[Y] bfAhom_k(cu_Q)` entrywise.
-/

@[expose] public section

namespace SuperdiffusionCLT.Section3.HighContrast

open Homogenization MeasureTheory ProbabilityTheory
open SuperdiffusionCLT.Frozen.Assumptions
open SuperdiffusionCLT.Frozen.Section2
open SuperdiffusionCLT.Section2.Annealed
open SuperdiffusionCLT.Section2.Cutoff
open SuperdiffusionCLT.Probability

variable {d : ℕ}

/-! ## The sigma-field of the first shells -/

/-- Every index sigma-field of the shell sequence is a sub-sigma-field of the
product sigma-field of the carrier. -/
theorem indexSigma_shellSeq_le (I : Set ℕ) :
    indexSigma (fun F : ShellSeq d ↦ F) I ≤
      (inferInstance : MeasurableSpace (ShellSeq d)) := by
  refine iSup₂_le fun i _ ↦ ?_
  exact (ShellField.measurable_shellCoordinate i).comap_le

/-- A shell coordinate whose index lies in `I` is measurable for the index
sigma-field of `I`, as a regular coefficient field. -/
theorem measurable_shellReg_indexSigma {I : Set ℕ} {n : ℕ} (hn : n ∈ I) :
    Measurable[indexSigma (fun F : ShellSeq d ↦ F) I]
      (fun omega : ShellSeq d ↦ shellReg omega n) :=
  ShellField.measurable_forgetShell.comp
    (measurable_coordinate_of_mem (fun F : ShellSeq d ↦ F) hn)

/-- **The infrared cutoff at level `k` reads only the shells `r <= k`.** It is
the sum of those `k + 1` coordinates. -/
theorem measurable_streamCutoff_indexSigma (k : ℕ) :
    Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k)]
      (fun omega : ShellSeq d ↦ streamCutoff omega k) := by
  unfold streamCutoff
  refine Finset.measurable_sum _ fun n hn ↦ ?_
  exact measurable_shellReg_indexSigma
    (Set.mem_Iic.mpr (Nat.lt_succ_iff.mp (Finset.mem_range.mp hn)))

/-- The cutoff coefficient field `a_k = nu Id + k_k` reads only the shells
`r <= k`. -/
theorem measurable_coefficientCutoff_indexSigma (nu : ℝ) (k : ℕ) :
    Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k)]
      (fun omega : ShellSeq d ↦ coefficientCutoff nu omega k) :=
  measurable_const.add (measurable_streamCutoff_indexSigma k)

/-! ## The coarse block matrix of the cutoff field reads only the first shells -/

/-- **The upper-left block of `bfA_k(cu_Q)` reads only the shells `r <= k`.** -/
theorem measurable_coarseBlockMatrix_coefficientCutoff_indexSigma [NeZero d] {nu : ℝ}
    (hnu : 0 < nu) (k : ℕ) (Q : TriadicCube d) (i j : Fin d) :
    Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k)]
      (fun omega : ShellSeq d ↦
        (coarseBlockMatrix (cubeSet Q) (coefficientCutoff nu omega k).toFun).upperLeft i j) :=
  @measurable_coarseBlockMatrix_upperLeft_apply d (ShellSeq d)
    (indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k))
    (fun omega ↦ coefficientCutoff nu omega k)
    (measurable_coefficientCutoff_indexSigma nu k)
    (fun omega ↦ aeLocallyUniformlyEllipticField_coefficientCutoff hnu omega k) Q i j

/-- The upper-right block of `bfA_k(cu_Q)` reads only the shells `r <= k`. -/
theorem measurable_coarseBlockMatrix_coefficientCutoff_upperRight_indexSigma [NeZero d]
    {nu : ℝ} (hnu : 0 < nu) (k : ℕ) (Q : TriadicCube d) (i j : Fin d) :
    Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k)]
      (fun omega : ShellSeq d ↦
        (coarseBlockMatrix (cubeSet Q) (coefficientCutoff nu omega k).toFun).upperRight i j) :=
  @measurable_coarseBlockMatrix_upperRight_apply d (ShellSeq d)
    (indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k))
    (fun omega ↦ coefficientCutoff nu omega k)
    (measurable_coefficientCutoff_indexSigma nu k)
    (fun omega ↦ aeLocallyUniformlyEllipticField_coefficientCutoff hnu omega k) Q i j

/-- The lower-left block of `bfA_k(cu_Q)` reads only the shells `r <= k`. -/
theorem measurable_coarseBlockMatrix_coefficientCutoff_lowerLeft_indexSigma [NeZero d]
    {nu : ℝ} (hnu : 0 < nu) (k : ℕ) (Q : TriadicCube d) (i j : Fin d) :
    Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k)]
      (fun omega : ShellSeq d ↦
        (coarseBlockMatrix (cubeSet Q) (coefficientCutoff nu omega k).toFun).lowerLeft i j) :=
  @measurable_coarseBlockMatrix_lowerLeft_apply d (ShellSeq d)
    (indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k))
    (fun omega ↦ coefficientCutoff nu omega k)
    (measurable_coefficientCutoff_indexSigma nu k)
    (fun omega ↦ aeLocallyUniformlyEllipticField_coefficientCutoff hnu omega k) Q i j

/-- The lower-right block of `bfA_k(cu_Q)` reads only the shells `r <= k`. -/
theorem measurable_coarseBlockMatrix_coefficientCutoff_lowerRight_indexSigma [NeZero d]
    {nu : ℝ} (hnu : 0 < nu) (k : ℕ) (Q : TriadicCube d) (i j : Fin d) :
    Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k)]
      (fun omega : ShellSeq d ↦
        (coarseBlockMatrix (cubeSet Q) (coefficientCutoff nu omega k).toFun).lowerRight i j) :=
  @measurable_coarseBlockMatrix_lowerRight_apply d (ShellSeq d)
    (indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k))
    (fun omega ↦ coefficientCutoff nu omega k)
    (measurable_coefficientCutoff_indexSigma nu k)
    (fun omega ↦ aeLocallyUniformlyEllipticField_coefficientCutoff hnu omega k) Q i j

/-- **Every entry of `bfA_k(cu_Q)` reads only the shells `r <= k`.** -/
theorem measurable_blockMatEntry_coarseBlockMatrix_coefficientCutoff_indexSigma [NeZero d]
    {nu : ℝ} (hnu : 0 < nu) (k : ℕ) (Q : TriadicCube d) (alpha beta : BlockCoord d) :
    Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k)]
      (fun omega : ShellSeq d ↦
        blockMatEntry
          (coarseBlockMatrix (cubeSet Q) (coefficientCutoff nu omega k).toFun) alpha beta) := by
  cases alpha with
  | inl i =>
      cases beta with
      | inl j =>
          exact measurable_coarseBlockMatrix_coefficientCutoff_indexSigma hnu k Q i j
      | inr j =>
          exact measurable_coarseBlockMatrix_coefficientCutoff_upperRight_indexSigma hnu k Q i j
  | inr i =>
      cases beta with
      | inl j =>
          exact measurable_coarseBlockMatrix_coefficientCutoff_lowerLeft_indexSigma hnu k Q i j
      | inr j =>
          exact measurable_coarseBlockMatrix_coefficientCutoff_lowerRight_indexSigma hnu k Q i j

/-! ## The product expectation -/

/-- **The expectation of a product factorizes across independent
sub-sigma-fields.** No integrability hypothesis is needed: if either factor
fails to be integrable, both sides are zero. -/
theorem integral_mul_of_indep_of_measurable {Omega : Type*}
    {m1 m2 mOmega : MeasurableSpace Omega} {mu : Measure Omega}
    (hm1 : m1 ≤ mOmega) (hm2 : m2 ≤ mOmega) (hindep : Indep m1 m2 mu)
    {X Y : Omega → ℝ} (hX : Measurable[m1] X) (hY : Measurable[m2] Y) :
    ∫ omega, X omega * Y omega ∂mu =
      (∫ omega, X omega ∂mu) * ∫ omega, Y omega ∂mu := by
  have hXY : IndepFun X Y mu :=
    (IndepFun_iff_Indep X Y mu).2
      (indep_of_indep_of_le_right (indep_of_indep_of_le_left hindep hX.comap_le) hY.comap_le)
  exact hXY.integral_fun_mul_eq_mul_integral
    (hX.mono hm1 le_rfl).aestronglyMeasurable (hY.mono hm2 le_rfl).aestronglyMeasurable

/-- The two index sets of the localization step are disjoint. -/
private theorem disjoint_Iic_Ioc (k l : ℕ) : Disjoint (Set.Iic k) (Set.Ioc k l) := by
  rw [Set.disjoint_left]
  intro n hn hn'
  simp only [Set.mem_Iic] at hn
  simp only [Set.mem_Ioc] at hn'
  omega

/-- **Under J2 the shells `r <= k` and the shells `k < r <= l` are
independent.** -/
theorem indep_indexSigma_Iic_Ioc {P : ProbabilityMeasure (ShellSeq d)}
    (hJ2 : ShellLawJ2 d P) (k l : ℕ) :
    Indep (indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k))
      (indexSigma (fun F : ShellSeq d ↦ F) (Set.Ioc k l)) P.toMeasure :=
  hJ2.indep_subcollections _ _ (disjoint_Iic_Ioc k l)

/-- **The printed factorization of the expectation**: an
observable of the shells `k < r <= l` and an observable of the shells `r <= k`
are independent, so the expectation of their product is the product of the
expectations. -/
theorem integral_mul_of_indexSigma_Iic_Ioc {P : ProbabilityMeasure (ShellSeq d)}
    (hJ2 : ShellLawJ2 d P) {k l : ℕ} {X Y : ShellSeq d → ℝ}
    (hX : Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Iic k)] X)
    (hY : Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Ioc k l)] Y) :
    ∫ omega, Y omega * X omega ∂P.toMeasure =
      (∫ omega, Y omega ∂P.toMeasure) * ∫ omega, X omega ∂P.toMeasure :=
  integral_mul_of_indep_of_measurable (indexSigma_shellSeq_le _)
    (indexSigma_shellSeq_le _) (indep_indexSigma_Iic_Ioc hJ2 k l).symm hY hX

/-! ## The factorization at the entries of the coarse block matrix -/

/-- The scalar action on doubled block matrices is entrywise. -/
theorem blockMatEntry_smul (c : ℝ) (A : BlockMat d) (alpha beta : BlockCoord d) :
    blockMatEntry (c • A) alpha beta = c * blockMatEntry A alpha beta := by
  cases alpha <;> cases beta <;> rfl

/-- An entry of the annealed block matrix is the expectation of the
corresponding entry of the coarse block matrix. -/
theorem blockMatEntry_annealedBlockMatrix (nu : ℝ) (m : ℕ)
    (P : ProbabilityMeasure (ShellSeq d)) (U : Set (Vec d))
    (alpha beta : BlockCoord d) :
    blockMatEntry (annealedBlockMatrix nu m P U) alpha beta =
      ∫ omega, blockMatEntry
        (coarseBlockMatrix U (coefficientCutoff nu omega m).toFun) alpha beta ∂P.toMeasure := by
  cases alpha <;> cases beta <;> rfl

variable [NeZero d] {nu : ℝ} {P : ProbabilityMeasure (ShellSeq d)} {k l : ℕ}
  {Y : ShellSeq d → ℝ}

/-- **The factorization at an entry of `bfA_k(cu_Q)`**: an observable of the
shells `k < r <= l` factors out of the expectation of that entry. -/
theorem integral_mul_blockMatEntry_coarseBlockMatrix_coefficientCutoff (hnu : 0 < nu)
    (hJ2 : ShellLawJ2 d P) (Q : TriadicCube d)
    (hY : Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Ioc k l)] Y)
    (alpha beta : BlockCoord d) :
    ∫ omega, Y omega * blockMatEntry
        (coarseBlockMatrix (cubeSet Q) (coefficientCutoff nu omega k).toFun)
        alpha beta ∂P.toMeasure =
      (∫ omega, Y omega ∂P.toMeasure) *
        blockMatEntry (annealedBlockMatrix nu k P (cubeSet Q)) alpha beta := by
  rw [blockMatEntry_annealedBlockMatrix]
  exact integral_mul_of_indexSigma_Iic_Ioc hJ2
    (measurable_blockMatEntry_coarseBlockMatrix_coefficientCutoff_indexSigma hnu k Q alpha beta) hY

/-- **`E[Y bfA_k(cu_Q)] = E[Y] bfAhom_k(cu_Q)`, entrywise**, for an observable
`Y` of the shells `k < r <= l`. This is the form in which the random scalar
factor of the localization step leaves the annealed comparison. -/
theorem blockMatEntry_integral_smul_coarseBlockMatrix_coefficientCutoff (hnu : 0 < nu)
    (hJ2 : ShellLawJ2 d P) (Q : TriadicCube d)
    (hY : Measurable[indexSigma (fun F : ShellSeq d ↦ F) (Set.Ioc k l)] Y)
    (alpha beta : BlockCoord d) :
    ∫ omega, blockMatEntry
        (Y omega • coarseBlockMatrix (cubeSet Q) (coefficientCutoff nu omega k).toFun)
        alpha beta ∂P.toMeasure =
      blockMatEntry ((∫ omega, Y omega ∂P.toMeasure) •
        annealedBlockMatrix nu k P (cubeSet Q)) alpha beta := by
  simp only [blockMatEntry_smul]
  exact integral_mul_blockMatEntry_coarseBlockMatrix_coefficientCutoff hnu hJ2 Q hY alpha beta

end SuperdiffusionCLT.Section3.HighContrast
