/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
module

public import SuperdiffusionCLT.Section7.Analytic.Geometry.IndicatorMultiscale
public import SuperdiffusionCLT.Section7.Analytic.Geometry.BoundaryLayer
public import Mathlib.MeasureTheory.Function.Floor

/-!
# The triadic filtration of the unit cube

`kc2_Q0 d = [-1/2, 1/2)^d` is the unit cube, `kc2_proj j` records the generation-`j` triadic cell of
a point of it (a constant `0` outside), and `kc2_sig j` is the sigma-algebra the cells generate.
These sigma-algebras increase with `j`, the first is trivial, and each lies in the Lebesgue
sigma-algebra.
-/

@[expose] public section

namespace SuperdiffusionCLT.Section7

open MeasureTheory Homogenization

variable {d : ℕ}

/-- The unit cube `[-1/2, 1/2)^d` (half-open; it differs from the open cube by a null set). -/
def kc2_Q0 (d : ℕ) : Set (Vec d) := Set.pi Set.univ fun _ => Set.Ico (-(1 / 2 : ℝ)) (1 / 2)

theorem kc2_Q0_measurable : MeasurableSet (kc2_Q0 d) :=
  MeasurableSet.univ_pi fun _ => measurableSet_Ico

theorem kc2_mem_Q0 {x : Vec d} : x ∈ kc2_Q0 d ↔ ∀ i, -(1 / 2 : ℝ) ≤ x i ∧ x i < 1 / 2 := by
  simp [kc2_Q0, Set.mem_pi]

theorem kc2_volume_Q0 : volume (kc2_Q0 d) = 1 := by
  rw [kc2_Q0, Real.volume_pi_Ico]
  have : (2⁻¹ + 2⁻¹ : ℝ) = 1 := by norm_num
  simp [this]

instance kc2_finite : IsFiniteMeasure ((volume : Measure (Vec d)).restrict (kc2_Q0 d)) :=
  ⟨by simp [kc2_volume_Q0]⟩

/-- The triadic cell index of generation `j`. -/
noncomputable def kc2_idx (j : ℕ) (x : Vec d) : Fin d → ℤ :=
  fun i => ⌊(3 : ℝ) ^ j * (x i + 1 / 2)⌋

/-- The generation-`j` cell of a point of the unit cube, and `0` outside the cube. -/
noncomputable def kc2_proj (j : ℕ) (x : Vec d) : Fin d → ℤ :=
  open Classical in if x ∈ kc2_Q0 d then kc2_idx j x else 0

/-- The sigma-algebra generated by the generation-`j` cells. -/
noncomputable abbrev kc2_sig (d j : ℕ) : MeasurableSpace (Vec d) :=
  MeasurableSpace.comap (kc2_proj j) inferInstance

theorem kc2_measurable_proj (j : ℕ) : Measurable (kc2_proj (d := d) j) := by
  unfold kc2_proj
  refine Measurable.ite kc2_Q0_measurable ?_ measurable_const
  refine measurable_pi_iff.2 fun i => ?_
  exact Int.measurable_floor.comp (by fun_prop)

theorem kc2_sig_le (j : ℕ) : kc2_sig d j ≤ (inferInstance : MeasurableSpace (Vec d)) :=
  (kc2_measurable_proj j).comap_le

/-- The generation-`j` cell is determined by the generation-`j+1` cell: integer division by `3`. -/
theorem kc2_proj_succ (j : ℕ) (x : Vec d) :
    kc2_proj j x = fun i => kc2_proj (j + 1) x i / 3 := by
  unfold kc2_proj
  by_cases hx : x ∈ kc2_Q0 d
  · simp only [hx, ↓reduceIte]
    funext i
    simp only [kc2_idx]
    have := Int.floor_div_natCast ((3 : ℝ) ^ (j + 1) * (x i + 1 / 2)) 3
    have e : (3 : ℝ) ^ (j + 1) * (x i + 1 / 2) / ((3 : ℕ) : ℝ) = (3 : ℝ) ^ j * (x i + 1 / 2) := by
      push_cast
      ring
    rw [e] at this
    simpa using this
  · simp only [hx, ↓reduceIte]
    funext i
    simp

theorem kc2_sig_mono (j : ℕ) : kc2_sig d j ≤ kc2_sig d (j + 1) := by
  have hf := fun x : Vec d => kc2_proj_succ (d := d) j x
  have hψ : Measurable (fun n : Fin d → ℤ => fun i => n i / 3) := measurable_of_countable _
  have : kc2_proj (d := d) j = (fun n : Fin d → ℤ => fun i => n i / 3) ∘ kc2_proj (j + 1) :=
    funext hf
  unfold kc2_sig
  rw [this, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono hψ.comap_le

theorem kc2_sig_zero : kc2_sig d 0 = ⊥ := by
  have : kc2_proj (d := d) 0 = fun _ => 0 := by
    funext x
    unfold kc2_proj
    by_cases hx : x ∈ kc2_Q0 d
    · simp only [hx, ↓reduceIte]
      funext i
      obtain ⟨h1, h2⟩ := kc2_mem_Q0.1 hx i
      simp only [kc2_idx, pow_zero, one_mul]
      exact Int.floor_eq_zero_iff.2 ⟨by linarith only [h1], by linarith only [h2]⟩
    · simp [hx]
  unfold kc2_sig
  rw [this]
  exact MeasurableSpace.comap_const _

/-! ### Cells of the filtration are small, and cells straddling `W` lie in its boundary layer -/

theorem kc2_norm_sub_lt {j : ℕ} {x y : Vec d} (hx : x ∈ kc2_Q0 d) (hy : y ∈ kc2_Q0 d)
    (h : kc2_proj j x = kc2_proj j y) : ‖x - y‖ < ((3 : ℝ) ^ j)⁻¹ := by
  have hp : (0 : ℝ) < ((3 : ℝ) ^ j)⁻¹ := by positivity
  rw [pi_norm_lt_iff hp]
  intro i
  simp only [kc2_proj, hx, hy, ↓reduceIte] at h
  have h1 : |(3 : ℝ) ^ j * (x i + 1 / 2) - (3 : ℝ) ^ j * (y i + 1 / 2)| < 1 :=
    Int.abs_sub_lt_one_of_floor_eq_floor (congrFun h i)
  have e : (3 : ℝ) ^ j * (x i + 1 / 2) - (3 : ℝ) ^ j * (y i + 1 / 2) =
      (3 : ℝ) ^ j * (x i - y i) := by ring
  rw [e, abs_mul, abs_of_pos (by positivity : (0 : ℝ) < (3 : ℝ) ^ j)] at h1
  rw [Real.norm_eq_abs, Pi.sub_apply]
  have h3 : (0 : ℝ) < (3 : ℝ) ^ j := by positivity
  calc |x i - y i| = ((3 : ℝ) ^ j)⁻¹ * ((3 : ℝ) ^ j * |x i - y i|) := by field_simp
    _ < ((3 : ℝ) ^ j)⁻¹ * 1 := mul_lt_mul_of_pos_left h1 hp
    _ = _ := mul_one _

theorem kc2_infDist_le {W : Set (Vec d)} (hW : IsOpen W) {x v : Vec d} (hx : x ∈ W)
    (hv : v ∉ W) : Metric.infDist x (frontier W) ≤ ‖x - v‖ := by
  have hs : IsPreconnected (segment ℝ x v) := (convex_segment x v).isPreconnected
  have hne : (segment ℝ x v ∩ frontier W).Nonempty := by
    by_contra hcon
    rw [Set.not_nonempty_iff_eq_empty] at hcon
    have hsub : segment ℝ x v ⊆ W ∪ (closure W)ᶜ := by
      intro p hp
      by_cases hpc : p ∈ closure W
      · left
        by_contra hpW
        have : p ∈ frontier W := ⟨hpc, by rwa [hW.interior_eq]⟩
        exact (Set.eq_empty_iff_forall_notMem.1 hcon) p ⟨hp, this⟩
      · right
        exact hpc
    have hdisj : Disjoint W (closure W)ᶜ :=
      Set.disjoint_compl_right_iff_subset.2 subset_closure
    rcases hs.subset_or_subset hW isClosed_closure.isOpen_compl hdisj hsub with h | h
    · exact hv (h (right_mem_segment ℝ x v))
    · exact h (left_mem_segment ℝ x v) (subset_closure hx)
  obtain ⟨p, hp, hpf⟩ := hne
  obtain ⟨a, b, ha, hb, hab, rfl⟩ := hp
  refine (Metric.infDist_le_dist_of_mem hpf).trans ?_
  rw [dist_eq_norm]
  have e : x - (a • x + b • v) = b • (x - v) := by
    have : a = 1 - b := by linarith only [hab]
    subst this
    module
  rw [e, norm_smul, Real.norm_eq_abs, abs_of_nonneg hb]
  have : b ≤ 1 := by linarith only [hab, ha]
  exact mul_le_of_le_one_left (norm_nonneg _) this

/-! ### The sup-times-`L¹` form of the pairing -/

theorem kc2_abs_integral_mul_le_sup {Ω : Type*} {m0 : MeasurableSpace Ω} {μ : Measure Ω}
    {a b : Ω → ℝ} {A : ℝ} (hab : Integrable (fun x => a x * b x) μ)
    (hb : Integrable b μ) (ha : ∀ᵐ x ∂μ, |a x| ≤ A) :
    |∫ x, a x * b x ∂μ| ≤ A * ∫ x, |b x| ∂μ := by
  refine (abs_integral_le_integral_abs).trans ?_
  rw [← integral_const_mul]
  refine integral_mono_ae hab.abs (hb.abs.const_mul A) ?_
  filter_upwards [ha] with x hx
  rw [abs_mul]
  exact mul_le_mul_of_nonneg_right hx (abs_nonneg _)

theorem kc2_pairing_sup {Ω : Type*} {m0 : MeasurableSpace Ω} {μ : Measure Ω} [IsFiniteMeasure μ]
    {m : ℕ → MeasurableSpace Ω} (hm0 : ∀ j, m j ≤ m0) (hmono : ∀ j, m j ≤ m (j + 1))
    {f h : Ω → ℝ} (hf : MemLp f 2 μ) (hh : MemLp h 2 μ) (J : ℕ) (Dseq : ℕ → ℝ) (R : ℝ)
    (hD : ∀ t < J, ∀ᵐ x ∂μ, |kc2_incr μ m f t x| ≤ Dseq t)
    (hR : ∀ᵐ x ∂μ, |f x - (μ[f | m J]) x| ≤ R) :
    |∫ x, f x * h x ∂μ - ∫ x, (μ[f | m 0]) x * (μ[h | m 0]) x ∂μ| ≤
      ∑ t ∈ Finset.range J, Dseq t * ∫ x, |kc2_incr μ m h t x| ∂μ +
        R * ∫ x, |h x - (μ[h | m J]) x| ∂μ := by
  have ht := kc2_telescope hm0 hmono hf hh J
  have e : ∫ x, f x * h x ∂μ - ∫ x, (μ[f | m 0]) x * (μ[h | m 0]) x ∂μ =
      ∑ j ∈ Finset.range J, ∫ x, kc2_incr μ m f j x * kc2_incr μ m h j x ∂μ +
      ∫ x, (f x - (μ[f | m J]) x) * (h x - (μ[h | m J]) x) ∂μ := by
    linarith only [ht]
  rw [e]
  have hinc : ∀ (u : Ω → ℝ), MemLp u 2 μ → ∀ j, MemLp (kc2_incr μ m u j) 2 μ := fun u hu j =>
    (hu.condExp (by norm_num)).sub (hu.condExp (by norm_num))
  refine (abs_add_le _ _).trans (add_le_add ?_ ?_)
  · refine (Finset.abs_sum_le_sum_abs _ _).trans (Finset.sum_le_sum fun j hj => ?_)
    exact kc2_abs_integral_mul_le_sup ((hinc f hf j).integrable_mul (hinc h hh j))
      ((hinc h hh j).integrable (by norm_num)) (hD j (Finset.mem_range.1 hj))
  · exact kc2_abs_integral_mul_le_sup
      ((hf.sub (hf.condExp (by norm_num))).integrable_mul (hh.sub (hh.condExp (by norm_num))))
      ((hh.sub (hh.condExp (by norm_num))).integrable (by norm_num)) hR

/-- `L¹` best approximation up to a factor two. -/
theorem kc2_l1_remainder_le {Ω : Type*} {m0 : MeasurableSpace Ω} {μ : Measure Ω}
    [IsFiniteMeasure μ] {m : MeasurableSpace Ω} (hm : m ≤ m0) {f H : Ω → ℝ}
    (hf : Integrable f μ) (hH : Integrable H μ) (hHm : StronglyMeasurable[m] H) :
    ∫ x, |f x - (μ[f | m]) x| ∂μ ≤ 2 * ∫ x, |f x - H x| ∂μ := by
  have hHe : μ[H | m] = H := condExp_of_stronglyMeasurable hm hHm hH
  have hsub : μ[H - f | m] =ᵐ[μ] μ[H | m] - μ[f | m] := condExp_sub hH hf m
  have h1 : ∫ x, |(μ[H - f | m]) x| ∂μ ≤ ∫ x, |(H - f) x| ∂μ := integral_abs_condExp_le _
  have hE : Integrable (μ[f | m]) μ := integrable_condExp
  have h2 : ∫ x, |H x - (μ[f | m]) x| ∂μ ≤ ∫ x, |f x - H x| ∂μ := by
    have : ∫ x, |H x - (μ[f | m]) x| ∂μ = ∫ x, |(μ[H - f | m]) x| ∂μ := by
      refine integral_congr_ae ?_
      filter_upwards [hsub] with x hx
      rw [hx, hHe]
      rfl
    rw [this]
    refine h1.trans (le_of_eq (integral_congr_ae (Filter.Eventually.of_forall fun x => ?_)))
    simp only [Pi.sub_apply]
    rw [abs_sub_comm]
  have h3 : ∫ x, |f x - (μ[f | m]) x| ∂μ ≤
      ∫ x, |f x - H x| ∂μ + ∫ x, |H x - (μ[f | m]) x| ∂μ := by
    have j1 : Integrable (fun x => |f x - H x|) μ := (hf.sub hH).abs
    have j2 : Integrable (fun x => |H x - (μ[f | m]) x|) μ := (hH.sub hE).abs
    have j3 : Integrable (fun x => |f x - (μ[f | m]) x|) μ := (hf.sub hE).abs
    rw [← integral_add j1 j2]
    refine integral_mono j3 (j1.add j2) fun x => ?_
    have := abs_add_le (f x - H x) (H x - (μ[f | m]) x)
    simpa using this
  linarith only [h2, h3]

theorem kc2_incr_l1_le {Ω : Type*} {m0 : MeasurableSpace Ω} {μ : Measure Ω}
    [IsFiniteMeasure μ] {m : ℕ → MeasurableSpace Ω} {f : Ω → ℝ} (hf : Integrable f μ) (t : ℕ) :
    ∫ x, |kc2_incr μ m f t x| ∂μ ≤ ∫ x, |f x - (μ[f | m (t + 1)]) x| ∂μ +
      ∫ x, |f x - (μ[f | m t]) x| ∂μ := by
  have hE1 : Integrable (μ[f | m (t + 1)]) μ := integrable_condExp
  have hE0 : Integrable (μ[f | m t]) μ := integrable_condExp
  have j1 : Integrable (fun x => |f x - (μ[f | m (t + 1)]) x|) μ := (hf.sub hE1).abs
  have j2 : Integrable (fun x => |f x - (μ[f | m t]) x|) μ := (hf.sub hE0).abs
  have j3 : Integrable (fun x => |kc2_incr μ m f t x|) μ := (hE1.sub hE0).abs
  rw [← integral_add j1 j2]
  refine integral_mono j3 (j1.add j2) fun x => ?_
  simp only [kc2_incr]
  have := abs_sub_le (μ[f | m (t + 1)] x) (f x) (μ[f | m t] x)
  rw [abs_sub_comm (μ[f | m (t + 1)] x) (f x)] at this
  simpa using this

end SuperdiffusionCLT.Section7
